varnishcache/varnish-cache

bin/varnishd/cache/cache_backend_cfg.c
I've already send this patch to the dev-list and got and OK from PHK.
This PR is to let everyone know what this patch is for:
in 'varnishadm backend.list' it also logs when a backend's health was last changed.
=> Add "last updated" timestamp for backend health in varnishadm

lib/libvarnishtools/vut.c
I encountered three instances of Varnish 4.0.1 running on separate Ubuntu 14.04 virtual machines where `varnishlog -d` had output `Log overrun` followed by `Log reacquired` and had switched to ignoring the `-d` switch and began tailing the log indefinitely.
There was a [Trac ticket 1345](https://www.varnish-cache.org/trac/ticket/1345) for the original issue of `-d` not being honoured at all which was fixed in commit 047c517f210348d631eec949df9231c27ce7b759.
The commit modified the `VSL_CursorVSM` call in `VUT_Setup` to add the `VSL_COPT_TAILSTOP` flag if the `-d` switch had been specified. However, there is a second call to `VSL_CursorVSM` call in `VUT_Main` which is used in the `Log reqacquired` scenario. My change duplicates the logic to conditionally add the `VSL_COPT_TAILSTOP` flag …
=> Maintain `-d` behaviour when log is overrun and reacquired

bin/varnishstat/varnishstat_curses.c
the hit ratio is calculated as: hr / (hr + mr), where:
* hr =  (hit - hitrate.lhit) / dt;
* mr = (miss - hitrate.lmiss) / dt;
therefore, if we substitute hr and mr with the previous definitions we get:
[(hit - hitrate.lhit) / dt] / [(miss - hitrate.lmiss) / dt;]
and we can simplify `dt`
=> Remote variables not necessary to calculate the hit-rate

bin/varnishd/cache/cache_acceptor.c, bin/varnishd/cache/cache_backend_probe.c, bin/varnishd/cache/cache_ban_lurker.c, bin/varnishd/cache/cache_expire.c, bin/varnishd/cache/cache_pool.c, bin/varnishd/cache/cache_shmlog.c, bin/varnishd/cache/cache_vrt_priv.c, bin/varnishd/cache/cache_wrk.c, bin/varnishd/hash/hash_critbit.c, bin/varnishd/hpack/vhp_decode.c, bin/varnishd/storage/storage_persistent.c, bin/varnishd/waiter/cache_waiter_poll.c, bin/varnishhist/varnishhist.c, bin/varnishtest/vtc_server.c, bin/varnishtop/varnishtop.c, configure.ac, include/vdef.h, lib/libvarnish/vcli_proto.c, lib/libvarnishapi/vsl_query.c
- use `NEEDLESS` macro to no-op code which is never reached
- use `SUNCCPRAGMA` macro to selectively silence warnings
Not sure if there are better / less intrusive ways of achieving the same goal
=> be friendly to Sun CC aka Solaris Studio

doc/sphinx/reference/varnishtest.rst
To avoid surprises on the user side, document the default timeout for `varnishtest`.
Found while testing a VCL that used `delay 300`.
=> Document default timeout for varnishtest

bin/varnishtest/tests/a00015.vtc, bin/varnishtest/tests/a02002.vtc, bin/varnishtest/tests/a02020.vtc, bin/varnishtest/tests/a02024.vtc, bin/varnishtest/tests/b00020.vtc, bin/varnishtest/tests/c00046.vtc, bin/varnishtest/tests/r00387.vtc, bin/varnishtest/tests/r00942.vtc, bin/varnishtest/tests/r01036.vtc, bin/varnishtest/tests/r01037.vtc, bin/varnishtest/tests/r01086.vtc, bin/varnishtest/tests/r01391.vtc, bin/varnishtest/tests/r01562.vtc, bin/varnishtest/tests/r01608.vtc, bin/varnishtest/tests/r01624.vtc, bin/varnishtest/tests/r01729.vtc, bin/varnishtest/tests/r01810.vtc, bin/varnishtest/tests/r02035.vtc, bin/varnishtest/vtc.c, bin/varnishtest/vtc.h, bin/varnishtest/vtc_http.c, bin/varnishtest/vtc_http2.c, include/vfil.h, lib/libvarnish/vfil.c
Following my campaign for empowering out-of-tree uses of `varnishtest`, an escape hatch to delegate body (XML, JSON, etc) checks to external programs.
This is also slightly breaking the VTC syntax as part of a general cleanup, `non-fatal` was renamed to `non_fatal`.
It includes opinionated changes to `libvarnish.a`, hopefully not controversial.
=> A `write_body` VTC command

doc/sphinx/users-guide/run_security.rst
As a reader of the docs
I mentally stumbled over a duplicated word
In order to... no wait, wrong format.
In hope of improving the codebase and the world as a whole, I hereby offer this change free of charge and with the usual "AS IS"-disclaimer to improve the flow of reading the documentation.
=> Remove duplicated word to improve reading pleasure

bin/varnishd/cache/cache_ban_lurker.c, bin/varnishtest/tests/c00049.vtc, include/tbl/params.h, include/tbl/vsc_f_main.h
Expurge long tail content from the cache to keep the number of bans
below this value. 0 disables.
This is a safety net to avoid bad response times due to bans being
tested at lookup time. Setting a cutoff trades response time for cache
efficiency. The recommended value is proportional to
rate(bans_lurker_tests_tested) / n_objects while the ban lurker is
working, which is the number of bans the system can sustain. The
additional latency due to request ban testing is in the order of
ban_cutoff / rate(bans_lurker_tests_tested). For example, for
rate(bans_lurker_tests_tested) = 2M/s and a tolerable latency of
100ms, a good value for ban_cutoff may be 200K.
=> Parameter ban_cutoff to limit the number of active (incomplete) bans

bin/varnishd/cache/cache_req_fsm.c, bin/varnishtest/tests/s00006.vtc
By rounding Age down, we make sure Age < max-age while the object
is fresh. Otherwise, we can prematurely get Age == max-age and Varnish
will calculate that as a 0s TTL and create a pass scenario.
More info can be found in this dev list email:
https://www.varnish-cache.org/lists/pipermail/varnish-dev/2016-December/009079.html
=> Make sure Age is always less than max-age

bin/varnishd/mgt/mgt_vcl.c, bin/varnishtest/tests/v00044.vtc
Fix a problem that could lead to asserts like:
```
Error: Child (16091) not responding to CLI, killed it.
400 33      
CLI communication error (hdr eof)
Error: Child (16091) died signal=6
Error: Child (16091) Last panic at: Wed, 22 Mar 2017 12:35:13 GMT
"Assert error in ccf_config_use(), cache/cache_vcl.c line 851:
Condition(vcl->temp == VCL_TEMP_WARM) not true.
thread = (cache-main)
version = varnish-plus-4.1.5r2-beta1 revision 4653e4f
ident = Linux,3.16.0-4-amd64,x86_64,-jnone,-smalloc,-smalloc,-hcritbit,epoll
now = 301627.711396 (mono), 1490186113.598806 (real)
Backtrace:
0x460aa0: pan_backtrace+0x20
0x460861: pan_ic+0x3c1
0x4609b0: ccf_panic
0x47c1e0: ccf_config_use+0x1c0
0x7f0f2f39e0c4: libvarnish.so(+0xb0c4) [0x7f0f2f39e0c4]
0x7f0f2f39dcfb: libvarnish.so(+0xacfb) [0x7f0f2f39dcfb] …
```
=> Master cooling problem

bin/varnishd/mgt/mgt_vcl.c, bin/varnishtest/tests/r02270.vtc
Newly loaded VCLs didn't get their go cold timer set even when they
were set to auto, causing them to never go cold automatically.
Fixes: #2270
=> Set the go-cold timer on newly loaded warm auto VCLs

lib/libvarnishapi/libvarnishapi.map
fixes https://github.com/varnishcache/varnish-cache/issues/2313
=> cannot link to varnishapi, symbols missing

bin/varnishd/cache/cache_req_fsm.c, bin/varnishtest/tests/b00001.vtc
Otherwise the backend might see multiple Connection entries.
Fixes #2337.
=> If pipe'ing, unset any existing Connection headers

bin/varnishd/cache/cache_vrt.c, bin/varnishtest/tests/r02339.vtc, doc/changes.rst, include/vrt.h, lib/libvmod_debug/vmod.vcc, lib/libvmod_debug/vmod_debug.c
This logs an error and fails the transaction when an illegal purge is performed (that is, outside `vcl_{hit,miss}`). Currently such cases are silently ignored, potentially leaving an end-user thinking that the plan is going according to plan.
How `VRT_purge` should actually behave (eg. ignore or fail) has yet to be discussed. I also need to understand the side effects of calling it with a non-zero TTL, this is why coverage is only for the `return (purge)` equivalent so far. Knowledgeable people in this area are welcome to enlighten me and save me some research/testing :)
This function is for VMODs, and what I'd like to do instead of simply changing `VRT_purge` is to write a very simple VMOD with three functions:
```
$Module purge 3 Varnish Purge Module
$Function INT hard()
Equivalent to …
```
=> Universal failure for VRT_purge

bin/varnishd/mgt/mgt_main.c, bin/varnishtest/tests/r02342.vtc, doc/changes.rst, doc/sphinx/reference/varnishd.rst
Tested manually, I will provide test coverage if this is acknowledged as a bug. For a description of the problem, see this comment:
https://github.com/varnishcache/pkg-varnish-cache/pull/70#issuecomment-307152655
I believe all versions of Varnish with a `vcl_dir` or `vcl_path` are affected.
=> Make varnishd -f honor the vcl_path

bin/varnishd/cache/cache_backend_tcp.c, bin/varnishd/cache/cache_main.c, bin/varnishd/cache/cache_priv.h
Probes currently running on a worker thread at the time they are
deleted will delay the release of the refcount they hold on the TCP
pool. Since this call will not be from the CLI thread we need locking
to protect these datastructures.
=> Add extra locking to protect the pools list and refcounts

Makefile.am
Noticed when switching to Github for fetching source on FreeBSD and using autotools it never correctly sources varnish.m4 so configure fails with obtuse errors about missing functions which are defined in varnish.m4.
=> Fix sourcing of varnish.m4 when building on FreeBSD

bin/varnishtest/tests/c00084.vtc, bin/varnishtest/tests/d00006.vtc, bin/varnishtest/tests/v00020.vtc, lib/libvcc/generate.py, lib/libvcc/vcc_acl.c, lib/libvcc/vcc_action.c, lib/libvcc/vcc_backend.c, lib/libvcc/vcc_compile.c, lib/libvcc/vcc_compile.h, lib/libvcc/vcc_expr.c, lib/libvcc/vcc_parse.c, lib/libvcc/vcc_symb.c, lib/libvcc/vcc_token.c, lib/libvcc/vcc_types.c, lib/libvcc/vcc_var.c, lib/libvcc/vcc_vmod.c, lib/libvcc/vcc_xref.c
This is a partial implementation of what was reported here: https://github.com/varnishcache/varnish-cache/issues/2325#issuecomment-301457374
The changes to the VCL syntax are summed up in this test case:
https://github.com/Dridi/varnish-cache/blob/vsym/bin/varnishtest/tests/c00084.vtc
Basically, all kinds of VCL symbols can contain dashes (`-`) and VCL labels moved to a name space. This isn't done yet for VMODs, it is not possible to declare a function with this character yet. The other missing bit is symbol uniqueness for everything that is not in a name space.
I'm not continuing this effort yet, I will take advantage of the probable delay until it's reviewed and hopefully merged to work on some other assignment. However I will of course reply to comments as soon as I see them.
=> First series of "vcl 6.0;" changes

bin/varnishd/cache/cache_req_fsm.c, bin/varnishtest/tests/r02367.vtc
This lets the request's vfp stack survive a VCL label change.
Fixes: #2367
=> Move req->ws_req snapshotting until after VFP_Setup

bin/varnishd/cache/cache_hash.c, bin/varnishd/cache/cache_priv.h, bin/varnishd/cache/cache_req_fsm.c, bin/varnishtest/tests/c00011.vtc, bin/varnishtest/tests/c00081.vtc, bin/varnishtest/tests/r01858.vtc, include/tbl/vsl_tags.h
For HitMiss and HitPass, only show the remaining TTL. Seeing these
values should help debugging of timing-sensitive transactions. The
grace and keep periods are absolute, but the TTL is the remaining
time relative to the current request. Same as obj.{ttl,grace,keep}
variables in VCL.
I spent way too much time correlating Timestamp records last
Friday, I'm convinced this would have helped greatly.
=> Add the TTL, grace and keep to Hit log records

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_pool.h, bin/varnishd/cache/cache_wrk.c, bin/varnishd/http2/cache_http2_proto.c, bin/varnishd/main.vsc, bin/varnishtest/tests/t02011.vtc
The initial plan was a one-liner to get rid of an `XXXAZ` assert (2nd patch) but testing this case proved to be hard because of a bug in the thread pools (fixed in 1st patch) and while I was playing a bit with h2 resets I realized that the `sess_drop` counters includes streams so I introduced a new `req_drop` counter (3rd patch).
I expect the 3rd patch to be potentially controversial, but I tried to keep the changes to a minimum.
As a side note, since we are breaking libvarnishapi, it may be a good occasion to sort the counters. For example `sess_drop` and `sess_dropped` could be next to each other.
=> Refuse h2 streams that can't be scheduled

bin/varnishd/cache/cache_vcl.c
The struct vcl and the temperature rwlock were not free'd on
discarding labels.
=> Fix memory leak when discarding labels

bin/varnishd/cache/cache_vcl.c
The locking around the use of vcl_active does not include the checking
of its magic value or the temperature asserts, leading to a race when
changing vcl_active.
Fixes: #2390
=> Straighten locking wrt vcl_active

bin/varnishd/http2/cache_http2_proto.c, bin/varnishtest/tests/r02305.vtc
This moves the body status decision to h2_end_headers, to make sure that
it is only done once per request.
We also move the Cookie header concatenation to h2_end_headers, to avoid
stepping on any changes that may have taken place in VCL.
Fixes: #2305
=> Don't panic if we reembark with a request body

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_esi_deliver.c, bin/varnishd/cache/cache_panic.c, bin/varnishd/cache/cache_req.c, bin/varnishd/cache/cache_session.c, bin/varnishd/cache/cache_vrt_priv.c
NB: This is an alternative solution to PR #2457 
This PR kills `sp->privs` and moves it over to `struct req`.
Keeping the privs list in struct sess would necessitate extra locking for h/2 where we have multiple reqs in flight concurrently.
Previously we used the `id` argument to tell apart pointers for different requests on the same session, this is still required for the very specific case where a VMOD would use both PRIV_TOP and PRIV_TASK.
Fixes: #2268
=> Move the req-specific PRIV pointers to struct req

bin/varnishd/http2/cache_http2_session.c
The extra locking prevents the race where a request thread is setting r2->cond = NULL and the session thread is testing r2->cond != NULL.
Fixes: #2434
=> Hold the sess mutex when evaluating r2->cond

bin/varnishd/mgt/mgt_main.c, doc/sphinx/reference/varnish-cli.rst, doc/sphinx/reference/varnishd.rst, doc/sphinx/users-guide/run_cli.rst, lib/libvarnishapi/vut.c
This helps write scripts like this:
optstring=$(varnishd -x optstring)
while getopts $optstring opt
do
case $opt in
n)
;;
*)
;;
esac
done
varnishd "$@"
Otherwise if optstring is not kept in sync, getopts will stop processing
options if it encounters one that is not specified.
=> Expose the varnishd optstring via -x

bin/varnishhist/Makefile.am, bin/varnishstat/Makefile.am, bin/varnishtop/Makefile.am, configure.ac
I hoped to get rid of m4/ax_with_curses.m4, but it needs to stays for platforms not shipping .pc files.
For for those that do however, it solves the issue of split libtinfo.
=> Use pkg-config for curses, if possible

bin/varnishd/cache/cache_backend.c, bin/varnishd/cache/cache_tcp_pool.c, bin/varnishd/cache/cache_tcp_pool.h, bin/varnishtest/tests/r02135.vtc
This PR addresses #2135 
We permit a single retry and force a fresh backend connection the second time around.
First commit adds a `force_fresh` parameter to `VTP_Get`. Second commit addresses the retry logic.
Failure will land us in `vcl_backend_error`, where the VCL user can choose to do further attempts via `return (retry);`.
=> Backend "extrachance" retry fixes

bin/varnishd/cache/cache_backend.c, bin/varnishd/cache/cache_tcp_pool.c, bin/varnishd/cache/cache_tcp_pool.h, bin/varnishtest/tests/r01772.vtc
This PR fixes the case where `first_byte_timeout` is not respected for recycled backend connections. 
- First commit teaches `VPT_Close` to also handle connections in state `VTP_STATE_STOLEN`. 
- Second commit removes a `VTP_Wait` that was only used for piped connections that are about to be closed. This is no longer necessary, since `VTP_Close` can now deal with also STOLEN connections.
- Third commit adds a timeout in `VTP_Wait` and bails out to let `vbe_dir_finish` do the necessary `VTP_Close`. Failure to respond within `first_byte_timeout` lands you in `vcl_backend_error`.
Fixes: #1772 
Supersedes: #2347
=> First byte timeout fixes

bin/varnishd/http2/cache_http2_session.c, bin/varnishtest/tests/t02005.vtc, include/tbl/h2_settings.h, include/tbl/params.h
This adds varnish parameters for all H2 settings except for `SETTINGS_ENABLE_PUSH` (that setting does not make sense from a server POV).
The next step here is to actually start enforcing the configured settings (max concurrent streams, max frame size, etc.). Currently the only one that is actually used is `SETTINGS_INITIAL_WINDOW_SIZE`.
=> Add parameters for various H/2 settings

bin/varnishd/cache/cache_fetch.c, bin/varnishd/cache/cache_vrt_var.c, bin/varnishtest/tests/v00052.vtc, lib/libvcc/generate.py
In addition, instead of always initializing a transaction's storage
backend using the round-robin selection, pick Transient when we know
in advance that beresp will be uncacheable.
Closes #2533
=> Introduce obj.storage for VCL

bin/varnishd/http2/cache_http2_proto.c, bin/varnishtest/tests/t02012.vtc
With this patch we fail new streams with a `REFUSED_STREAM` if h2_max_concurrent_streams is exceeded. New streams may be opened again after the count drops below the limit.
I'm using the value of `h2->refcnt` for the counting. If at some point we decide other bits will need to hold `h2_sess` refs, we will need to revisit this.
For the test case we need to keep N streams in flight while also making sure they are started in order, so I ended up using quite a few barriers to stabilize that.
=> Enforce h2_max_concurrent_streams

bin/varnishd/VSC_main.vsc, bin/varnishd/storage/storage_lru.c, bin/varnishtest/tests/r01764.vtc
I got a strange error the other day.
Status code is 200, but body was incomplete.
This error occurred because nuke_limit was reached.
I think this error is hard to notice.
I would like to add a new counter to make notice it.
I think it can see that need to increase nuke_limit by this counter.
related ml thread https://varnish-cache.org/lists/pipermail/varnish-misc/2018-February/026340.html
=> Add n_lru_limited counter

bin/varnishd/mgt/mgt_param_bits.c
They add up to a considerable chunk of the VSL traffic, especially when cookies are involved, while providing little value when troubleshooting. In an effort to reduce VSL cycles on heavy workloads I found these to be good candidates for several reasons:
- `obj.*` fields are immutable in VCL
- after a hit, we initially get the same `Resp*` records in `vcl_deliver`
- before `vcl_backend_response` returns, we can infer them from `Beresp*`
The main difference would be `ObjHeader:X-Varnish`, but it would be the same as `BerespHeader:X-Varnish`, and be part of the `RespHeader` counterpart in the case of a hit. That, and cache-related headers adjusted to the current time.
One case where they wouldn't appear is for example on a hit followed by a restart. I have yet to find a use case where I'd …
=> Add Obj* records to the default vsl_mask

bin/varnishd/cache/cache_fetch.c
If the stevedore failed the object creation, we would leak the temporary
VSB holding the computed vary string. This patch frees it.
Problem exists in 4.1 and later.
=> Fix memory leak of vary string on stevedore alloc fail

bin/varnishtest/gensequences
I never thought that I'd have to fix a string concatenation problem in
a BusyBox awk program to generate VT100 code in a container, but here we
are:
echo | awk 'END {print "foo" "" ++a, "foo" ++a}'
should output "foo0 foo1", and for all the ?awk I tested, it does,
except for BusyBox awk who thought funny to output "0 foo1", breaking the
teken_state.h file.
=> Fix gensequences for BusyBox awk

bin/varnishtest/tests/a00009.vtc
alpine's getopt returns "progname: unrecognized option: A"
=> Make a00009.vtc pass on alpine

bin/varnishd/cache/cache_cli.c, bin/varnishd/mgt/mgt_cli.c, bin/varnishtest/tests/b00008.vtc, include/vcli_serve.h, lib/libvarnish/vcli_serve.c
This adds -j support to the command
varnishadm ping -j
Tested on RFC4627/RFC7159/ECMA404 standards (all valid JSON)
=> Add JSON ping output

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_ban.c, bin/varnishd/cache/cache_ban.h, bin/varnishd/cache/cache_ban_build.c, bin/varnishd/cache/cache_ban_lurker.c, bin/varnishd/cache/cache_vrt.c, include/vrt.h
Fixes #2716 for most cases.
Open questions:
* make `wstat` lock visible to ban code and hold it during cli ban?
* do the same for `vcl_init` / `vcl_fini`  or will we add a worker?
From the commit message:
For ban statistics, we updated VSC_C_main directly, so if we raced
Pool_Sumstat(), that could undo our changes.
This patch fixes statistics by using the per-worker statistics
cache except for the following remaining corner cases:
* bans_persisted_* counters receive absolut updates, which does
not seem to fit the incremental updates via the per-worker stats.
I've kept these cases untouched and marked with comments. Worst
that should happen here are temporary inconsistencies until the
next absolute update.
* For BAN_Reload(), my understanding is that it should only
happen during init, so …
=> Accurate ban statistics except for a few remaining corner cases

bin/varnishd/waiter/cache_waiter_epoll.c
reviving this: https://git.alpinelinux.org/cgit/aports/tree/main/varnish/musl-fix-stack-overflow.patch
Alpine uses musl libc that has a smaller stack, so Varnish compiles but can't run with that big a number of events (8192). phk offered that maybe the NEEV number could need to be revised and we should have a look at what others do.
- nginx has it configurable, set to 512 by default, and I found no recommendation about changing those.
- haproxy also has it configurable with a 200 default, and says this:
```
tune.maxpollevents <number>
Sets the maximum amount of events that can be processed at once in a call to
the polling system. The default value is adapted to the operating system. It
has been noticed that reducing it below 200 tends to slightly decrease
latency at the expense of network …
```
=> Accommodate musl libc that has a smaller stack

lib/libvarnishapi/Makefile.am
Fixes: libvarnishapi needs soname bump #2710
Should be backported to branches: 5.0, 5.1, 5.2, 6.0
=> Increasing libvarnishapi.so version from 1.0.6 to 2.0.0

bin/varnishtest/tests/m00000.vtc, lib/libvcc/vcc_compile.c, lib/libvcc/vcc_compile.h, lib/libvcc/vcc_expr.c, lib/libvcc/vcc_xref.c
... and fail the VCL unless successful.
Providing the PRIVs to vmods is a core function, so error handling should happen outside vmods.
Besides being safe, this initialization can be more efficient than previous code for PRIVs used frequently within the same subroutine.
An alternative approach would be to initialize all privs once per task / top request, but unless all privs are actually used in a VCL, this approach could impose significant overhead, both in terms of time
and memory. By initializing privs once per sub, we impose overhead for privs which are referenced but not actually used in a subroutine, but not for all of the vcl.
Fixes #2708
=> initialize PRIV_TASK and PRIV_TOP vmod arguments once per subroutine

bin/varnishtest/tests/b00064.vtc
This test is unstable on some systems when running with a very high `-j` parameter, and I hope this will fix it.
Fixes: #2753
=> Stabilize b000064.vtc for real

lib/libvcc/vmodtool.py
Without this patch, it did
TypeError: Unicode-objects must be encoded before hashing
Fixes: #2436
=> Fix vmodtool with python3

bin/varnishd/cache/cache_req_fsm.c, bin/varnishtest/tests/r01821.vtc
issuing PR with respect to the pre-release freez-ish period
The previous code was correct already, but we can make it clearer that HFP implies OC_F_PASS
Also test explicitly that both HFM and HFP have their objects slimmed.
Closes #2768
=> Clarify and test object slimming for hfp+hfm

bin/varnishd/cache/cache_wrk.c
As long as we are not queuing any threads, there is no queue to
move. We record the queue marker the first time we notice queuing and
only then see if it doesn't move.
Fixes #2794
=> keep the dog in the kennel unless there's a queue

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_vrt_priv.c, bin/varnishtest/tests/v00041.vtc
O(n) does not scale for a high number of dynamic privs, so trade some
workspace for O(lg n)
=> manage dynamic privs as a red/black tree

bin/varnishd/cache/cache_vrt.c, bin/varnishtest/tests/r01504.vtc, lib/libvmod_vtc/vmod.vcc, lib/libvmod_vtc/vmod_vtc.c
A vmod may return a null IP. This relaxes the check in `VRT_acl_match` to
fail the transaction instead of crashing.
Refs #2842
=> Tolerate null IP addresses for ACL matches

bin/varnishd/cache/cache_hash.c, bin/varnishd/hash/hash_classic.c, bin/varnishd/hash/hash_critbit.c, bin/varnishd/hash/hash_simple_list.c, bin/varnishd/hash/hash_slinger.h
This patch set reduces the number of times the objhead mutex needs to be acquired for many types of passes through HSH_Lookup(), including the simple cache hit. It does this by changing the functions to deref objhead to take an already locked objhead as input, and then unlocking it as part of the operation. This saves the need to take the lock again during deref.
This change will likely give a measurable performance increase for caches seeing a large number of hits to the same object.
=> Reduce locking in HSH_Lookup

bin/varnishd/cache/cache_vcl.c
So I noticed that the following VCL:
```vcl
sub vcl_init {
std.log("NOW: " + now);
}
```
Produces: `NOW: Thu, 01 Jan 1970 00:00:00 GMT`
This is due to `ctx->now` not being initialized. This PR initializes it.
Now you get: `NOW: Fri, 07 Dec 2018 01:57:06 GMT`
I didn't bother with a VTC, seems pretty straight forward.
=> Allow now to be used in vcl_init

bin/varnishd/cache/cache_esi_deliver.c, bin/varnishtest/tests/e00003.vtc
Ensure ESI children are set up from preq->http0.
This broke in 2c59afe22ba108c7f2ab5ff75b2e30baf4ef9ec7
=> Initialize ESIs from the correct header set

bin/varnishd/cache/cache_backend.c, bin/varnishd/cache/cache_backend_probe.c, bin/varnishd/cache/cache_director.c, include/vrt.h
Yes, this is fugly, yet formatting of the backend.list output
is spread all over the place (including vmods via the vdi_list_f
callback), so until we decide it is worth spending time on separating
formatting from content, I see no other option than making the
field widths known to all vrt.
=> centralize definition of backend.list fields width

bin/varnishd/VSC_lck.vsc, bin/varnishd/cache/cache_lck.c, include/tbl/debug_bits.h
Follow-Up to #2635: separate stats for the lock and trylock case
I cannot quite follow phk's obscurity argument as this will only trigger additional questions. So instead, make clear in the name and documentation that the counters are only significant if the `lck` debug bit is set.
=> add debug bit to count contended locks

bin/varnishd/cache/cache_vrt_vcl.c, bin/varnishtest/tests/b00016.vtc, doc/changes.rst, include/vrt.h, lib/libvmod_directors/Makefile.am, lib/libvmod_directors/misc.c, lib/libvmod_directors/vmod.vcc
This allows for relevant simplification of vcl with varying backend / director names, as when identical VCL is deployed to several nodes.
Toy example:
```
vcl_init {
new myself = directors.round-robin();
myself.add_backend(directors.lookup(server.identity));
}
```
=> add vrt & vmod support to look up a director by name

bin/varnishd/cache/cache_backend_probe.c, bin/varnishd/cache/cache_director.c, include/vrt.h, lib/libvmod_directors/round_robin.c, lib/libvmod_directors/vdir.c, lib/libvmod_directors/vdir.h
... by example of the round-robin director. Should this suggestion get accepted, the next step would be to adopt the code for the other bundled directors.
This adds:
* basic stats on the number of healthy backends for directors as
* `x/y healthy` if only _x_ out of _y_ backends are healthy.
* `healthy` for all healthy  as before
* `sick` for all sick as before
* Details on the backends configured in the director for `-p`
Example output for this vcl:
```
vcl 4.1;
import directors;
import std;
probe p {.url = "/foo"; }
backend a1 {.host = "127.0.0.1";}
backend a2 {.host = "127.0.0.1";}
backend a3 {.host = "127.0.0.1";}
backend a4 {.host = "127.0.0.1"; .port = "8080"; .probe = p;}
sub vcl_init {
new rr1 = directors.round_robin();
rr1.add_backend(a1);
rr1.add_backend(a2);
rr1.add_backend(a3); …
```
=> bring "more nuance" (quote phk) to backend.list output for directors

bin/varnishd/cache/cache_backend.c, bin/varnishd/cache/cache_backend.h, bin/varnishd/cache/cache_backend_probe.c, bin/varnishd/cache/cache_director.c, bin/varnishd/cache/cache_director.h, bin/varnishd/cache/cache_vrt_vcl.c, include/vrt.h, lib/libvmod_directors/vdir.c
This implements the remaining bits from #2896, please see individual commit messages
* To fix the admin health "probe" column, we basically got two options: Either we need to include this column in the list callback, for which we would need to give up the admin health isolation, or we need to give the generic director code a way to tell if a backend has a probe. At this point I think that the most straightforward way is the latter by using the presence of a _healthy_ callback to indicate if there is a probe.
I had also tried adding a flag to the director to indicate presence of a probe, but that lead to more duplication, IMHO.
* To indicate via the healthy callback the presence of a probe, we restructure VBE and move the extra `sick` bitfield at the VDIR layer to VBE. This also cleans the …
=> remaining backend.list cleanup & retire (struct director).sick

bin/varnishd/VSC_main.vsc, bin/varnishd/cache/cache_req_fsm.c, bin/varnishd/http1/cache_http1.h, bin/varnishd/http1/cache_http1_pipe.c, bin/varnishtest/tests/v00059.vtc, include/tbl/params.h
This is a first of hopefully three patch series in the pipe vicinity.
This is pretty straightforward, count and limit ongoing pipe transactions only if we `return (pipe)` from `vcl_pipe`.
=> Limit the number of concurrent pipe transactions

lib/libvcc/vcc_compile.c, lib/libvcc/vcc_compile.h
Historically, all initializers called from VGC_Load() would handle
failures individually (return (1) from VGC_Load) or not fail at
all. Now that we got VRT_fail(), it makes sense to generalize.
The upcoming use case is to properly handle failures from
VRT_new_backend_clustered().
=> make VRT_fail() work with any initializier

bin/varnishd/cache/cache_fetch.c, bin/varnishtest/tests/r01395.vtc, bin/varnishtest/tests/r02946.vtc, doc/sphinx/users-guide/vcl-built-in-subs.rst
includes #2950 as a prerequisite
I have now made up my mind about #2946 and would fix/clarify as follows:
Fixes #2946 in the sense that we want to treat a cacheable backend synth like any other object and kill the stale object it replaces.
We do not replace the stale oc when
* abandoning the bereq
* leaving vcl_backend_error with return (deliver) and beresp.ttl == 0s
* there is a waitinglist on this object because in this case the default ttl would be 1s, so we might be looking at the same case as the previous
=> backend synth vs. stale oc take 2

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_session.c, bin/varnishd/cache/cache_vrt_var.c, bin/varnishd/http1/cache_http1_fsm.c, bin/varnishd/http2/cache_http2_proto.c, bin/varnishtest/tests/b00067.vtc, doc/sphinx/reference/vcl_var.rst
Purposes:
* Allow to optimize keepalive for trusted client connections (e.g. CDN, authenticated clients)
* Prepare for an optimization to time out connections on inactive VCLs earlier (see #2764)
A VTC and the other client timeouts will be added when accepted.
=> Add timeout_idle customization per session

bin/varnishd/cache/cache_fetch.c, bin/varnishd/cache/cache_hash.c, bin/varnishd/cache/cache_obj.c, bin/varnishtest/tests/c00097.vtc, bin/varnishtest/tests/c00098.vtc, bin/varnishtest/tests/c00099.vtc, include/tbl/boc_state.h
Resolve race on waitinglist rushing between OC_F_BUSY and boc->state  …
When an object is ready for delivery, HSH_Unbusy was called before calling
ObjSetState([BOS_STREAM|BOS_FINISHED]). The HSH_Unbusy() call does the
waitinglist rushing, but HSH_Lookup() wanted to look at the boc->state and
if BOS_STREAM had been reached. This could cause requests woken to find
that the stream state still hadn't been reached (ObjSetState still hadn't
executed), and go back on the waitinglist.
To fix this, this patch reverts commit 0375791, and goes back to considering
OC_F_BUSY as the gate keeper for HSH_Lookup. This eliminates the race,
because HSH_Unbusy and HSH_Lookup then uses the same mutex.
That change opens up the possiblity that req code after HSH_Lookup() sees
an object that has not yet reached …
=> Master unbusy race

bin/varnishd/cache/cache_fetch.c, bin/varnishd/cache/cache_hash.c, bin/varnishd/cache/cache_obj.c, bin/varnishd/cache/cache_req_fsm.c, bin/varnishd/cache/cache_varnishd.h, include/tbl/boc_state.h
The previous attempt at fixing this was less than ideal. By signalling the delivery threads BOS_STREAM state before HSH_Unbusy, several test cases became fragile, and would fail under high load conditions. What would happen was that the fetch initiating request was allowed to continue (seeing BOS_STREAM) even though HSH_Unbusy had not been run yet, allowing the handling of that request to finish completely, and the test case to continue running. If the test case next step e.g.. was to purge the same URL, it would fail to purge the object (still OC_F_BUSY).
This PR reverts commits 501246e and 4130055. The third patch adds a new approach to fix the initial race.
=> 2nd attempt at resolving the waitinglist rush HSH_Unbusy and boc->state race

bin/varnishd/mgt/mgt_vcl.c, bin/varnishtest/tests/c00077.vtc, bin/varnishtest/tests/r02432.vtc, bin/varnishtest/tests/r02471.vtc, bin/varnishtest/tests/v00003.vtc
Conceptually, the auto state was a variant of the warm state which
would automatically cool the vcl. Yet, cooling did not only transition
the temperature, but also the state, so 'auto' only worked one way -
except that vcl.use or moving a label (by labeling another vcl) would
also set 'auto', so a manual warm/cold setting would get lost.
Now the auto-state will remain no matter the actual temperature or
labeling, so when a vcl needs to implicitly change temperature (due to
being used or being labeled), an auto vcl will remain auto, and a
cold/warm vcl will change state, but never become 'auto' implicitly.
The vcl state/temperature test v00003.vtc, besides testing the new
auto semantics, now also checks for the right vcl.list output and has
been reduced by a duplicate check (warm event …
=> change semantics of the vcl 'auto' state and centralize vcl mgt

bin/varnishd/cache/cache_ban.c, bin/varnishd/cache/cache_ban_lurker.c
This is an improvement of #2925 (which I will close). The the difference is that this PR is even more eager to remove objects from the ban list.
The goal of this PR is to not hold off when dying objects are encountered, and it turned out that we can remove `oc`s in other cases as well.
I am not sure how much effect the last commit has, but I think there are corner cases where the speedup would be significant.
=> Ban lurker optimalization: Remove from ban list when possible

bin/varnishd/mgt/mgt_param_bits.c, bin/varnishtest/vtc_varnish.c
The name implies that this is not for production usage.
=> Add Debug to the default VSL mask

bin/varnishd/cache/cache_gzip.c
Ran into an issue where Varnish reports an incorrect Content-Length when streaming a backend response (gzip) and running that thru a gunzip VDP. Turns out that `OA_GZIPBITS` is being unsafely used. The patch simply forces Varnish to do a chunked response when streaming.
Reproducer VTC is [here](https://gist.github.com/rezan/015b181d0fa14392f14f9cf05060d6c3).
Just to explain, when we write the gunzip length of `3167` here:
https://github.com/varnishcache/varnish-cache/blob/4709fae3a703b5904a799b8aa1df2872e803219f/bin/varnishd/cache/cache_gzip.c#L402
We end up here:
https://github.com/varnishcache/varnish-cache/blob/4709fae3a703b5904a799b8aa1df2872e803219f/include/vend.h#L103-L106
And because we are writing single bytes, the delivery thread can incorrectly read `3167` as `3072` or `95`, …
=> Guard against OA_GZIPBITS streaming race

bin/varnishd/http2/cache_http2.h, bin/varnishd/http2/cache_http2_deliver.c, bin/varnishd/http2/cache_http2_proto.c, bin/varnishd/http2/cache_http2_send.c, bin/varnishtest/tests/t02016.vtc
I entered my garage to work on something two days ago and found my pet blocking the way. It wouldn't budge until after a good shaving.
There is a lot to review here and I tried to break it down to be as granular as possible. When I first wrote my patch I found bugs I thought I had caused but no, they were already there so instead of just fixing them I tried to reorder them in a more coherent way, and tried to also add h1 coverage.
The first problem is the use of `SO_{RCV,SND}BUF` to cover the h1 timeouts. It works on my machine (obviously) but I don't know how portable this is:
- does it work on all systems in general?
- how may each system round up buffer size?
- may the rounding up lead to test failures?
I decided to leave this to the review because I won't be available next week, and …
=> Start honoring [idle_]send_timeout of h2 streams

bin/varnishd/http2/cache_http2_proto.c, bin/varnishd/http2/cache_http2_send.c, bin/varnishtest/tests/t02016.vtc
Revisiting #2980 recently compelled me to fix this.
=> Ensure that we always log h2 idle_send_timeout

doc/sphinx/reference/varnishlog.rst, doc/sphinx/reference/varnishncsa.rst
Be a bit more elaborate on the expected behaviour
=> Docfix: varnishlog and varnishncsa exits from SIGHUP in the foreground

doc/sphinx/users-guide/vcl-backends.rst
This is bit confusing in the docs.
=> Typo. A director having two backends with the same IP is confusing

doc/sphinx/users-guide/vcl-built-in-subs.rst
The behavior described here is old (see cache_fetch.c), but has not been cleanly documented in the docs.
I am making this pull request (instead of committing directly) so that @carlosabalde can have a look first.
=> Document 1 second TTL on (synthetic) error objects

bin/varnishd/cache/cache.h
This moves the error code and reason fields to the end of the struct where they should have been when these fields were added to maintain VRT compatibility (putting them in the middle would require anyone who is using the struct to recompile their VMODs apparently).
=> Move backend error state reason and code struct field to end of busyobj struct

lib/libvarnish/vtcp.c
I have checked the illumos source and there are some legit conditions when `EPROTO` is signalled for misbehaving tcp peers.
panic seen in production:
```
Assert error in VTCP_blocking(), vtcp.c line 225:
Condition(VTCP_Check(j)) not true.
version = varnish-trunk revision 3457ded, vrt api = 6.1
ident = -jsolaris,-smalloc,-smalloc,-hcritbit,ports
now = 39647514.473957 (mono), 1564367221.322315 (real)
Backtrace:
4630c2: /usr/local/sbin/varnishd'pan_backtrace+0x30 [0x4630c2]
463535: /usr/local/sbin/varnishd'pan_ic+0x23a [0x463535]
4cefcb: /usr/local/sbin/varnishd'VTCP_blocking+0x5e [0x4cefcb]
48e789: /usr/local/sbin/varnishd'HTTP1_Session+0x150 [0x48e789]
48d6bd: /usr/local/sbin/varnishd'http1_req+0x12a [0x48d6bd]
482cbd: /usr/local/sbin/varnishd'Pool_Work_Thread+0x4e4 [0x482cbd]
481d4c: …
```
=> EPROTO can happen on solar-ish OSes

bin/varnishncsa/varnishncsa.c, bin/varnishncsa/varnishncsa_options.h, bin/varnishtest/tests/e00033.vtc
varnishncsa skip ESI subrequests.
https://github.com/varnishcache/varnish-cache/blob/master/bin/varnishncsa/varnishncsa.c#L894-L895
I think useful for ESI debugging, if show ESI subrequests.
=> Show ESI request in varnishncsa

bin/varnishd/cache/cache_panic.c
I was trying to understand why `backtrace(3)` doesn't work on alpine and noticed that we are supposed to free whatever `backtrace_symbols(3)`. From the man page:
> This array is malloc(3)ed by backtrace_symbols(), and must be freed by the caller. (The strings pointed to by the array of pointers need not and should not be freed)
=> free array returned by backtrace_symbols(3)

doc/sphinx/reference/directors.rst, doc/sphinx/whats-new/changes-6.2.rst, doc/sphinx/whats-new/upgrading-5.1.rst, doc/sphinx/whats-new/upgrading-5.2.rst, doc/sphinx/whats-new/upgrading-6.0.rst, doc/sphinx/whats-new/upgrading-6.1.rst, doc/sphinx/whats-new/upgrading-6.2.rst, lib/libvcc/vmodtool.py, lib/libvmod_blob/vmod.vcc, lib/libvmod_directors/vmod.vcc, lib/libvmod_std/vmod.vcc, lib/libvmod_unix/vmod.vcc
as @slimhazard pointed out when reviewing a suggestion I made to some
vmod documentation, the vmodtool generated link target names are
confusing to users: vmod_foo.func is nothing you can use as VCL, while
foo.func() is.
=> name vmod function / constructor / method RST xref like VCL

include/miniobj.h, varnish.m4
- According to #3051, this does not seem too obvious to be
properly detected on Linux systems.
- Some other OSes prefer to play in their own 'backyard',
having similar feature but named differently (e.g. NetBSD)
would need addition autotools check.
- Thus proposing implementing the macro with the volatile
pointer approach rather than memory fence's, sufficient to
prevent compiler optimisations.
=> Implementing ZERO_OBJ macro proposal.

bin/varnishtest/vtc_http.c
varnishtest clients don't connect to the first varnish defined regardless of their name. It assumes that the first varnish is called v1. This patch should clarify that.
=> Clarify varnishtest automatic connect behavior

.circleci/config.yml
Currently weeklies and other packagecloud items are handled via Varnish Software's jenkins setup which isn't available to the public. To improve transparency this PR adds a circleCI that drives the package builds and distcheck tests.
The packaging info is still held at https://github.com/varnishcache/pkg-varnish-cache, this only put things together for easy maintenance and review.
The goal is to build weeklies with it for a couple of weeks and once we are sure with the process we can migrate from Jenkins to cirecleCI.
Notes:
- `centos:7` currently can't `distcheck` because of an apparent bug with docutils
- `distcheck` on `debian:buster` has sanitizers disabled because the tool generating `vhp_hufdec.h` has some leaks, aborting compilation
- `alpine`'s distcheck fails because of …
=> Introduce circleci instructions

bin/varnishd/cache/cache_req_fsm.c, bin/varnishtest/tests/v00060.vtc, lib/libvcc/vcc_backend.c
This brings in the feature for allowing null backend declarations via the syntax discussed [here](https://github.com/varnishcache/varnish-cache/pull/3008). The syntax is as follows:
```
backend default none;
```
=> Added the syntax 'backend name none;'

bin/varnishd/cache/cache_ban_lurker.c, bin/varnishtest/tests/c00049.vtc
I was hoping this would have made it into 6.0, but didn't. So asking for it expicitly.
This is a cherry-pick of 44ea36eb050fc8bdabc4a834bedd4e77c154a2ff from master
93d805014df919f9be761c6d8ad4ed86eb90c2cb made execution of
ban_lurker_test_ban() conditional on bd != b, which effectively caused
objects hanging off bans below request bans to not get tested against
relevant bans.
Because object bans (from the obans list) are being marked completed,
the objects which were skipped would also be missed to get evaluated
against the relevant bans at lookup time unless they were evaluated in
request context. So, in effect, we would simply miss to test bans.
Fixes #3007
Maybe related to #3006
=> fix regression: ban-lurker skips objects

bin/varnishd/cache/cache_fetch.c, bin/varnishd/cache/cache_fetch_proc.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishd/cache/cache_vrt.c, bin/varnishtest/tests/r03009.vtc
A series of patches to make std.rollback() from vcl_backend_response() safe again.
Fixes #3009 and also pulls straight some more missing error checking.
Please refer to the individual commit messages for more detail.
=> Fix bereq rollback

bin/varnishd/cache/cache_fetch.c, bin/varnishd/cache/cache_hash.c, bin/varnishd/cache/cache_req_fsm.c, bin/varnishtest/tests/c00097.vtc, bin/varnishtest/tests/c00098.vtc, bin/varnishtest/tests/c00099.vtc
This makes waitinglist rushes happen also in HSH_Lookup when encountering
cache hits. This helps to get the requests on the waitinglist restarted
when doing streaming delivery. Fixes #2977. Backported from @mbgrydeland
master commits.
Based originally on: 3736849608cb8907b0c3ef93b01691ea3281f48a
=> Make waitinglist rushes propagate on streaming delivery

bin/varnishd/cache/cache_vrt.c, bin/varnishtest/tests/d00003.vtc, include/vrt.h, lib/libvmod_directors/hash.c, lib/libvmod_directors/shard_cfg.c, lib/libvmod_directors/shard_dir.c, lib/libvmod_directors/shard_dir.h, lib/libvmod_directors/vmod_shard.c
This deduplicates logic between the two hashing directors, and in the
case of vmod-shard adds a missing check for empty components in the
strands that should be skipped.
Not happy with the name, it was harder than I anticipated. Suggestions
welcome.
=> Add a VRT_HashStrands32 utility

bin/varnishd/mgt/mgt_param.c, bin/varnishd/mgt/mgt_param.h, bin/varnishd/mgt/mgt_param_tweak.c, bin/varnishd/mgt/mgt_pool.c, bin/varnishtest/tests/r03098.vtc, tools/coccinelle/replace.cocci
Inform users when the parameter we try to change depends on another
parameter.
This is not meant to be merged as-is, we could have a new VSB function
to trim the end of the string if it matches the one passed as the second
argument. In this case, we would trim the trailing newline only of the
CLI response didn't overflow in the first place, adding the extra
information on the same line. Alternatively we could also simply add the
explanation for the dynamic bounds on the next line.
Feedback welcome.
Fixes #3098
=> RFC: Improve thread pool parameters error messages

bin/varnishd/cache/cache_acceptor.c, bin/varnishd/cache/cache_backend_probe.c, bin/varnishtest/tests/r02872.vtc, include/tbl/vsl_tags.h, include/tbl/vsl_tags_http.h, lib/libvarnishapi/vsl_query.c
This is just a quick proof of concept. The VSL query code relies too much on asserts and maybe we should add a negative return value to `vslq_test_rec` to gracefully recover from malformed fields and print an error when we encounter one.
I ran into this use case:
```
varnishtest "Backend_health fields"
server s1 {
rxreq
txresp
} -start
varnish v1 -vcl {
backend s1 {
.host = "${s1_sock}";
.probe = {
.interval = 1m;
}
}
} -start
server s1 -wait
shell -expect "HTTP/1.1 200 OK" {
varnishlog -d -n ${v1_name} -g raw -q 'Backend_health[2] ~ healthy'
}
```
I will update this change based on review feedback.
=>  Make Backend_health fields work in VSL queries

bin/varnishd/cache/cache_wrk.c
When we breed threads without a delay, we should make an effort to let them run as soon as possible and not have the cpu occupied with the herder code.
This will increase the overhead due to additional context switching for the benefit of reducing latencies until new threads get to run.
Effect seen with this vtc by @Dridi
```
varnishtest "over-breeding"
varnish v1 -arg "-p debug=+syncvsl -p debug=+flush_head"
varnish v1 -arg "-p thread_pools=1 -p thread_pool_min=10"
varnish v1 -vcl {
backend be none;
} -start
varnish v1 -expect MAIN.threads == 10
```
figures from
```
./varnishtest -i -k -j40 -n1000 tests/as_above.vtc |\
awk '/^#/ { print $5; }'| sort | uniq -c
```
```
before	after
76	18
67	24
66	18
```
motivated by #2942
=> yield to newly bred threads

bin/varnishd/cache/cache_backend_probe.c
A case has been observed where the probe scheduling stopped. The system had some probes with very long interval (24h), and some with short intervals. It is suspected that the cause was the bug that this PR fixes, where the heap bubbled the wrong probe to the top giving a very long (24h) wait time before the next probe scheduling.
An attempt was made at creating a test case for this, but it proved very unreliable and timing sensitive so it was abandoned.
=> Fix bug in probe heap comparison function

bin/varnishstat/varnishstat_curses.c, doc/sphinx/reference/varnishstat.rst
This adds another vim-style key binding to varnishstat.
Couldn't find any good way to extend u00008.vtc to test it. The
cursor is always at column 22 and page-downing to the bottom
will break the test case when we add another counter.
=> Add Ctrl-f and Ctrl-b for pagedown/up in varnishstat.

bin/varnishd/proxy/cache_proxy_proto.c
SA_CLIENT_IP and SA_CLIENT_PORT are set twice since d7a81fe8
=> Set SA_CLIENT_{IP,PORT} only once

doc/sphinx/tutorial/peculiarities.rst, doc/sphinx/users-guide/run_security.rst
Fixed the typos in the files mentioned in the corresponding issue.
=> Fixes #3136: Typos in user guide.

bin/varnishd/cache/cache_pool.h, bin/varnishd/cache/cache_wrk.c, bin/varnishtest/tests/c00096.vtc
When getidleworker signals the pool herder to spawn a thread, it increases the dry counter, and the herder resets dry again when spawning a single thread. This will in many cases only create a single thread even though the herder was signaled dry multiple times, and may cause a situation where the cache acceptor is queued and no new thread is created. Together with long lasting tasks (ie endless pipelines), and all other tasks having higher priority, this will prevent the cache acceptor from being rescheduled.
c00096.vtc demonstrates how this can lock up.
To fix this, spawn threads if we have queued tasks and we are below the thread maximum level.
=>  Govern thread creation by queue length instead of dry signals

bin/varnishd/cache/cache_backend.c, bin/varnishd/cache/cache_vcl.c, bin/varnishd/cache/cache_vcl.h, bin/varnishd/cache/cache_vrt_vcl.c, lib/libvmod_debug/vmod_debug.c
this PR fixes #3094 
We add missing locking for operations on the director list to ensure consistency with concurrent dynamic director additions and deletions.
We remove the temperature lock which prevented director deletions during COLD events and ensure that only backends on the director list receive events.
Please note that there is no explicit vtc, the test case has been added to vmod_debug and runs with every invocation of that vmod.
Please consider the individual commit messages for additional detail on the reasoning.
=> Fix director list membership and temperature events

doc/sphinx/users-guide/storage-backends.rst
Fixes typo in storage backends guide.
=> Typo in user guide.

bin/varnishd/cache/cache_req_fsm.c, bin/varnishtest/tests/v00060.vtc, doc/sphinx/reference/vcl.rst, doc/sphinx/users-guide/vcl-backends.rst, lib/libvcc/vcc_backend.c
This brings in the feature for allowing null backend declarations via the syntax discussed [here](https://github.com/varnishcache/varnish-cache/pull/3008). The syntax is as follows:
```
backend default none;
```
This also provides documentation for the feature.
This is a back-port that is totally cherry-picked from master.
=> Backend None 6.0 Backport

bin/varnishd/mgt/mgt_vcl.c, bin/varnishtest/tests/c00077.vtc, bin/varnishtest/tests/r02432.vtc, bin/varnishtest/tests/v00003.vtc
Backport to solve duplicate label crash with the addition of a new test written by @Dridi 
f3632843589a0d5095f60cec2ed1589268f59b86
424c7b85dd7c95fa5dba804472d8a64f2adb9961
adf18f4df2aaae0701ab2ddc04ca518e71c68a55
=> back-port to solve the duplicate label crash

bin/varnishtest/tests/v00060.vtc, lib/libvcc/vcc_backend.c
Cherry-picked from 3ff7628628b0c1fb846fd86576bd1c9048517251
=> Backport backend none 60 vcc warning fix - 6.0

bin/varnishd/cache/cache_backend_probe.c
cherry-pick from f402e5ff3063026f6ac779295b318da491a934a9
=> Fix bug in probe heap comparison function - backport

.circleci/config.yml
if version is trunk, change it to the current date and add a flag file
so that packages can be suffixed with -weekly/.weekly depending on the
platform
also, drop the number splitting/assembling dance, just use the upstream version
Alpine has some very strict versioning conventions, and I didn't want to change the current scheme for debian/rhel, but we could just drop the weekly suffix for them too
=> Better weeklies, fix alpine builds

bin/varnishd/mgt/mgt_child.c, bin/varnishtest/tests/b00071.vtc, bin/varnishtest/tests/u00011.vtc, include/tbl/cli_cmds.h
I felt a bit embarrassed by this email from @carlosabalde:
https://varnish-cache.org/lists/pipermail/varnish-misc/2019-December/026767.html
=> Expose the master and worker PIDs via the CLI

bin/varnishd/cache/cache_gzip.c, bin/varnishtest/tests/g00005.vtc
Under load, client c4 from g00005.vtc may fail with a 200 response
instead of the expected 206 partial response.
There is a window during which we might still see a boc, but because
c4 sets `beresp.do_stream` to `false`, the fetch has to be over. To close
this race we can instead reference the boc as suggested in #2904 and
keep track of the boc state.
---
With enough load c4 explodes, spotted via vtest.
=> Don't ignore OA_GZIPBITS if there is a boc

bin/varnishd/http1/cache_http1.h, bin/varnishd/http1/cache_http1_deliver.c, bin/varnishd/http1/cache_http1_fetch.c, bin/varnishd/http1/cache_http1_line.c, bin/varnishtest/tests/s00010.vtc
This otherwise maintains the status quo regarding prior handling of
HTTP/1 write errors.
=> Don't report send timeouts as REM_CLOSE errors

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_fetch.c, bin/varnishd/http1/cache_http1_fetch.c, bin/varnishtest/tests/r03093.vtc
Currently we allow fetch retries with body even after we have released the
request that initiated the fetch, and the request body with it. The
attached test case demonstrates this, where s2 on the retry attempt gets
stuck waiting for 3 bytes of body data that is never sent.
Fix this by keeping track of what the initial request body status was, and
failing the retry attempt if the request was already released
(BOS_REQ_DONE).
=> Fail fetch retries when request body has been released

bin/varnishd/cache/cache_backend.c, bin/varnishd/cache/cache_transport.h, bin/varnishd/cache/cache_vrt.c, bin/varnishd/proxy/cache_proxy.h, bin/varnishd/proxy/cache_proxy_proto.c, bin/varnishtest/tests/o00003.vtc, include/vrt.h, lib/libvmod_vtc/vmod.vcc, lib/libvmod_vtc/vmod_vtc.c
the use case is to send proxy headers from backend vmod code
=> make proxy protocol header formatting available in VRT

bin/varnishd/cache/cache_vcl.c, bin/varnishtest/tests/v00010.vtc, include/vcc_interface.h, lib/libvcc/generate.py, lib/libvcc/vcc_compile.c, lib/libvcc/vcc_compile.h, lib/libvcc/vcc_xref.c
In the absence of a core dump, we do not have any information yet in the
panic output about vcl object instances, for example to find out which
object a priv belongs to when the instance address is used for
per-instance priv state.
To make this information available at the time of a panic, we add the
following:
* A struct vrt_ii (for instance info), of which a static gets
filled in by VCC to contain the pointers to the C global variable
instance pointers at VCC time
* A pointer to this struct from the VCL_conf to make it available to
the varnishd worker
* dumps of the instance info for panics
=> Add information about vcl object instances to the panic output

.travis.yml
Hello,
With this Pull Request I'd like to request to add arm64 architecture to the build matrix at TravisCI.
ARM64 is used more and more for servers too and it would be good if Varnish Cache is tested regularly.
I've ran the build and tests both on one of our arm64 machines and at [TravisCI](https://travis-ci.org/martin-g/varnish-cache/builds/639491964) and at the moment both are fine!
amd64 is the default arch at TravisCI so it is preserved!
At https://github.com/varnishcache/varnish-cache/issues?utf8=%E2%9C%93&q=is%3Aissue+arm I've seen that there were some problems on ARM based architectures in the past. Hopefully with this change the ARM specific problems will stay away in the future too.
=> Add 'arch' to the jobs, so that it tests both amd64 and arm64 on Linux

bin/varnishd/cache/cache_vcl.c, bin/varnishd/cache/cache_vcl.h, bin/varnishd/cache/cache_vpi.c, bin/varnishd/cache/cache_vrt_vcl.c
Both callers of `vcl_get()`, `VPI_vcl_select()` and `VCL_Refresh()`, potentially have to unref another vcl first.
For `VCL_Refresh()`, this happens when the active vcl changes and the previously active vcl is cached in `(struct worker).vcl`, which can be assumed to always be the case on a busy system.
For `VPI_vcl_select()`, this happens when switching vcls at `esi_level > 0`.
To summarize, this patch will primarily reduce contention on the `vcl_mtx` after a `vcl.use` CLI command on a busy system and for `return(use(vcl))` with ESI.
I added a trivial `AZ(*vcc)` patch and ran the checks before the actual patch to ensure that really the previous use of `vcl_get()` was only ever with `vcc` pointing to NULL (that is trivially clear from the caller code, but anyway...).
=> reduce vcl_mtx contention with an implicing VCL_Rel() in vcl_get()

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_shmlog.c, bin/varnishtest/tests/m00000.vtc, bin/varnishtest/tests/r03131.vtc, bin/varnishtest/tests/v00004.vtc, lib/libvmod_std/vmod_std.c
Since 8baf4a690fdb699923dd8438d0088f34fcb24365 we lost information about an overflowed workspace by calling `std.log()`, which resulted from use of the workspace for construction of a contiguous string from the argument constituents.
Since then, we have changed the interface to STRANDS, but this issue remained.
We now solve the case for real by pushing the string concatenation down to VSL: New versions of `VSL` and `VSLb` (coded by example of `VSLv()` and `VSLbt()`) take a strands argument and create a log record without additional copy overhead.
These solve #3194 for `std.log()`, make logging more efficient and, in particular, allow use of `std.log()` in low workspace conditions (because they do not require any).
Also improve test coverage for `std.log()`
Ref #3194
=> Add a strands interface to VSL and use it for std.log

bin/varnishtest/vtc_varnish.c
simple fix for fedora/gcc-10.0.1: -Werror=format-overflow, by some reason hit on s390x
https://kojipkgs.fedoraproject.org//work/tasks/2806/41452806/build.log
Fixes #3216
=> simple fix for fedora/gcc-10.0.1: -Werror=format-overflow

doc/sphinx/reference/varnishstat.rst
The Keybindings section is the only place mentioning differnt log levels
and one might assume that `-1` or `-j` behave the same as the default
ncurses interface.
The latter however does not show all counters by default as the single
action flags do, hence `varnishstat -f '*overload*'` will not show
`MAIN.sc_overload` by default, with `-1` however it does.
Fix grammar while here.
=> varnishstat.rst: Mention default log level in curses mode

doc/sphinx/users-guide/esi.rst
There's a tiny typo in the documentation users-guide/esi.rst which causes a wrong formatting in the section "ESI on invalid XML":
=> Fix formatting on 'ESI on invalid XML'

varnish.m4
I think this got copied and pasted from the VARNISH_UTILITIES macro below. If I understand correctly, the macro is called VARNISH_COUNTERS and should be used as `VARNISH_COUNTERS([foo bar])`.
=> varnish.m4: Fix documentation mistake

bin/varnishd/common/common_param.h, bin/varnishd/mgt/mgt_param.c, bin/varnishd/mgt/mgt_param.h, bin/varnishd/mgt/mgt_param_bits.c, bin/varnishd/mgt/mgt_param_tbl.c, bin/varnishd/mgt/mgt_pool.c, include/tbl/params.h
This is fresh from the oven, hopefully docfixes we can get in before the release.
My original intent was to use the dynamic bounds reasons fields to document `vsl_reclen` and `vsl_buffer` dependencies. It turned into the beginning of an overhaul of `params.h` but while individual patches may look large, they aren't. Using `git show -U0 <hash>` might help for the review of large-looking patches. They are really just mechanical patches, courtesy of vim macros.
Along the way, I also found that `thread_pool_stack`'s dynamic nature was not documented.
I'm planning further progress in this area after the 6.4 release. Reviewing this area last week I found more opportunities for improvement.
=> Document more dynamic parameters bounds

bin/varnishd/cache/cache_director.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishd/cache/cache_vcl.c, include/vrt.h, lib/libvmod_debug/vmod_debug.c
This text is a slightly edited version of the commit message from the third commit, as the other two are only preparations.
This PR adds the final bit to fix #2902: As discussed in the ticket, there should be no `VRT_CTX` `msg` vsb present for `COLD` events, yet existing code did provide it in some cases.
Comments on the most relevant changes to `cache_vcl.c` in order of appearance:
Existing code kept the CLI `VRT_CTX` around for longer than it strictly needed to just because access to the error message in `ctx->msg` was still required.
In order to be able to simplify management of the CLI `VRT_CTX`, we change `VCL_Rel_CliCtx()` to return the `ctx->msg` IFF it was requested by a _true_ argument to `VCL_Get_CliCtx()`
Regarding #2902, the main issue with existing code was that the decision …
=> fix ctx->msg for cold events

bin/varnishd/cache/cache_vrt.c, include/vrt.h
So far, we have focused on transitioning vmod arguments to STRANDS.
To take the next step and also return STRANDS (which leverages the actual benefit - not copying unmodified strand elements), vmods need to allocate a struct strands on the workspace.
This commit adds a utility function for this common task.
Implementation note: A single `WS_Alloc()` with some pointer arithmetic would suffice, but using two results in cleaner code.
=> Add VRT_AllocStrandsWS() to allocate strands on a workspace

bin/varnishd/cache/cache_fetch.c, bin/varnishd/cache/cache_req.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishd/cache/cache_vcl.c, bin/varnishd/cache/cache_wrk.c, bin/varnishd/cache/cache_ws.c, bin/varnishd/http1/cache_http1_line.c, bin/varnishd/http2/cache_http2_deliver.c, bin/varnishd/http2/cache_http2_session.c, bin/varnishd/proxy/cache_proxy_proto.c, bin/varnishtest/tests/c00071.vtc
This is an alternative approach to #3197 on how to fix #3194 as discussed during today's bugwash:
`WS_Snapshot()` now returns a magic value which gets recognized by `WS_Reset()` to ensure that the overflowed marker gets preserved or even restored. In this case, the workspace does not actually get reset.
background:
We use workspace overflows to signal to bail out for example after a failing `VRT_SetHdr()`. This is a guarantee that if some serious issue occurred during processing, we rather send an error downstream than an incomplete response or the result of incomplete processing.
We use the `WS_Snapshot() ...  WS_Reset()` pattern as some kind of second order workspace allocation where the called code itself uses `WS_Reserve()`.
With this usage pattern, `WS_Reset()` called …
=> An overflowed workspace must remain overflowed after WS_Reset()

bin/varnishd/http1/cache_http1_fetch.c, bin/varnishd/http1/cache_http1_line.c, bin/varnishtest/tests/r03189.vtc, bin/varnishtest/tests/s00011.vtc
problem
---
Previously, we only checked `v1l->deadline` (which gets initialized from the `send_timeout` session attribute or parameter) only for short writes, so for successful "dripping" http1 writes (streaming from a backend busy object with small chunks), we did not respect the timeout.
solution
---
This patch restructures `V1L_Flush()` to always check the deadline before a write by turning a `while() { ... }` into a `do { ... } while` with the same continuation criteria: `while (i != v1l->liov)` is turned into `if (i == v1l->liov) break;` and `while (i > 0 || errno == EWOULDBLOCK)` is kept to retry short writes.
This also reduces the `writev()` call sites to one.
Fixes #3189
(potentially breaking) changes
---
After (if) the patch is accepted, we should put a prominent warning into the …
=> respect `send_timeout` for "dripping" http1 writes

bin/varnishtest/tests/v00021.vtc, lib/libvcc/vcc_action.c, lib/libvcc/vcc_compile.h, lib/libvcc/vcc_expr.c, lib/libvcc/vcc_parse.c, lib/libvcc/vcc_xref.c
After the initial discussion from #3163, and looking more closely at how
variable access is handled in subroutines I noticed a discrepancy.
Setting a read only variable like `obj.ttl` in `vcl_recv` would result in
a misleading error message explaining that it is read only, instead of
simply not available.
This change defers the illegal write check, registering unconditionally
that the symbol was used in a set action. As a result we always get the
correct error message but depending on whether this is happening in a
vcl_ or custom subroutine we either get "in method" or "from method" in
the error message. A minor discrepancy probably worth getting rid of the
prior inconsistency.
This is covered by the v21 test case.
=> Defer the illegal write check a bit

bin/varnishd/cache/cache_esi_fetch.c, bin/varnishd/cache/cache_esi_parse.c, bin/varnishd/cache/cache_gzip.c, bin/varnishtest/tests/r03253.vtc
Turn assertion into VFP error
The vtc is based upon r02645.vtc and reliably reproduces the panic without the patch by sweeping through possible amounts of free workspace ranging from 4 to 400 bytes.
Fixes #3253
=> Handle workspace allocation errors in VEP_Init()

bin/varnishd/cache/cache_vrt_priv.c
this PR was already OK'd via #3129, I just wanted to keep the previous PR for future reference and not force-push a different implementation.
To be merged after the release freeze
---
in varnish-cache, access to all ESI sub-requests happens in a single thread, but vmods (VDPs) may add concurrency.
We thus protect access to PRIV_TOP with the session mutex.
Any vmods using this facility will likely need to add additional locking for the actual data structures referenced through the `PRIV_TOP` and any other access to the top request.
For alternatives previously considered, see #3139
=> support concurrent access to PRIV_TOP

bin/varnishd/cache/cache_esi_deliver.c, bin/varnishtest/tests/r03241.vtc
As with any other out-of-workspace condition during ESI processing, we do not have any better way than to deliver an incomplete response (missing ESI include).
Or do we?
Fixes #3241 (the panic, not the root cause)
=> Error handling for out-of-workspace VDP_Push during ESI processing

bin/varnishstat/varnishstat.c, bin/varnishtest/tests/u00015.vtc
fixes #3186
This changes the format in only two ways:
- counters go into their own `counters` sub-object
- new `version` field, set to 1 (since most lenient parser will say it's 0 if the field is absent)
However, it will break parsers downstream, it maybe an issue if the next release isn't a major one. I'm happy to communicate with the downstream projects I know/can reach to ease the migration.
=> varnishstat json schema change

bin/varnishd/proxy/cache_proxy_proto.c, include/vsa.h, lib/libvarnish/vsa.c
VSA_BuildFAP: Build a suckaddr from Family, Address and Port
Follow the spirit of the vsa.c top level rant and spare callers the hassle of creating sockaddrs specific to ip4/ip6 just to build a VSA, which is intended to avoid having to special-case the protocols in the first place.
Usage is intentionally simple: The interface just takes an address family, an address and a port together with length arguments for additional safely. NULL / 0 arguments are accepted and will create zero address elements.
The first commit of the PR contains the wrapper code with a basic rewrite of `vpx_proto2()` as the current use case in core code. The second commit show how `vpx_proto2()` can be further condensed because special casing is not required any more.
More use cases are to follow.
The name of the …
=> Add a convenience wrapper to VSA_Build sparing the additional sockaddr detour

doc/changes.rst
On `doc/changes.rst` the date associated with *Varnish Cache 6.4.0* was  *2019-09-16*.
Wasn't *6.4.0* released on *March 16th 2020*?
=> Wasn't 6.4.0 released on March 16th 2020?

bin/varnishd/cache/cache_deliver_proc.c, bin/varnishd/cache/cache_esi_deliver.c, bin/varnishd/cache/cache_filter.h, bin/varnishd/cache/cache_range.c, lib/libvmod_debug/vmod_debug.c
`VDP_END` marks the end of successful processing, it is issued by `VDP_DeliverObj()` and may also be sent downstream by processors ending the stream `(for return value != 0)`
`VDP_END` must at most be generated once per processor, so any VDP sending it downstream must itself not forward it a second time.
* `VDP_bytes()`
The only relevant change is the assertion that `VDP_END` must not be received by any VDP more than once. This comes with minor restructuring of the handling of the three actions
* `VDP_DeliverObj()`
Here, `VDP_END` is pushed down after succesful iteration over the objects. We could also send the last storage segment with `VDP_END`, but this would require a change in all stevedores. Unless there is a good case for it, I do not see much value in this minor optimization.
* …
=> Add VDP_END action for delivery processors

bin/varnishd/http1/cache_http1_vfp.c, bin/varnishtest/tests/r03266.vtc
Fixes: #3266
I'm a bit unsure about using ``SC_RESP_CLOSE`` as the ``doclose`` flag here. Short of adding a new one, that is the closest I could find.
=> Ensure we don't recycle a closed backend connection

doc/sphinx/reference/vmod.rst
The only official documentation about defining counters from a VMOD currently is the [Varnish 6.0 release notes](https://varnish-cache.org/docs/trunk/whats-new/changes-6.0.html#under-the-hood-mostly-for-developers). This patch fixes that by adding a counter section to the [VMOD reference guide](https://varnish-cache.org/docs/trunk/reference/vmod.html).
I'm using the diff from the [xkey patch that added counters](https://github.com/varnish/varnish-modules/commit/21d0c84d876315ce2377a1f1168a6aa794df5f8f) as a guide.
=> Document how to make counters in a VMOD

.circleci/make-deb-packages.sh
There is a problem with fakeroot-sysv on Ubuntu 20.04 aarch64:
```
Install Build-Depends packages...
+ mk-build-deps --install debian/control
+ yes
semop(1): encountered an error: Function not implemented
Error in the build process: exit status 1
```
=> Use fakeroot-tcp when creating packages for Debian/Ubuntu

bin/varnishd/cache/cache_pool.h, bin/varnishd/cache/cache_wrk.c, bin/varnishtest/tests/c00096.vtc
Commits:
bdcdaf936ca13e07b8a71584e93669a0d0fcaf41
dbd95ce2efa334c682b47c3cd47adfe735484f09
36606226f29f589a6104b3d6514693306953b0e2
The first commit was not a clean cherry-pick
=> Backport better thread creation

bin/varnishd/cache/cache_esi_fetch.c, bin/varnishd/cache/cache_fetch.c, bin/varnishd/cache/cache_gzip.c, bin/varnishtest/tests/r03169.vtc, include/tbl/obj_attr.h
Commits:
54af42d4c328089625a59eb063e75d5c72125852
5c1fea755361664d7f2f8e23e700a0e6a00f4225
d921b1f263ba7403427cc9f8c4e82ec05469b90a
Had to change the cleanup function inside of the new function to VDI_Finish
=> Ensure we don't override Content-Encoding in a 304 conditional fetch backport

doc/sphinx/Makefile.am, man/Makefile.am
This PR fixes #3309 with the symlink approach:
For out-of-tree builds (aka [VPATH builds aka parallel builds](https://www.gnu.org/software/automake/manual/html_node/VPATH-Builds.html) in automake parlor), we symlink all documentation source files to the builddir in order to find generated documentation and documentation source files within the same tree.
More background is given in #3309
=> fix out-of-tree builds

bin/varnishtest/tests/v00065.vtc, include/vre.h, lib/libvarnish/vre.c, lib/libvmod_debug/vmod.vcc, lib/libvmod_debug/vmod_debug.c
Using PCRE's \Q and \E escape sequences, accounting for the possibility
of a \E sequence in the input string.
Supersedes #3206
=> VRE and VRT functions to quote regular expressions

bin/varnishd/cache/cache_backend.c, bin/varnishtest/tests/b00060.vtc, bin/varnishtest/tests/e00008.vtc, bin/varnishtest/tests/e00019.vtc, bin/varnishtest/tests/e00020.vtc, bin/varnishtest/tests/e00022.vtc, bin/varnishtest/tests/r00894.vtc, bin/varnishtest/tests/r01092.vtc, bin/varnishtest/tests/r01355.vtc, include/tbl/vsl_tags.h
This is a followup to https://github.com/varnishcache/varnish-cache/pull/3288. As discussed:
* Deprecate `BackendReuse` in favor of `BackendClose`
* Add a connection status field to `BackendOpen` and `BackendClose` which states if the connection is new, reused, recycled, or closed.
=> Backend connection reuse logging (v2)

bin/varnishd/http1/cache_http1_line.c, bin/varnishtest/tests/r03189.vtc
This adds more coverage for send_timeout on a response.
Reference https://github.com/varnishcache/varnish-cache/pull/3201
=> Backport send_timeout

bin/varnishd/cache/cache_director.c, include/vrt.h, lib/libvcc/vcc_expr.c
recover a minor improvement from #2680:
This commit is to emit slightly different error messages to differentiate between the cases "no backend set in vcl" and "none returned from the director".
Another error logging change from #2680 was to check for administratively unhealthy, but we should better leave that check to the backend (see #3299)
=> Diffentiate "no backend" from "none resolved" in VDI_Resolve()

bin/varnishtest/tests/v00018.vtc, lib/libvcc/Makefile.am, lib/libvcc/generate.py, lib/libvcc/vcc_action.c, lib/libvcc/vcc_backend.c, lib/libvcc/vcc_compile.c, lib/libvcc/vcc_compile.h, lib/libvcc/vcc_expr.c, lib/libvcc/vcc_namespace.h, lib/libvcc/vcc_parse.c, lib/libvcc/vcc_storage.c, lib/libvcc/vcc_symb.c, lib/libvcc/vcc_types.c, lib/libvcc/vcc_vmod.c, lib/libvcc/vcc_xref.c
The second iteration (#3158) of this change has been running in production successfully for months now (with I assume a variety of VMODs and a fair amount of VCL) but @bsdphk requested a third attempt.
The `_type` top-level symbol used to avoid conflicts was not as categorically rejected as the `::` hack from the first iteration and instead we decided to try with multiple symbol tables. This is what this patch series does.
This pull request is mostly composed of the exact same commits as #3158 (which I'm keeping open as requested by @nigoroll) and the main difference is the replacement of d5875b833cfeda80567d1c3a43be0c4efafc3c2a by e5a0cdc30 (with a few conflicts to resolve afterwards).
Again, like #3158 and #3147 this third installment does not change any VCL behavior, and only touches …
=>  Generalize type methods (take 3)

configure.ac, include/vmb.h
Use <stdatomic.h> if we have it.
Let Ancient FreeBSD without `<stdatomic.h>` fall back to the `__GNUCC_` inline assy.
=> VMB: renovation (re: #3316)

bin/varnishd/mgt/mgt_child.c, bin/varnishtest/vtc_subr.c, include/vapi/vsig.h, lib/libvarnish/vsub.c
Mainly WCOREDUMP is undefine but WIFCORED has similar semantic.
=> Haiku build fix

lib/libvarnish/vsb.c
`cci` has been complaining about a leak, but only for `debian:buster`:
```
Direct leak of 16 byte(s) in 1 object(s) allocated from:
#0 0x7f871d0f4330 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
#1 0x5574f9341a25 in VSB_newbuf /workspace/lib/libvarnish/vsb.c:203
#2 0x5574f9341eb2 in VSB_new_auto /workspace/lib/libvarnish/vsb.c:261
#3 0x5574f91ed833 in MCF_ParamConf mgt/mgt_param.c:737
#4 0x5574f91f08fe in tcp_probe mgt/mgt_param_tcp.c:65
#5 0x5574f91f0c9f in tcp_keep_probes mgt/mgt_param_tcp.c:78
#6 0x5574f91f0ead in MCF_TcpParams mgt/mgt_param_tcp.c:89
#7 0x5574f91ed09f in MCF_InitParams mgt/mgt_param.c:664
#8 0x5574f91de52f in mgt_initialize mgt/mgt_main.c:289
#9 0x5574f91e05bb in main mgt/mgt_main.c:497
#10 0x7f871be2e09a in __libc_start_main …
```
=> plug VSB leak

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_fetch.c, bin/varnishd/cache/cache_req_body.c, bin/varnishd/http1/cache_http1_fetch.c, bin/varnishtest/tests/r03093.vtc
After some consideration we decided to backport this, although it changes a private API because well the API was private and undocumented so vmod writers should not have been using it.
commits:
f88b47951415fc212c8b4bb929b5a0db2c0835c0
d4b6228e1e32cda3014eeff0a5cb60cd7a0b5474
4e6e4eedcf078795d3197792d17b1294d79ff616
=> Body Free Race Backport

bin/varnishd/http2/cache_http2_deliver.c, bin/varnishtest/tests/r03384.vtc
This exposes an assert situation if you are out of workspace.
Fixes #3382
=> Remove extraneous VSB_new()

bin/varnishd/cache/cache_req_fsm.c, bin/varnishd/cache/cache_vcl_vrt.c, bin/varnishd/cache/cache_vrt_priv.c, bin/varnishtest/tests/r03329.vtc, bin/varnishtest/tests/r03385.vtc
This uses `req->ws` for `ctx->ws` when piping. Previously the `bo` workspace was used, which lead to privs being registered in the wrong context and client data being lost after the `bo` completes.
This is a 6.0 backport patch.
Fixes #3329
Fixes #3385
=> Pipe workspace fix

doc/sphinx/Makefile.am
On `alpine` mv needs a `-f` switch to overwrite a file, leading to `distcheck` failures in `cci`
=> force mv to avoid issues on alpine

bin/varnishd/VSC_main.vsc, bin/varnishd/cache/cache_fetch.c, bin/varnishtest/tests/b00066.vtc, bin/varnishtest/tests/s00007.vtc
Uncacheable and shortlived objects end up in transient memory. Add two
counters to track both type of responses separately.
=> Add counters: beresp_uncacheable, beresp_shortlived

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_acceptor.c, bin/varnishd/cache/cache_hash.c, bin/varnishd/cache/cache_http.c, bin/varnishd/cache/cache_panic.c, bin/varnishd/cache/cache_req_fsm.c, bin/varnishd/cache/cache_session.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishd/cache/cache_vary.c, bin/varnishd/cache/cache_vrt.c, bin/varnishd/cache/cache_vrt_re.c, bin/varnishd/cache/cache_wrk.c, bin/varnishd/cache/cache_ws.c, bin/varnishd/http1/cache_http1_fsm.c, bin/varnishd/http1/cache_http1_line.c, bin/varnishd/http1/cache_http1_proto.c, bin/varnishd/http2/cache_http2_hpack.c, bin/varnishd/http2/cache_http2_proto.c, bin/varnishd/http2/cache_http2_session.c, bin/varnishd/proxy/cache_proxy_proto.c, bin/varnishtest/tests/r03319.vtc, include/vrt.h, lib/libvmod_blob/vmod_blob.c, lib/libvmod_cookie/vmod_cookie.c, lib/libvmod_std/vmod_std.c, lib/libvmod_std/vmod_std_conversions.c, lib/libvmod_std/vmod_std_querysort.c
As request by @bsdphk and @nigoroll this pull request is a series of cherry-picks from #3320 containing everything except wssan itself.
Most changes are small, larger changes are mostly mechanical.
API changes from #3320:
Avoiding direct field access was in some cases trivial, for example `ws->f` could be replaced with `WS_Front(ws)` and in other instances we needed new APIs to support "exotic" use cases.
- removed `WS_Front()`, it never makes sense, except during a reservation
- added `WS_Reservation()`, similar to `WS_Front()` but returns `NULL` outside of a reservation
- added `WS_Reserved()`, needed by the HTTP/1 pipelining code
- ~changed `WS_ReserveSize()` to reserve exactly what was requested or nothing~
- changed `WS_Copy()`, it returns `const void *`
- only `std.querysort()` …
=> Breaking changes to the workspace API

doc/sphinx/users-guide/vcl-grace.rst
It has been a while since the built-in vcl_hit changed, and this
updates the user guide.
Since 6.0.1 we have had the corresponding change in TTL, grace, keep
change, and this is also mentioned.
=> Document correctly vcl_hit built-in VCL

bin/varnishd/cache/cache_fetch.c, bin/varnishtest/tests/b00073.vtc, doc/sphinx/whats-new/changes-trunk.rst
Whether the header was set by the backend or directly in VCL, it is now
possible to signal that a backend connection should not be added back to
the pool after a successful fetch with a Connection:close header.
Pooling such a connection would be counter-productive if closing the
session was requested by the backend itself, because it would then be
likely that reusing the connection would result in busting the extra
chance.
Setting the Connection:close directly in VCL can help mitigating against
a misbehaving backend.
Refs #3400
---
Split in two commits to ease back-ports.
=> vbf: Prevent pooling of a Connection:close beresp

doc/sphinx/reference/vcl_var.rst
If *PROXY protocol* is not used, the value of `client.ip` will be the same as `remote.ip`, not `local.ip` as mentioned in the docs.
=> client.ip equals remote.ip, not local.ip

configure.ac, doc/changes.rst, doc/sphinx/whats-new/upgrading-6.5.rst, include/vrt.h
We need a new release in order to fix up the lack of bumping of VRT_MAJOR_VERSION in 6.5.0.
=> Release Varnish Cache 6.5.1

.circleci/config.yml
This changes the .circleci/config.yaml for the release branch. This accomplishes two things:
The nightly "build packages" behaviour is now for all commits to the release branch, so no need to wait for the nightly cron trigger to get a package building type of build initiated by circleci.
It uses the 6.5 branch of pkg-varnish-cache, which was forked off of the master pkg-varnish-cache for this release. This makes it so that any future changes to pkg-varnish-cache won't influence the building of the release branch. This will be very useful if there ever is a need to make another point release on the release branch.
=> Change CCI behaviour for the release branch

bin/varnishtest/tests/m00000.vtc, doc/sphinx/reference/vmod.rst, lib/libvmod_debug/vmod_debug.vcc, lib/libvmod_debug/vmod_debug_obj.c
I came across a VMOD that has a method named like the constructor to
conceptually reinitialize the object's state. That's an implementation
detail of the VMOD in question and arguably undefined behavior in
Varnish.
In order to not accidentally break this assumption, add some test
coverage and document this possibility.
=> vmod: Objects can have methods named like constructors

bin/varnishd/cache/cache_fetch.c, bin/varnishtest/tests/b00073.vtc
Once we ask the backend to close the connection after a given request
there is no benefit from putting the backend connection back in the
pool. It's actually a surefire way to force a subsequent backend fetch
to fail its first attempt and go straight to its extra chance.
Since we try to maximize connection reuse this would have to come from
VCL and a user asking for the backend to close the connection should
have a good reason to do so, for example when the backend is known to
misbehave under certain circumstances.
Closes #3400
Refs #3405
=> vbf: Prevent pooling of a Connection:close bereq

lib/libvarnish/vsb.c
They either take both a dynamic struct and buffer, or both are static.
We can also use macros from miniobj to tidy the functions and try to
ensure that memset() is not optimized away.
---
I'm wondering whether it makes sense to keep some of the macros
from sbuf and not go straight for miniobj, vas and stdlib facilities. We
already diverged a lot with sbuf, both in terms of downstream changes
and lagging behind upstream.
=> vsb: Harden destroy and fini operations

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_http.c, bin/varnishd/http2/cache_http2_deliver.c, bin/varnishtest/tests/r03416.vtc, bin/varnishtest/tests/r03417.vtc, include/tbl/http_headers.h
Some browsers are strict about this and simply drop responses containing such headers. Since this is not filtering a context switch between a client and a backend transaction (or cache hit) a new filtering flag is added to the HTTP headers table for connection-specific headers. This new flag cannot be compounded as `HTTPH_R_FETCH|HTTPH_A_INS` because the TE header is an exception and left alone, even though trailers aren't supported.
Better diff with the `--ignore-all-space` option.
We could go further and consider any client request containing one as malformed as mandated by RFC 7540.
Closes #3416
Closes #3417
=> http2: Don't send resp connection-specific headers

bin/varnishtest/tests/d00003.vtc, lib/libvmod_directors/vmod_directors.vcc
It makes it easier to substitute the hash director with say, the round robin director, when weight is not a concern.
---
Why not use the shard director you ask? Because in some cases the hash director fits better, mainly for its simplicity.
=> directors: Optional weight in hash::add_backend()

bin/varnishd/cache/cache_vrt.c, include/vct.h, include/vrt.h
Ref: https://httpwg.org/specs/rfc7230.html#header.fields
>  field-value    = \*( field-content / obs-fold )
>  field-content  = field-vchar [ 1\*( SP / HTAB ) field-vchar ]
>  field-vchar    = VCHAR / obs-text
- we do not accept the obsolete line folding (obs-fold)
- VCHAR is 0x20 to 0x7e
- obs-text is 0x80 to 0xff
So we end up with `!VCT_CTL || HTAB (LF)`
This change would be the basis for new use cases, like
- a type method `.valid_header`
- a feature flag `+validate_headers` which would call `VRT_ValidHdr()` for all `VRT_SetHdr()` calls
=> add a trivial VRT function to check if a string is a valid header value

lib/libvarnishapi/vsl_cursor.c
This cursor is the simplest of all as of now, and also the fastest way
to skim through a -r input when it's a regular file. This is essentially
a file cursor with much less memory churn.
On a 13GB log dump captured during a performance benchmark varnishlog
takes around 6m15s to print all the transactions to /dev/null but the
mmap cursor consistently reduces this time to around 1m01s.
This is particularly useful to audit logs at rest, be it error logs
after an incident or transactions captured during a benchmark-type
scenario.
=> vslc: New mmap cursor type for regular files

lib/libvarnishapi/vut.c
55995ab0f96c458b1b585afe49c3af737e363205 turned the `VSIG_*` flags into counters, and changed the top of the `VUT_Main()` accordingly.
We need to reflect the change also further down in the tight loop calling `VSLQ_Dispatch()`.
Fixes #3436
system call count for the test case from the issue with this patch applied:
```
$ ab -kn 100000 http://localhost:8888/ & timeout 10 strace -c /tmp/bin/varnishncsa >/dev/null & sleep 1 ; pkill -USR1 varnishncsa
...
Completed 60000 requests
Completed 70000 requests
strace: Process 20860 detached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
100.00    0.000007           0      3304           newfstatat
0.00    0.000000           0      1665           read
0.00    0.000000 …
```
=> fix signal handling in VUT

doc/sphinx/reference/varnish-cli.rst
If you look at @bsdphk's example of how to compose the authentication string, you clearly see there's a newline between `foo` (the secret), and `ixslvvxrgkjptxmcgnnsdxsvdmvfympg` (the challenge):
```
critter phk> cat > _
ixslvvxrgkjptxmcgnnsdxsvdmvfympg
foo
ixslvvxrgkjptxmcgnnsdxsvdmvfympg
^D
critter phk> hexdump -C _
00000000  69 78 73 6c 76 76 78 72  67 6b 6a 70 74 78 6d 63  |ixslvvxrgkjptxmc|
00000010  67 6e 6e 73 64 78 73 76  64 6d 76 66 79 6d 70 67  |gnnsdxsvdmvfympg|
00000020  0a 66 6f 6f 0a 69 78 73  6c 76 76 78 72 67 6b 6a  |.foo.ixslvvxrgkj|
00000030  70 74 78 6d 63 67 6e 6e  73 64 78 73 76 64 6d 76  |ptxmcgnnsdxsvdmv|
00000040  66 79 6d 70 67 0a                                 |fympg.|
00000046
critter phk> sha256 _
SHA256 (_) = …
```
=> Missing newline character between the secret and the challenge

doc/sphinx/reference/varnish-cli.rst
Reverts varnishcache/varnish-cache#3444 that was based on a shell
example that would mangle the secret file's last newline.
=> Revert "Missing newline character between the secret and the challenge"

bin/varnishd/cache/cache_backend.c, bin/varnishd/cache/cache_fetch.c, bin/varnishtest/tests/c00036.vtc, doc/sphinx/reference/vsl.rst
Unlike client transactions where it's usually easy to attribute latency, we lack some serious insights on the backend side. I had a hard time finding names and eventually gave up on the idea not to collide with client timestamps, but client and backend tasks already share Timestamp:Start so maybe it's fine to actually repurpose some?
=> vsl: New Timestamp records for backend tasks

bin/varnishd/cache/cache_backend_probe.c, bin/varnishd/http1/cache_http1_deliver.c, bin/varnishd/http1/cache_http1_pipe.c, bin/varnishd/http1/cache_http1_vfp.c, bin/varnishd/http2/cache_http2_session.c, bin/varnishd/proxy/cache_proxy_proto.c, include/vtcp.h, lib/libvarnish/vtcp.c
This PR adds EAGAIN/EWOULDBLOCK as an accepted errno for operations on sockets. This fixes #3415.
It also adds VTCP_Assert around other operations on sockets throughout the code. This is for consistency.
=> Consistent use of VTCP_Assert

bin/varnishd/cache/cache_vrt.c, include/vcc_interface.h, lib/libvcc/vcc_expr.c
avoiding local variables and `VPI_BundleStrands()`
DRAFT, TODO: Might need polishing, check suncc, definitely needs some benchmarking.
Fixes #3392
=> vcc: Pass literal VCL_STRANDS arguments

bin/varnishd/VSC_main.vsc, bin/varnishd/cache/cache_esi_deliver.c, bin/varnishtest/tests/e00003.vtc
This has been on my TODO for many years, finally got around to making the PR. The problem is that when you make an ESI subrequest, its not considered a `client_req`. However, it gets accounted for in all the other counters like `cache_hit`, `cache_miss`, etc. This leads to situations where you can see way more hits and misses than requests, which is confusing. Adding this counter will bring these counts back into equilibrium.
=> Count ESI subrequests

bin/varnishd/mgt/mgt_vcl.c, bin/varnishtest/tests/c00077.vtc, include/tbl/cli_cmds.h
To put it simply, let's take a simple CLI script:
vcl.discard vcl1
vcl.discard vcl2
[...]
vcl.discard vclX
We can now achieve the same with a single command:
vcl.discard vcl1 vcl2 ... vclX
But there is slighty more to it, because vcl.discard operates on both
VCLs and VCL labels, and dependencies can exist between both. So in
addition to operate on multiple VCLs it also does so in the correct
order.
=> cli: Teach vcl.discard to operate on multiple VCLs

bin/varnishd/cache/cache_backend.c
For a first byte timeout on a new connection, we emit
FetchError: first byte timeout
For a first byte timeout being reached on a recycled connection, we
should keep the error message similar.
Ref eecd409d13f145765de3aeee4984179e0ae008b5
=> clarify first byte timeout FetchError message

bin/varnishd/cache/cache_vrt_priv.c, doc/sphinx/reference/vmod.rst, include/vrt.h, lib/libvmod_cookie/vmod_cookie.c, lib/libvmod_debug/vmod_debug.c, lib/libvmod_directors/shard_cfg.c, lib/libvmod_std/vmod_std_fileread.c
This is the refactoring we agreed on to enable an alternative implementation of #3454. This PR does not yet introduce the copy callback needed to add the functionality suggested in #3454.
We replace the `.free` pointer of `struct vmod_priv` with a pointer to a methods struct with callbacks. As of this commit, it only contains the former `.free` callback renamed to `.fini`. The purpose of the refactoring is to allow addition of more callbacks later.
The new `struct vmod_priv_methods` also contains a `.type` member pointing to a string to contain an arbitrary description of the type of data any priv holds which uses these methods.
Implementation:
relevant changes are in `cache_vrt_priv.c` and `vrt.h`, other changes are to the documentation and bundled vmods.
The implementation is a simple …
=> Methods for vmod_priv

lib/libvmod_directors/round_robin.c
see https://github.com/varnishcache/varnish-cache/issues/3474#issuecomment-738012804 for discussion
When resolve requests race, we were not guaranteed to consider all backends because we updated a shared nxt variable.
Fixes #3474
=> fix round-robin race

lib/libvarnish/vsb.c
We don't need to assert the integrity of the VSB after every single
byte, it can become very expensive depending on the workload.
=> vsb: Speed VSB_cat() up using VSB_bcat()

bin/varnishd/cache/cache_vrt.c, bin/varnishtest/tests/v00009.vtc, bin/varnishtest/tests/v00011.vtc, include/vrt.h, lib/libvcc/vcc_action.c, lib/libvmod_std/vmod_std.c, lib/libvmod_std/vmod_std.vcc
The `ban()` vcl action adds bans like the `ban` CLI command, but has no facility for in-band error reporting. Errors are only reported to VSL.
We add `std.ban()` as a replacement for `ban()` with identical semantics, but error reporting added.
We add `v00009.vtc` mirroring `v00011.vtc`, but with `std.ban()` replacing `ban()`. The test number was chosen to fill a gap close to `v00011.vtc`.
Implementation:
We change `VRT_ban_string()` to return any error. Where the error is not a constant string, we need to format it on the workspace. For workspace overflows, we need to fall back to canned constant error strings to ensure that the error case never appears as success.
=> add `std.ban()` for vcl access to ban errors

bin/varnishd/cache/cache_acceptor.c, include/vsa.h, lib/libvarnish/vsa.c
Flexelint on Linux exhibits exactly the problem described by @bsdphk  in his rant at the top of `vsa.c`, quote:
> Do I need to tell you that static code analysis tools have a really hard time coping with (struct suckaddr_storage), and that they give a lot of false negatives which confuse people ?
One instance of this issue:
```
--- Module:   cache/cache_acceptor.c (C)
_
#... _assert(!!((getsockname(sp->fd, (void*)&ss, &sl)) == 0)) /*lint -restore *
#... getsockname(sp->fd, (void*)&ss, &sl)) == 0); } while (0)
AZ(getsockname(sp->fd, (void*)&ss, &sl));
cache/cache_acceptor.c  330  Error 64: Type mismatch (arg. no. 2) (union
__SOCKADDR_ARG = void *)
_
#... SA_Build(sa, &ss, sl)) != 0); } while (0)
AN(VSA_Build(sa, &ss, sl));
cache/cache_acceptor.c  332  Warning 603: Symbol 'ss' (line 318) …
```
=> Add VSA_getsockname()

bin/varnishd/cache/cache_director.c, bin/varnishd/cache/cache_req_fsm.c, bin/varnishd/cache/cache_vrt.c, bin/varnishd/cache/cache_vrt_priv.c, bin/varnishd/cache/cache_vrt_vcl.c, bin/varnishtest/tests/b00001.vtc, bin/varnishtest/tests/m00017.vtc, bin/varnishtest/tests/r03329.vtc, bin/varnishtest/tests/r03385.vtc, bin/varnishtest/tests/v00051.vtc, doc/sphinx/reference/vcl_var.rst
This is a follow-up  to #3408 because I accidentally pushed 5cbb3586649839b83438bd99f557cf30c9c78a66 while working on #3464. This also exposed #3385. (the reason for my accidental push was that, unfortunately, I looked at an old `make check` before pushing - my apologies).
At any rate, this has made me re-iterate over #3329, #3385 and #3408 :
So far my position has been [that we need to make vcl_pipe {} live either on the client, or the backend side](https://github.com/varnishcache/varnish-cache/pull/3330#issuecomment-654346165) but not both, which, while it formally is client side, is currently indirectly implied by the availability of symbols like `bereq.http` and `bereq.backend` and the fact that `ctx->ws` is the backend workspace (which is also the cause for #3385 )
While I stand by …
=> a compromise on workspace / priv handling of vcl_pipe

bin/varnishd/cache/cache_vrt_priv.c, bin/varnishtest/tests/m00000.vtc, include/vrt.h, vmod/vmod_debug.c, vmod/vmod_debug.vcc
`VRT_priv_task()` inserts a priv_task if it does not exist.
In some cases, it is more efficient to only insert a priv_task under certain conditions. These require an API function to only return a priv_task if it exists. This is `VRT_priv_task_lookup()`.
A TODO comment has been added for a sensible performance optimization, avoiding one VRBT traversal for the `VRT_priv_task()` case. I would address this after this suggestion got accepted, if so.
=> Add VRT_priv_task_lookup()

bin/varnishd/cache/cache_varnishd.h, bin/varnishd/cache/cache_wrk.c, bin/varnishd/http1/cache_http1_fsm.c, bin/varnishstat/varnishstat.c, bin/varnishstat/varnishstat_bindings.h, bin/varnishstat/varnishstat_curses.c, bin/varnishstat/varnishstat_options.h, bin/varnishtest/vtc_varnish.c, include/tbl/feature_bits.h, include/vapi/vsc.h, lib/libvarnishapi/libvarnishapi.map, lib/libvarnishapi/vsc.c
See the commit log for details:
* push stats in more relevant cases (by @mbgrydeland)
* adjust negative gauges to zero
* add a 'r' control everywhere relevant
* push stats from the HTTP/1 session loop
=> Various VSC consistency improvements

bin/varnishd/mgt/mgt_vcl.c, bin/varnishd/mgt/mgt_vcl.h, bin/varnishtest/tests/c00077.vtc, include/tbl/cli_cmds.h
This replaces the previous mapping of VCLs to discard with a mark and
sweep operation where a different head is used to track matching VCLs.
To discard VCLs in topological order, we can simply discard dependencies
recursively before discarding a given VCL.
It then becomes trivial to switch to glob patterns.
=> vcl: Add support for vcl.discard glob patterns

bin/varnishd/cache/cache_deliver_proc.c, bin/varnishd/cache/cache_esi_deliver.c, bin/varnishd/storage/storage_simple.c
Follow-up to #3125 :
That PR added `VDP_END`, but always issued another `VDP_bytes()` call with no data at the end of the object.
We now make it the responsibility of the object iterator to send `VDP_END` and opportunistically try to issue it with the last bytes in order to avoid the additional `VDP_bytes()` call with no data.
As noted by Martin in https://github.com/varnishcache/varnish-cache/pull/3125#issuecomment-600620905 the advantage is that "in H/2 there is the need to send a frame with a last bit set to mark the end of the stream" and in H/1 we could generate the end chunk right after the last bit of data.
This change does not implement these optimizations yet, but prepares the grounds.
In addition to the suggested changes, could reviewers please also let me know if you would …
=> Try to send VDP_END with the last bytes

bin/varnishncsa/varnishncsa.c, doc/sphinx/reference/varnishncsa.rst
Allow the user to log the request time in milliseconds through the new
format specifier: %{ms}T .
Patch by @asadsa92 and review by YT.
See https://httpd.apache.org/docs/current/mod/mod_log_config.html
=> varnishncsa: log request time in milliseconds

lib/libvarnishapi/vsl_dispatch.c
When a VUT is slow enough, it might very well be overrun while it is
scanning logs. For our built-in VUTs like varnishncsa or varnishlog
this can happen if writing the output can block waiting for IO ops
or when the output is piped to a slow consumer.
---
The assertion from 8a4e28f17c2ee39237a2c56fa0694f2f0b73e3f8 triggered in production.
=> vsl: Give up when it's too late to buffer records

bin/varnishd/cache/cache_fetch.c, bin/varnishd/cache/cache_req.c, bin/varnishd/cache/cache_req_fsm.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishd/cache/cache_vcl.c, bin/varnishd/cache/cache_vpi.c, bin/varnishd/cache/cache_vrt.c, bin/varnishd/cache/cache_vrt_priv.c, bin/varnishd/cache/cache_vrt_vmod.c, bin/varnishtest/tests/v00041.vtc, doc/sphinx/reference/vmod.rst, include/vcc_interface.h, include/vrt.h, lib/libvcc/vcc_expr.c, lib/libvcc/vcc_vmod.c, vmod/vmod_cookie.c, vmod/vmod_debug.c, vmod/vmod_debug_obj.c, vmod/vmod_directors_shard_cfg.c, vmod/vmod_std_fileread.c
Continuation of #3464:
we take the chance of the breaking change in the previous commit to also add a `VRT_CTX` argument to `vmod_priv_fini_f`. This allows a `vmod_priv` fini function, for example, access to the request or simpler and better logging (because the task's vsl buffer can be used where otherwise only unbuffered vsl was possible).
Implementation:
The meat of this commit really only is the change to the `vmod_priv_fini_f` typedef and `VRT_priv_fini()`.
All other changes are either to bundled vmods or the straight forward infrastructure to make available a ctx to `VRT_priv_fini()`, which, for client and backend context, is called via `VCL_TaskLeave()`.
Consequently, it made sense to also change the signature `Req_Rollback()` and `Bereq_Rollback()`.
=> add a VRT_CTX argument to the vmod_priv fini function

bin/varnishtest/tests/r03463.vtc, doc/sphinx/reference/vsl-query.rst, lib/libvarnishapi/vsl_query.c
Only if `strtoll(3)` stumbled upon a VNUM special character.
Fixes #3463
=> vsl: Tolerate float LHS with int RHS in queries

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_panic.c, bin/varnishd/cache/cache_vrt_priv.c
Very minor, utterly insignificant suggestion which I am just not sure about:
This adds a variant of `PAN_dump_struct()` which does not start a new indentation level on a new line.
For example, privs panic:
* before:
```
***  v1    debug|  privs = 0x7ff354c96200 {
***  v1    debug|    priv = 0x7ff354c98198 {
***  v1    debug|      {p (nil) l 0 m (nil) t \"\"} vmod 7ff35a7fc260
***  v1    debug|    },
***  v1    debug|  },
```
* after:
```
***  v1    debug|  privs = 0x7f0674096200 {
***  v1    debug|    priv = 0x7f0674098198 {{p (nil) l 0 m (nil) t \"\"} vmod 7f06793fd260},
***  v1    debug|  },
```
Obviously, this makes more of a difference for iterations over many objects
=> Add PAN_dump_oneline() ?

bin/varnishtest/vtc_gzip.c
Assert Greater or Equal to Zero.
Trivial suggestion to counter Coverity issues 1472401 and 1472402: Simply wrap a signed value which we require to be positive.
The Coverity issue basically complains about assigning an `ssize_t` to `vz.avail_in` which is unsigned.
If accepted, we should probably promote this to a vdef.h?
=> Add AGEZ()

bin/varnishd/cache/cache_vpi.c, include/Makefile.am, include/vcc_assert.h, include/vcc_interface.h, lib/libvcc/Makefile.am, lib/libvcc/generate.py, lib/libvcc/vcc_compile.c
We wrap `VAS_Fail()` as `VPI_Fail()` and add an `assert()` macro to the Varnish Generated C (VGC) code. This `assert()` definition is basically a copy of that in `vas.h`, but deliberately added to a source file which is only used by `generate.py` for VGC, such that this slightly different definition be only visible to VGC.
I also pondered the option to include VCL source information in `VPI_Fail()`: By using the information updated by `VPI_count()`, we could have that, but as the assert is, for now, intended only to ensure correctness of VCC and core VRT code, I decided against this complication.
With `assert()` in place for VGC, we arm the assertions from 75acb5cc7aa73fcd22b150dd1a3b899c6ec9bc44
=> assert() for VGC and arm assertions on ctx->method

bin/varnishd/cache/cache_vpi.c, bin/varnishd/cache/cache_vrt_vcl.c, bin/varnishtest/tests/m00053.vtc, bin/varnishtest/tests/m00054.vtc, bin/varnishtest/tests/v00020.vtc, bin/varnishtest/tests/v00021.vtc, doc/changes.rst, doc/sphinx/reference/vmod.rst, include/vcc_interface.h, include/vrt.h, lib/libvcc/generate.py, lib/libvcc/vcc_action.c, lib/libvcc/vcc_compile.c, lib/libvcc/vcc_compile.h, lib/libvcc/vcc_expr.c, lib/libvcc/vcc_parse.c, lib/libvcc/vcc_symb.c, lib/libvcc/vcc_xref.c, lib/libvcc/vmodtool.py, vmod/vmod_debug.c, vmod/vmod_debug.vcc
use case
-----------
This PR implements a vmod type for vcl subs with the goal of being able to use vcl subs as parameters to vmod function/method calls, which allows them to call back into VCL subs. The primary, obvious use case is a clean interface for [vmod_dispatch](https://code.uplex.de/uplex-varnish/libvmod-dispatch). Another use case I have in mind would be the option to add iterator vmod functions, for example to tokenize a string and call a sub for each token with a task variable set.
implementation
--------------------
We add to VRT and initialize for each vcl sub a `struct vcl_sub` which contains:
* a methods bitmask defining which contexts this sub may be called from
* the name as seen from vcl
* the function pointer to the `vcl_func_f`
As the latter two are trivial, I will …
=> a vmod type for vcl subs & VRT_call()

bin/varnishd/http2/cache_http2.h, bin/varnishd/http2/cache_http2_proto.c, bin/varnishd/http2/cache_http2_session.c, bin/varnishtest/vtc_http2.c, include/tbl/h2_error.h
And use that for logging purposes when a successfully opened h2 session
ends. RX_JUNK is still the default session close reason when existing
reasons aren't accurate enough.
Fixes #3393
=> h2: Add a sess_close reason to h2 connection errors

bin/varnishd/cache/cache_hash.c, bin/varnishd/cache/cache_req_fsm.c, bin/varnishtest/tests/r02372.vtc, doc/sphinx/reference/vsl.rst, include/tbl/params.h
As a recurring pitfall sometimes hard to identify, it deserves its own
notice. The accounting of variants reuses the worker's strangelove field
since it doesn't conflict where other parts of the code base use it.
=> lookup: Add a notice for high numbers of variants

bin/varnishtest/tests/m00054.vtc, lib/libvcc/vcc_action.c
that is,
```
call vmod.returning_sub();
```
in VCL.
Follow up to #3163 
If accepted, I would prefer to recommend to vmod authors to consider returning a `VCL_SUB` type and making the `call` explicitly from VCL whenever possible, as this allows for more flexibility (like storing the `VCL_SUB` again and running some more code before finally calling it some time later - or even not so) and _might_ allow us to make additional checks in VCL.
`VRT_call()` nevertheless needs to stay for the "foreach" case.
The existing `call sub;` is special in that it instantiates "sub", if it does not exist already, enabling use-before-definition semantics.
The doctrine of this change is to preserve this behaviour and to not make existing, static calls any less efficient.
To support calling both literal SUBs …
=> Enable calling a dynamic sub

bin/varnishtest/tests/m00053.vtc, lib/libvcc/vcc_action.c, lib/libvcc/vcc_compile.h, lib/libvcc/vcc_symb.c, vmod/vmod_debug.c, vmod/vmod_debug.vcc
7ec28f1ae91bd39e6e89beb7dffd4248c5054414 did not work with object methods because we need a partial symbol table lookup to identify them, otherwise the symbol kind we find is just SUB for the method's return value.
Fixes #3521
=> Fix callling a dynamic sub for object methods

bin/varnishd/cache/cache_fetch.c, bin/varnishtest/tests/r03525.vtc
The bo fields err_code and err_reason need to be reset on a retry otherwise the values are kept.
Fixes #3525
=> Clear the status and response on a retry

bin/varnishd/cache/cache_acceptor.c, bin/varnishtest/tests/t02011.vtc
When accepting new incoming connections in the acceptor thread, it would
schedule, they would be registered with the VCA priority. This priority is
reserved for the acceptor thread itself, and specifically is not included
in the TASK_QUEUE_CLIENT categorisation. This would interfere with the
thread reserve pools.
t02011.vtc had to be adjusted to account for the new priority
categorisation of the initial request.
=> Use the REQ priority for incoming connection tasks by the acceptor

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_wrk.c, bin/varnishtest/tests/c00104.vtc
The watchdog mechanism currently triggers when any queueing is happening,
regardless of the priority. Strictly speaking it is only the backend
fetches that are critical to get executed, and this prevents the thread
limits to be used as limits on the amount of work the Varnish instance
should handle.
This can be especially important for instances with H/2 enabled, as these
connections will be holding threads for extended periods of time, possibly
triggering the watchdog in benign situations.
This patch limits the watchdog to only trigger for no queue development
on the highest priority queue.
=> Limit watchdog to highest priority only

bin/varnishd/cache/cache_range.c, bin/varnishd/http2/cache_http2_deliver.c, bin/varnishtest/tests/c00034.vtc
And fix the h2_req VDP error handling as per the VDP contract.
Test case inspired by @simonvik. Since this is one of those test cases that
explicitly mix two features I wasn't sure whether I wanted to make this
an h2 test case or a range test case. Since this was ultimately a range
bug I decided to register it in a range test case.
It's not obvious what should have been authoritative here. The range VDP
was rightfully latching an error via SC_RANGE_SHORT that is defined as an
error-type session close reason, but VDP_DeliverObj() doesn't take that
into account. While SC_RANGE_SHORT isn't a session/protocol error for h2
but rather a stream error it is not obvious what VDP_DeliverObj() should
do in the absence of a negative retval and the presence of a non-null
sess_close.
Maybe another way …
=> range: Propagate the VDP error for short ranges

bin/varnishd/cache/cache_vrt.c, bin/varnishtest/tests/r03546.vtc
When an `obj.*` field is passed into the `resp.reason` in a `return(synth())` expression, under certain conditions the `oc` can be dereferenced early and lead to a use after free in `vcl_synth`. The fix is to do a workspace copy if the value is not local when entering a synthetic response. This will also cover `vcl_backend_error`.
=> resp.reason and vcl_synth can race with obj.* pointers

bin/varnishtest/tests/d00029.vtc
we only use one passed and one piped requests, so our servers should
only ever see two requests.
Motivated by a failure on fedora armv7hl, which I do not understand:
```**   c1    === txreq -url /1 -hdr "pipe: true"
**** c1    txreq|GET /1 HTTP/1.1\r
**** c1    txreq|pipe: true\r
**** c1    txreq|Host: 127.0.0.1\r
**** c1    txreq|\r
**   c1    === rxresp
**** dT    3.832
**** c1    rxhdrlen = 0
---- c1    HTTP header is incomplete
**** dT    3.833```
=> thaw pile: Polish testcase

bin/varnishd/cache/cache_vrt.c, include/vrt.h
... and document it
The size of 1 for the `p` array would not be required, it is a safety measure only.
Should we have this or rather set `.p = NULL`?
=> Add a NULL VCL_STRANDS

bin/varnishd/cache/cache_fetch.c, bin/varnishtest/tests/c00105.vtc
The assertion that the stale objcore of a conditional fetch cannot be
failed unless it was streaming is incorrect. Between the moment when
we grab the stale objcore in HSH_Lookup and the moment we try to use
it after vcl_backend_response, the backend fetch may have completed or
failed.
Instead, we need to treat an ongoing fetch and a failed fetch as
separate checks since the latter may happen with or without a boc.
=> condfetch: Handle failed stale_oc without a boc

bin/varnishd/storage/storage_simple.c
This is a TTFB optimization: I noticed that, when streaming, we would only sometimes send headers while waiting for more body data from the backend, depending on the amount of body data read ahead when reading the backend headers.
The `flush_head` debug bit would avoid the delay, but it leads to an extra flush in all cases, even when we could send some body data down the line with the headers.
This trivial patch peeks into the busy object to determine if the first `ObjWaitExtend()` is likely to block and, if so, issues a flush, which will cause the headers to be sent in addition to any initial data VDPs might have to send.
=> When streaming, send headers if no body data available yet

bin/varnishd/mgt/mgt_child.c
This patch makes varnishtest run almost 1s faster in most of my local tests.
=> Decrease sleep time when waiting for child to die.

.circleci/config.yml, .circleci/make-rpm-packages.sh
`doc/sphinx/installation/install_source.rst` Didn't have an analogous section in 6.0 (or  doc/sphinx/installation/install.rst in 6.0), so it is dropped.
=> [LTS Backport] Attempt to Fix cci

bin/varnishd/cache/cache_fetch.c, bin/varnishtest/tests/r03525.vtc
The bo fields err_code and err_reason need to be reset on a retry otherwise the values are kept.
Fixes #3525
Original ticket: https://github.com/varnishcache/varnish-cache/issues/3525
Original PR: https://github.com/varnishcache/varnish-cache/pull/3526
=> [LTS Backport] Clear the status and response on a retry

bin/varnishd/cache/cache_vrt.c, bin/varnishtest/tests/r03546.vtc
We can incorrectly reference resp.reason from other sources when
jumping into vcl_synth. This also covers passing in a reason in
vcl_backend_error.
Original PR: https://github.com/varnishcache/varnish-cache/pull/3546
=> [LTS Backport] resp.reason and vcl_synth can race with obj.* pointers

bin/varnishd/cache/cache_gzip.c
Originally PR: https://github.com/varnishcache/varnish-cache/pull/2904.
Fixes: https://github.com/varnishcache/varnish-cache/issues/3535
=> [LTS Backport] Guard against OA_GZIPBITS streaming race

lib/libvmod_directors/round_robin.c
When resolve requests race, we were not guaranteed to consider all
backends because we updated a shared nxt variable.
Fixes #3474
Original PR: https://github.com/varnishcache/varnish-cache/pull/3479
=> [LTS Backport] directors.round_robin() sometimes returns unhealthy backends

bin/varnishd/cache/cache_fetch.c, bin/varnishtest/tests/b00073.vtc, doc/sphinx/whats-new/changes-6.0.rst
Original PRs: https://github.com/varnishcache/varnish-cache/pull/3405 https://github.com/varnishcache/varnish-cache/pull/3423
First discussed: https://github.com/varnishcache/varnish-cache/pull/3400
=> [LTS Backport] Don't recycle a backend when a Connection: close header is present

bin/varnishd/cache/cache_fetch.c, bin/varnishtest/tests/c00105.vtc
The assertion that the stale objcore of a conditional fetch cannot be
failed unless it was streaming is incorrect. Between the moment when
we grab the stale objcore in HSH_Lookup and the moment we try to use
it after vcl_backend_response, the backend fetch may have completed or
failed.
Instead, we need to treat an ongoing fetch and a failed fetch as
separate checks since the latter may happen with or without a boc.
Conflicts:
bin/varnishd/cache/cache_fetch.c
Original PR: https://github.com/varnishcache/varnish-cache/pull/3558
=> [LTS Backport] Cond fetch boc race

bin/varnishd/cache/cache_req_fsm.c, bin/varnishtest/tests/r03560.vtc
A backend error can trigger Varnish to produce a valid zero length response.
https://github.com/varnishcache/varnish-cache/issues/3560
https://github.com/varnishcache/varnish-cache/pull/3561
=> [LTS Backport] Early backend error triggers zero length response

bin/varnishtest/tests/d06001.vtc, lib/libvmod_directors/shard_cfg.c
Technically not a backport, these are fixes specific to shard and 6.0.
`canon_point` - This was dropped in master before a big change which added weights. In trying to keep 6.0 stable, we left this in and had to approximate what this value is based on the new algorithm. Previously we used the last point (which sometimes doesn't exist), but upon closer inspection, we should be using the first point.
`shard.reconfigure()` - There is a bug where if you `reconfigure()` and empty shard, future calls of `reconfigure()` will fail. This does not exist anymore in master since `reconfigure()` was made optional and the shared state has been removed. The root of the problem is that we do not cleanup our state when we see there are no backends. I also moved the lock up to cover more operations safely.
=> [LTS Backport] Shard fixes

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_wrk.c, bin/varnishtest/tests/c00104.vtc
Limit watchdog to highest priority workers only.
This should be based on https://github.com/varnishcache/varnish-cache/pull/3590, `r02418.vtc` needs to be removed as this patch also removes that deadlock scenario.
https://github.com/varnishcache/varnish-cache/pull/3537
=> [LTS Backport] Watchdog priority

bin/varnishd/cache/cache_ban_lurker.c, bin/varnishtest/tests/r03006.vtc
Original body below:
background: When the ban lurker has finished working the bottom of the
ban list, conceptually we mark all bans it has evaluated as completed
and then remove the tail of the ban list which has no references any
more.
Yet, for efficiency, we first remove the tail and then mark only those
bans completed, which we did not remove. Doing so depends on knowing
where in the (obans) list of bans to be completed is the new tail of
the bans list after pruning.
5dd54f8390739c62c201e62c36eb515b1e03c2ee was intended to solve this,
but the fix was incomplete (and also unnecessarily complicated): For
example when a duplicate ban was issued, ban_lurker_test_ban() could
remove a ban from the obans list which later happens to become the new
ban tail.
We now - hopefully - solve the …
=> [LTS Backport] properly maintain the obans list when pruning the ban list tail

bin/varnishd/cache/cache_vrt.c, bin/varnishtest/tests/r03308.vtc, lib/libvarnish/vtim.c
For VCL_TIME values that would convert to a year element that can not fit
in an int, gmtime_r would fail, and VTIM_format() would use random stack
values when picking weekday and month strings.
This patch changes VTIM_format to return "" when gmtime_r reports
failures. This way the API is not changed. Callers can test for empty
string to catch the failure if needed.
VRT_TIME_string is patched to catch the VTIM_format error, and return NULL
on failure.
=> Handle unformatable VCL_TIME to string conversion failures

bin/varnishd/cache/cache_http.c, bin/varnishtest/tests/c00016.vtc, include/tbl/http_headers.h
The actual agorithm was found with `gperf` but its output is
not directly usable and include/tbl/http_headers.h change so
infrequently that this step is not automated.  (Asserts protect
against overlooking this step if new headers are added to
the table.)
=> Use "perfect hash" to find headers to be filtered out.

bin/varnishtest/Makefile.am, bin/varnishtest/cmds.h, bin/varnishtest/tests/a00021.vtc, bin/varnishtest/tests/c00106.vtc, bin/varnishtest/vtc.c, bin/varnishtest/vtc.h, bin/varnishtest/vtc_tunnel.c, doc/sphinx/Makefile.am
The tunnel acts like a client and a server and forwards bytes between
two parties. It can then pause in the middle of a session and control
how much data can go in either direction. Combined with barriers it can
be used to trigger socket timeouts, possibly in the middle of protocol
frames.
A tunnel works with two threads: one to execute its spec and one to poll
both parties and transfer data accordingly. The two threads synchronize
via basic pthread primitives and follow a very simplistic state machine:
ACCEPT -> RUNNING <-> PAUSED -> SPEC DONE -> POLL DONE -> STOPPED
Despite being simplistic, the coordination of two threads would likely
complicate the implementation of a `-repeat` action, but it is still
possible to `start` a tunnel again as shown in the c102 test case that
exercises …
=> varnishtest: New tunnel command

bin/varnishd/cache/cache_hash.c, bin/varnishd/cache/cache_req.c, bin/varnishd/cache/cache_req_fsm.c, bin/varnishtest/tests/c00107.vtc, doc/sphinx/reference/vcl_var.rst, include/tbl/req_flags.h
It works like the hash_ignore_busy flag: it is disabled by default
and survives a restart, but as the name implies will skip vary checks
for object candidates.
=> req: New hash_ignore_vary flag

bin/varnishtest/tests/v00021.vtc, lib/libvcc/vcc_expr.c
It seems that the common point between both is that we technically start
a brand new expression (expr0) in the RHS of an ongoing expression
instead of using an RHS-specialized function (like expr4 or expr_add).
In practice, we do recursively start a brand new expression, so we need
the subsequent conversion work performed by expr0. Except that expr0
starts with a boolean OR parsing which we don't want here.
Instead of adding another special case to expr0, we can instead split
the conversion work to its own function and parse the RHS of a REGEX or
an ACL match expression as expr4+expr_convert.
Fixes #3628
=> vcc: Give the REGEX treatment to ACL expressions

.circleci/config.yml
Alpine 3.14 includes a newer version of musl that uses the newer
faccessat2 syscall, which is not yet allowlisted by the seccomp filter
in older Docker versions. Docker 20.10.0+ allows this new syscall.
In this patch, we configure Circle to set up a Docker 20.10+ environment
where we can run Alpine 3.14 builds.
=> circleci: Re-enable Alpine latest

lib/libvarnish/vav.c
Commas unlike spaces are hard separators, so a trailing comma leads to a
last empty parameter.
A comma may appear after an argument's "trailing" spaces and should not
result in an additional parameter. In <foo  , bar> we should expect two
fields, not three.
Comments are only treated as such at arguments boundaries: <foo #bar>
parses one field <foo> and <foo#bar> parses one field <foo#bar>, taking
the shell word splitting as the model, cementing what was the existing
VAV behavior in the first place.
Unlike the shell, we don't expect quotes to start in the middle of a
token so <foo"bar> is invalid unless escaping was disabled.
Fields that are quoted need a separator: <"foo""bar"> is therefore
invalid unless escaping was disabled.
=> vav: Tighten arguments parsing

bin/varnishd/Makefile.am, bin/varnishd/cache/cache_ban.c, bin/varnishd/cache/cache_ban.h, bin/varnishd/cache/cache_ban_build.c, bin/varnishd/cache/cache_vrt_re.c, bin/varnishtest/tests/u00006.vtc, bin/varnishtest/vtc_haproxy.c, bin/varnishtest/vtc_logexp.c, bin/varnishtest/vtc_misc.c, bin/varnishtest/vtc_subr.c, bin/varnishtest/vtc_syslog.c, bin/varnishtest/vtc_varnish.c, include/tbl/params.h, include/vre.h, lib/libvarnish/vre.c, lib/libvarnishapi/vsl.c, lib/libvarnishapi/vsl_arg.c, lib/libvarnishapi/vsl_query.c, lib/libvarnishapi/vxp_parse.c, lib/libvcc/vcc_utils.c
See https://github.com/varnishcache/varnish-cache/pull/3616#issuecomment-864041455.
This revision of the VRE API allows the VRE facade to be the only place in the code where we actually touch pcre and offers a better abstraction for our usage. VMODs interested in more pcre features can as usual use it directly.
We can then perform the pcre2 migration (#3559) in a single `vre.c` file.
=> VRE API revamp

.circleci/config.yml, wflags.py
Since we turn warnings into errors, that means failing the build because
something we have no control over in /usr/include does not have a strict
prototype or some other shenanigan.
Just in case it might be added by Wall or Wextra in a future clang or
GCC release, we may disable it explicitly too.
Refs #3565
---
Waiting for cci to see the effect of this change.
=> build: Don't warn on system headers

vmod/vmod_std.vcc
In RST, there needs to be an empty line after ::, otherwise the whole
block is interpreted as a normal paragraph where newlines are not
preserved.
=> doc: Fix formatting in some examples

bin/varnishtest/tests/c00001.vtc, lib/libvarnish/vre.c
Before 6014912e74de7989e37b7be2737cef370b7147ba, `VRE_sub()` used an ovector of size 30, which always containted sufficient space to store the 10 possible back-references `\0` thorugh `\9`.
Now that we use `pcre2_match_data_create_from_pattern()` and later `pcre2_get_ovector_pointer()`, we only get space for the number of substrings in the pattern, see _pcre2api(3)_:
> The ovector is created to be exactly the right size to hold all the substrings a pattern might capture.
Consequently, we need to check that back references do not exceed the maximum ovector.
=> VRE: bounds check back references in VRE_sub()

bin/varnishtest/tests/r03564.vtc, doc/sphinx/reference/vcl_var.rst
This is just the order of their declaration in the VCL manual.
As a side effect it works around a bug where the sess.xid syntax
requirements would prevent sess.timeout_idle to be used in VCL 4.0,
which is less intrusive than a proper fix.
The bug was fixed in trunk without being noticed in the first place
after many heavy changes to libvcc. For a stable branch this is less
risky than a back-port since there are only two sess.* symbols.
Fixes #3564
=> vcl: Change the order of sess.* variables

bin/varnishtest/tests/r01038.vtc, bin/varnishtest/tests/r01120.vtc, bin/varnishtest/tests/r02219.vtc, include/tbl/params.h
On many busy production systems, the VSL buffer for transactions often
fills up, triggering a flush to the VSM. If such a transaction takes a
long time, it can happen that the flushed data is overwritten before
the whole transaction completes. The result is that these transactions
are missed by varnishncsa and other tools. Increasing the vsl_buffer
does the trick, at some cost in workspace usage.
The cost implies that one should increase the workspaces, too. Since
the old defaults of 64k each are too low for many common use cases
today, it is natural to increse everything in one patch.
=> Increase vsl_buffer and workspaces

bin/varnishtest/tests/b00076.vtc, doc/sphinx/reference/vcl_var.rst, lib/libvcc/vcc_symb.c, lib/libvcc/vcc_var.c
Because we funnel HTTP header names through the symbol table they have
to be valid VCL identifiers. It means that we can't support all valid
header names, which are tokens in the HTTP grammar. To finally close this
loophole without the help of a VMOD we allow header names to be quoted:
req.http.regular-header
req.http."quoted.header"
However we don't want to allow any component of a symbol to be quoted:
req."http".we-dont-want-this
So we teach the symbol table that wildcard symbols may be quoted. There
used to be several use cases for wildcards but it is now limited to HTTP
headers.
Refs #3246
Refs #3379
=> vcl: Allow header names to be quoted (compliance improvements)

lib/libvcc/vcc_compile.c, lib/libvcc/vcc_compile.h
In the output of vcl.show -v, it means that the least useful file (in the
sense that it is common to every single vcl.load) is now printed last.
This change originates from a larger and more intrusive refactoring.
It also helps get rid of spurious Wstring-contatenation warnings from
clang 12 in the test suite, instead of disabling it altogether.
Refs c8174af68956206115972e72e75ceddbd758116e
=> [6.0] vcc: Insert the built-in source last

bin/varnishd/cache/cache_req_fsm.c, bin/varnishtest/tests/r03560.vtc
Previously we would read the response Content-Length from a failed oc, which would make the error response valid. Now, if this is detected, we don't touch the Content-Length.
The root of the problem is that we race with a `boc` and end up with a failed `objcore`, all before transmitting anything. I guess we should be careful, anytime we check for a `boc` and don't get one, we should then check if the resulting `oc` is valid. Most of the time this is harmless. In this case, we are changing the `Content-Length` to zero and returning a completely valid response.
Fixes https://github.com/varnishcache/varnish-cache/issues/3560
=> Don't change the C-L if we detect a failed stream

vmod/vmod_cookie.vcc
This patch is a bit wordy, but since the `NULL` string is not explained well, I think it is justified. Comments welcome.
=> Docfix 3634

bin/varnishd/cache/cache_varnishd.h, bin/varnishd/http2/cache_http2.h, bin/varnishd/http2/cache_http2_panic.c, bin/varnishd/http2/cache_http2_proto.c, bin/varnishd/http2/cache_http2_session.c, bin/varnishd/mgt/mgt.h, bin/varnishd/mgt/mgt_param.h, bin/varnishd/mgt/mgt_param_tweak.c, bin/varnishd/storage/mgt_stevedore.c, bin/varnishd/storage/stevedore.c, bin/varnishd/storage/storage.h, bin/varnishd/storage/storage_file.c, bin/varnishd/storage/storage_malloc.c, bin/varnishd/storage/storage_simple.c, bin/varnishd/storage/storage_simple.h, bin/varnishtest/tests/f00007.vtc, bin/varnishtest/tests/r02679.vtc, bin/varnishtest/tests/t02014.vtc, bin/varnishtest/tests/t02017.vtc, bin/varnishtest/tests/t02018.vtc, bin/varnishtest/tests/t02019.vtc, bin/varnishtest/tests/t02020.vtc, bin/varnishtest/tests/t02021.vtc, bin/varnishtest/tests/t02022.vtc, bin/varnishtest/vtc_http2.c, include/tbl/params.h
This PR solves two H/2 related bugs:
* Adds a buffer for incoming data frames between the session handling thread and the individual H/2 stream threads. This avoids having the session handling thread block while waiting for a stream thread to come around and request the incoming data, which would block most progress on the H/2 session.
* Implements handling of padding bytes in incoming data frames. Previously we would ingore their presence and treat all the bytes as data bytes.
The patch set also improves on panic output for H/2.
=> Master h2 rxbuf padding

bin/varnishncsa/varnishncsa.c, bin/varnishtest/tests/u00017.vtc, doc/changes.rst
open question: does the trailing character count as part of the message, and should it be printed too?
=> [ncsa] -j will escape control characters

Makefile.am, bin/varnishtest/vtc_tunnel.c, lib/libvarnish/vbh.c, lib/libvarnish/vlu.c, tools/magic_check.sh
Only from a git clone, and only from the root directory, which should
leave alone distcheck and builds from release archives.
Fix offending magic numbers and add `make check` coverage.
=> tools: New script to check magic numbers

bin/varnishd/cache/cache.h, include/vas.h, include/vdef.h, include/vre.h, lib/libvarnish/vre.c, lib/libvarnishapi/generate.py
It populates an array of txt provided by the caller with the groups that were captured on a successful match, and returns the number of such groups or a VRE error. Because the underlying `vre_capture()` function is covered by `VRE_sub()` we can probably spare ourselves `VRE_capture()` coverage via vmod_debug.
Doing so, this patch series makes `txt` available more widely in the code base.
Alternative to #3655.
=> vre: New VRE_capture() function

bin/varnishd/cache/cache_hash.c, bin/varnishd/cache/cache_req.c, bin/varnishd/cache/cache_req_fsm.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishtest/tests/b00077.vtc, include/tbl/vsl_tags.h
The larger the response we hit, the more likely we are to hit an ongoing
fetch and since we buffer transaction logs it can become really tedious
to infer whether the backend transaction may have already been overrun
or not flushed yet. At least, such a heuristic was impossible with a VSL
query until now.
=> vsl: New "fetch status" field for Hit records

bin/varnishd/storage/stevedore.c, bin/varnishtest/tests/t02022.vtc
This looks like an oversight based on the test case expectations.
=> stevedore: Set up nuke_limit for buffer allocations

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_fetch.c, bin/varnishd/cache/cache_http.c, bin/varnishd/cache/cache_range.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishtest/tests/c00034.vtc, bin/varnishtest/tests/r00466.vtc, bin/varnishtest/tests/r02530.vtc, include/vnum.h, lib/libvarnish/Makefile.am, lib/libvarnish/vav.c, lib/libvarnish/vnum.c
That is, only when `http_range_support` is on, which is the default.
Refs #3246
---
The test coverage is by no means comprehensive, and only the last commit changes behavior.
=> vrg: Consistency check of backend responses (compliance improvements)

include/vnum.h, lib/libvarnish/vnum.c
fixes #3697
@Dridi, I know we discussed `VTIM_EPSILON` but `VNUM_EPSILON` kept things in vnum land, and we use it to test `VNUM_duration`, so it made sense?
=> [vnum] more lenient test

bin/varnishd/Makefile.am, bin/varnishd/storage/mgt_stevedore.c, bin/varnishd/storage/storage.h, bin/varnishd/storage/storage_debug.c, bin/varnishd/storage/storage_malloc.c, bin/varnishtest/tests/b00017.vtc
For now, the purpose is to regression test fc1ce6daf6a966df3aa8b7519228f60b040ff072 with a minimal amount of code.
=> Add a debug storage engine

bin/varnishd/cache/cache_vrt.c, doc/changes.rst, include/vrt.h, lib/libvcc/vcc_expr.c, vmod/vmod_debug.c, vmod/vmod_directors_shard.c, vmod/vmod_directors_shard_cfg.c
As much as `VCL_STRANDS` has it's merits, it is tedious to work with for simple cases like passing arguments to VRT functions.
These macro attempt to make life a little easier for vmod authors.
Motivated by https://github.com/kenshaw/libvmod-dns/pull/15/files
Usage examples:
```c
VCL_STRING on_ws = VRT_STRANDS_string(ctx, VSTR(some_function()));
VCL_STRANDS on_stack = VSTRS(4, "one", two_func(), "3", four_func());
```
BTW: I could not find a nice/clean way to count the number of arguments to a variadic macro, so I do not think we get around the requirement to declare the number of strings to pass.
=> Macros to simplify VCL_STRANDS use

lib/libvarnishapi/vut.c
=> Clear vut->sighup even if sighup_f is not defined

bin/varnishd/mgt/mgt_param.c, doc/changes.rst, include/tbl/params.h
Note: This is a PR into 6.0, our LTS branch.
A default stack space of 48k will cause a stack overflow in _some_ of the test cases (VMOD `blob`, specifically) on _some_ Linux distributions. The increase to 64k seems to be enough to solve this.
=> Increase default stack space

.travis.yml, bin/varnishd/Makefile.am, bin/varnishd/cache/cache_panic.c, configure.ac
```
Conflicts:
.travis.yml
bin/varnishd/cache/cache_panic.c
```
---
Test cases m35 to m38 are currently failing on my machine, two of the failures seem to be caused by a segmentation fault in `funlockfile()`. As *usual* (emphasis on usual) libunwind made this much easier to figure out than the libexecinfo back-trace, so I'm submitting a back-port of @gquintard's patch.
=> Offer a configure --with-unwind switch (6.0)

bin/varnishd/mgt/mgt_vcl.c, bin/varnishtest/tests/r03734.vtc
Using the wrong list variable would cause the dependency check to consider
VCLs that were not attempted discarded.
Fixes: #3734
=> Use correct list var name in mgt_vcl_discard_depcheck

bin/varnishd/cache/cache_main.c, include/tbl/cli_cmds.h
For the purpose of simulating a workload where the cache process takes significant time to shut down.
=> cli: New debug.shutdown.delay command

configure.ac
One can still use the --without-unwind configure flag.
Refs #3717
=> build: Use libunwind if available at configure time

lib/libvarnish/vre.c
which I think vmods will require eventually.
I would actually need `PCRE2_NOTBOL|PCRE2_NOTEOL` right now, but hope to get around it...
=> Whitelist some pcre2 match options

bin/varnishd/cache/cache_acceptor.c, bin/varnishd/common/heritage.h, bin/varnishtest/tests/l00000.vtc, bin/varnishtest/tests/o00001.vtc, bin/varnishtest/tests/o00006.vtc, bin/varnishtest/tests/r01804.vtc, bin/varnishtest/tests/r02722.vtc
See individual commits for all the details, and a test case in the last commit that fixes a bug that exists at least on Linux that would result in missing socket options on unix domain sockets under certain circumstances.
Before back-porting this to 6.0, we should probably back-port #3704 first.
=> Refactoring of the acceptor sockopt inheritance

.github/workflows/cifuzz.yml
Add CIFuzz workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz, on which Varnish-cache already runs.
=> github actions: add CIFuzz integration

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_fetch.c, bin/varnishd/cache/cache_req_fsm.c, bin/varnishd/cache/cache_vrt_var.c, bin/varnishtest/tests/b00030.vtc, bin/varnishtest/tests/e00030.vtc, bin/varnishtest/tests/r02219.vtc, doc/sphinx/reference/vcl_var.rst
See https://github.com/varnishcache/varnish-cache/pull/3553#issuecomment-804133604
Reviewers please let me know what think about this: We could have more & better assertions on `(ctx)->where`. If we want them, I would propose to add some utility macros like
```
#define VRT_CHECK_req(ctx) ...
#define VRT_CHECK_oc(ctx) ...
...
#define VRT_ACCESS_req(ctx) ...
#define VRT_ACCESS_oc(ctx) ...
...
```
such that we can generalize macros
=> Add {req,resp,bereq,beresp,obj}.time

bin/varnishd/cache/cache_shmlog.c, include/vapi/vsl_int.h
When vsl_reclen (maximum length of a record) is close to vsl_buffer,
the vsl buffer is flushed to the main shared memory log for every
record. This is because we test if there is space for vsl_reclen, not
the actual size of the formatted log record (which likely is much
smaller).
Fix this by doing the formatting in up to two stages. If the first
stage shows that we overflowed, but would not have overflown
vcl_reclen if there was more room in the buffer, then flush and redo
the formatting. This limits the extra work of formatting twice only to
the one record that happened to overflow the buffer.
=> Fix unnecessary log buffer flushing

bin/varnishlog/varnishlog.c, bin/varnishlog/varnishlog_options.h, bin/varnishncsa/varnishncsa.c, bin/varnishncsa/varnishncsa_options.h, bin/varnishtest/tests/u00003.vtc, bin/varnishtest/tests/u00006.vtc, bin/varnishtest/tests/u00019.vtc, include/vut_options.h, lib/libvarnishapi/vsl.c, lib/libvarnishapi/vut.c
As suggested in the https://github.com/varnishcache/varnish-cache/issues/3740#issuecomment-975240592 summary, I'm adding "-" meaning `stdout` for the `-w` option for parity with the `-r` option. Because VUTs daemonize closing the standard streams, it is now treated as an error to both daemonize and read or write from `stdin` or `stdout`.
Instead of adding errors as suggested for `-A` without `-w`, it is documented as a no-op in this situation, and the same is done for `-a` and `-u`.
=> vut: Write to stdout with a "-w -" option

lib/libvmod_std/vmod_std_conversions.c
Otherwise valid code can panic on workspace exhaustion:
std.ip(req.http.X-Real-IP, std.ip(req.http.X-Client-IP, client.ip))
If the nested std.ip() call runs out of workspace, it will return a null
ip instead of the fallback, and the outer std.ip() call will panic upon
checking the suckaddr sanity.
Refs #3746
=> std.ip: Always provide some form of fallback (6.0)

bin/varnishd/cache/cache_hash.c, include/tbl/oc_flags.h
HSH_Purge() suffers from a problem when there are more objcores on a given
objhead than we can hold temporary references for on the available
workspace, and multiple purges for the same objhead are issued at the same
time.
The previous algorithm would use a flag on the objcores (OC_F_PURGED) in
order to keep track of how far in the list we had gotten. This becomes a
problem when multiple threads are purging the same objhead at the same
time. When a new purge is started, the flags would be reset, which would
cause any existing purge thread to restart. If a steady stream of purges
for a given objhead is issued and enough objcores are present, none would
finish.
This rework uses OC references in the list as bookmarks, in order to know
how far into the list we were when releasing the mutex …
=> Rework HSH_Purge()

bin/varnishd/cache/cache_main.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishd/cache/cache_wrk.c, bin/varnishd/cache/cache_ws.c, bin/varnishd/cache/cache_ws_emu.c, bin/varnishd/fuzzers/esi_parse_fuzzer.c, bin/varnishtest/tests/c00071.vtc
That is, when it's a request or backend transaction, otherwise it's
still logged with VXID 0. The goal is to allow a correlation between
VCL statements and their workspace footprint by sharing the same
transaction instead of being split between raw and vxid scopes. That
kind of debugging becomes possible when the workspace debug flag is
used and VCL_trace records are not masked.
Given the verbosity of both workspace and trace logs, we would need
new tools to process transactions for this purpose and until we can
link everything we have a chicken-egg problem.
This change introduces a new thread-local variable to keep track of a
worker's VSL when it is given one. Not all workspace operations from
a transaction are logged, the missing bits are early initialization
and teardown: in other …
=> Tie workspace logs to their transactions

bin/varnishd/cache/cache_vrt_var.c, bin/varnishtest/tests/r03079.vtc, doc/sphinx/reference/vmod.rst, include/vrt.h, lib/libvcc/generate.py, lib/libvcc/vcc_action.c, lib/libvcc/vcc_compile.h, lib/libvcc/vcc_expr.c, lib/libvcc/vcc_types.c
This patch series is a different take on #3114 that takes a different approach than #3123, as announced in https://github.com/varnishcache/varnish-cache/issues/3114#issuecomment-595805313.
It does mainly four things:
- Allow `set BODY [+]= STRINGS|BODY`
- Automatic cast from `STRINGS` to `BLOB`
- Migrate `std.fileread()` logic to a new VFC [1] subsystem
- Reuse VFC in a new `blob.fileread()` function
I followed the direction we agreed on and my only peeve is that VFC lives in `libvarnish` and it might not be the best venue. In order to avoid needless BLOB allocations I need VFC to hand over a BLOB directly which creates a "reverse" dependency from `libvarnish` to `vrt.h` that is not to my liking.
The other thing I'm not too happy about is the `vcc_PeekExpr` function. I had two approaches …
=> Allow *.body to take either a STRING or a BLOB

bin/varnishd/mgt/mgt_param.c, bin/varnishd/mgt/mgt_param.h, bin/varnishd/mgt/mgt_param_tweak.c, bin/varnishtest/tests/b00078.vtc, include/tbl/params.h
With this change, we can formalize the renaming of a parameter while
maintaining the old name temporarily for compatibility.
A deprecated alias can be set with either `param.set` or the `-p` option,
but won't be listed by:
- `param.show [-j]`
- `param.show [-j] changed`
- `param.show -l`
Only an explicit `param.show` for the name of the alias will provide a
minimal documentation with a deprecation notice and the current value.
In the manual, there is only a deprecation notice. The rationale is
that administration tools shouldn't pick them up when enumerating the
parameters.
Since we currently don't have deprecated parameters, this can only be
tested manually, for example:
PARAM_ALIAS(vcl_dir, vcl_path)
To ensure that we don't break this, we could consider having a perpetual
deprecated …
=> param: Infrastructure for deprecated aliases

bin/varnishd/cache/cache_req_fsm.c, bin/varnishtest/tests/b00030.vtc, bin/varnishtest/tests/v00051.vtc, doc/sphinx/reference/vcl_var.rst, doc/sphinx/reference/vsl.rst
And expose bereq.time in vcl_pipe now that we have some.
Refs #3562
=> pipe: Add missing Start and Process timestamps

bin/varnishd/mgt/mgt.h, bin/varnishd/mgt/mgt_param.c, bin/varnishd/mgt/mgt_param.h, bin/varnishd/mgt/mgt_vcc.c, bin/varnishtest/tests/c00109.vtc, configure.ac, include/tbl/params.h
See the current trunk docs for `cc_command`:
https://varnish-cache.org/docs/trunk/reference/varnishd.html#cc-command
Currently it says:
> Default: exec clang -g -O2 -Wall -Werror -Wno-error=unused-result -fstack-protector-strong -Werror -Wall -Wcast-align -Wcast-qual -Wchar-subscripts -Wempty-body -Wextra -Wformat -Wformat-y2k -Wformat -Wformat-zero-length -Wmissing-field-initializers -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wpointer-sign -Wreturn-type -Wshadow -Wstrict-aliasing -Wstrict-prototypes -Wstring-plus-int -Wswitch -Wunused-parameter -Wunused-result -Wwrite-strings -Wno-old-style-definition -Wno-sign-compare -Wno-implicit-fallthrough -Wno-missing-variable-declarations -Wno-nullability-completeness -fstack-protector -Wno-missing-field-initializers -pthread -fpic …
=> param: Cleanup of cc_command (and collaterals)

bin/varnishd/cache/cache_deliver_proc.c, bin/varnishd/cache/cache_esi_deliver.c, bin/varnishd/cache/cache_esi_fetch.c, bin/varnishd/cache/cache_fetch.c, bin/varnishd/cache/cache_fetch_proc.c, bin/varnishd/cache/cache_filter.h, bin/varnishd/cache/cache_gzip.c, bin/varnishd/cache/cache_range.c, bin/varnishd/cache/cache_req_body.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishd/cache/cache_vrt_filter.c, bin/varnishd/http1/cache_http1_deliver.c, bin/varnishd/http2/cache_http2_deliver.c, vmod/vmod_debug.c
This allows VDPs and VFPs to pass state from a PRIV_TASK to respectively
a vdp_entry or a vfp_entry. When a filter is set up by a VMOD, there is
otherwise no way to configure a filter on a per-task basis.
=> filter: Pass a VRT_CTX to the init methods

.circleci/config.yml
We see linking failures sometimes, so hopefully that solves those.
=> circleci: Update packages on archlinux

bin/varnishd/cache/cache_esi.h, bin/varnishd/cache/cache_esi_deliver.c, bin/varnishd/cache/cache_esi_parse.c, bin/varnishtest/tests/e00035.vtc, include/tbl/feature_bits.h
This changes the default behavior of includes, matching the ESI language specification. The onerror attribute seems to only accept one value, so in its absence a failed ESI fragment delivery aborts the top request delivery.
In addition, it breaks the ESI object attribute format for persisted caches.
---
This is OK for trunk to change the default behavior and objattr format, but for the 6.0 LTS branch we would need to gate this behind a feature flag. I'm wondering whether this is fine to have such an `esi_include_onerror` flag in 6.0 that does not exist in trunk.
=> esi: Implement <esi:include onerror="continue"/>

bin/varnishd/cache/cache_pool.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishd/common/common_param.h, bin/varnishd/mgt/mgt.h, bin/varnishd/mgt/mgt_param_bits.c, bin/varnishtest/tests/c00080.vtc, include/Makefile.am, include/tbl/experimental_bits.h, include/tbl/params.h
This parameter should ease the introduction of features that may later
be removed without being considered a breaking change. For features that
get promoted to either being always present or behind the feature param,
it sends a clear signal regarding when we consider a feature ready for
production. This could have been useful for HTTP/2 support for example.
The first experimental feature is the ability to drop thread pools,
which was behind the debug param.
Having EXPERIMENTAL in the code takes a lot of real estate, but exp is
already established as short for expiry.
---
I omitted this patch since there is already a lot to review for a single new parameter:
```diff
diff --git i/include/tbl/params.h w/include/tbl/params.h
--- i/include/tbl/params.h
+++ w/include/tbl/params.h
@@ -1695,6 …
```
=> param: New experimental parameter

bin/varnishtest/tests/r01332.vtc, include/tbl/symbol_kind.h, lib/libvcc/generate.py, lib/libvcc/vcc_compile.h, lib/libvcc/vcc_symb.c, lib/libvcc/vcc_vmod.c, lib/libvcc/vmodtool.py, vmod/vmod_cookie.c, vmod/vmod_cookie.vcc, vmod/vmod_debug.vcc
Their sole purpose is to resolve to another symbol. The script expects aliases to be defined like this in the RST docs:
my.alias ``VCL <= 4.1``
Type: DEPRECATED
Alias of: something.else
A little description is still necessary.
This should facilitate renaming variables in the future. One thing we could do is to have libvcc warn about deprecated aliases (subject to a new `vcc_err_alias` parameter too) to make this visible not just in the manual.
There is no `DEPRECATED` type in addition to the new `SYM_ALIAS` kind, this is a purely cosmetic suggestion.
Deprecated aliases should probably have a high VCL version limit like in the example above, `generate.py` doesn't enforce it so far.
Aliases have zero runtime cost, since ultimately the aliased symbol is used at compile time instead of the …
=> vcc: New SYM_ALIAS kind for deprecated symbols

bin/varnishd/cache/cache_req_fsm.c, configure.ac, doc/changes.rst, doc/sphinx/index.rst, doc/sphinx/whats-new/changes-7.1.rst, doc/sphinx/whats-new/index.rst, doc/sphinx/whats-new/upgrading-7.1.rst, include/vrt.h, lib/libvarnish/version.c
Small changes to the release process document so far:
https://github.com/varnishcache/varnish-cache/wiki/Release-procedure/_compare/1828e403030ed12ccfe4a00c8d65fa28f4fc5727...b11b98093a9cd87af2dede6c0161d5ada101e143
=> Prepare for 7.1.0

bin/varnishtest/vtc_http.c
Apparently, clang11 on i386 macOS uses `int` instead of `ssize_t` for `a- b` where bot `a` and `b` is `char`. It leads to an error:
```
vtc_http.c:392:8: error: format specifies type 'ssize_t' (aka 'long') but the argument has type 'int' [-Werror,-Wformat]
p - hp->body, t, *p);
^~~~~~~~~~~~
```
See https://build.macports.org/builders/ports-10.6_i386-builder/builds/64402/steps/install-port/logs/stdio as example of such error.
=> Fixed build on i386 macOS with clang-11

bin/varnishd/cache/cache_acceptor.c, bin/varnishd/mgt/mgt_param_tcp.c, configure.ac
TCP_KEEPALIVE is the TCP_KEEPIDLE's equivalent and uses seconds
for the idle time.
=> tcp_keepidle socket option support for macOs.

bin/varnishd/mgt/mgt_param_tweak.c, bin/varnishtest/tests/b00042.vtc, include/tbl/params.h
Allowing units is much more convenient and keeping them optional
maintains compatibility. On the other hand, changing the defaults
for default_ttl and default_grace has no impact on the generated
RST.
Keeping track of the user input could help since default values
are "washed" like user input, without resorting to a dynamic
default.
Refs #3756
=> param: Optionally pass a duration unit to timeouts

bin/varnishd/cache/cache_backend.c, bin/varnishd/cache/cache_fetch.c, bin/varnishd/http1/cache_http1_fetch.c, bin/varnishtest/tests/b00073.vtc, bin/varnishtest/tests/f00001.vtc, bin/varnishtest/tests/r02332.vtc, doc/sphinx/reference/directors.rst, include/tbl/bo_flags.h
There is no cancellation mechanism in the middle of an HTTP/1
transaction besides closing the session. If a backend closes
the connection before the end of the bereq delivery, it may
also send a 4XX or 5XX response that could be valuable for the
original client.
In this scenario, we can process the backend response, and we
can use the bereq.send_failed flag to decide what to do about
broken transactions. The beresp.fetch_failed flag can never
be raised in vcl_backend_response but is made available to
enable code sharing with vcl_backend_error as demonstrated in
r02332.
The test case r02332 is a combination of the 3 test cases
from #3686.
There are several things to take into consideration: it is
the responsibility of the backend implementation to raise the
send_failed and fetch_failed …
=> vbe: Try fetching beresp when sending bereq failed

doc/sphinx/reference/vcl_var.rst, vmod/tests/std_b00001.vtc, vmod/vmod_std.c, vmod/vmod_std.vcc
The first commit of the two is just a doc polish which goes to this PR because of the current freeze.
The second commit is the actual PR:
``std.now()`` fills a gap left by the stable time of the now variable in VCL: Sometimes we need to know the current time after some longer processing in VCL.
``std.timed_call()`` is intended to measure longer operations in VCL. ``std.timestamp()`` exists already to add accurate measurements to the log. ``std.timed_call()`` is for cases where the duration is required in VCL, for example to enrich HTTP requests/responses.
=> std.now() and std.timed_call()

.circleci/config.yml, .circleci/make-deb-packages.sh, .circleci/make-rpm-packages.sh
Use their version number as the image tag instead of the code name for
clarity. Add a packaging job for the incoming Ubuntu 22.04, and add
distcheck jobs for Ubuntu 20.04 and 22.04 with a comment explaining
which Ubuntu is arbitrarily selected for 32bit builds.
Also, stop pretending that CentOS is a dpkg-based distribution, we are
not fooling anyone.
=> circleci: Revamp Ubuntu jobs

configure.ac
According to the GCC manual on -fno-omit-frame-pointer:
> Note that -fno-omit-frame-pointer doesn't guarantee the frame pointer
> is used in all functions.  Several targets always omit the frame
> pointer in leaf functions.
And what is says about -m[no-]omit-leaf-frame-pointer:
> -momit-leaf-frame-pointer
> -mno-omit-leaf-frame-pointer
>
> Omit or keep the frame pointer in leaf functions.  The former behavior
> is the default.
So we should probably prevent both.
=> build: Add -mno-omit-leaf-frame-pointer to sanitizer CFLAGS

bin/varnishd/cache/cache_shmlog.c, bin/varnishtest/tests/l00006.vtc, lib/libvsc/VSC_main.vsc
We have various stat counters for the shared memory log (shmlog),
but nothing to give us the number of bytes used (consumed).  To
address this, add new stat counters to the shmlog:
shm_bytes
Total number of bytes used in the shared memory log.
This includes bytes unused when we wrap.
shm_bytes_wrap
Number of bytes unused when we wrap.
Signed-off-by: Dridi Boukelmoune <dridi.boukelmoune@gmail.com>
---
I'm submitting this change on behalf of @drodden from @varnish, and I bundled an additional trivial patch.
=> vsc: New MAIN.shm_bytes* counters

include/Makefile.am
Do we need many words?
I think it's equally useful as `vtim.h` and should be available to vmods.
=> Install vnum.h

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_fetch.c, bin/varnishd/cache/cache_panic.c, bin/varnishd/cache/cache_req_fsm.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishd/cache/cache_vcl.c, bin/varnishd/cache/cache_vpi.c, bin/varnishd/cache/cache_vrt.c, bin/varnishd/cache/cache_vrt_priv.c, bin/varnishd/cache/cache_vrt_vcl.c, bin/varnishd/cache/cache_wrk.c, include/vcc_interface.h, include/vrt.h, lib/libvcc/vcc_compile.c, tools/coccinelle/archive/wrk_vpi.cocci, vmod/vmod_debug.c, vmod/vmod_debug_dyn.c
As documented in [this comment](https://github.com/varnishcache/varnish-cache/pull/3512#issuecomment-770905412), I was asked to make VCL source line information (as tracked by `VPI_count()`) available in panics. This would actually be very handy for analysis, and if there _was_ a place for the vpi count in `VRT_CTX`, we could make `VCL_Trace` a VCC flag (turning tracing on only if explicitly asked for at compile time), turn `VPI_count()` into a very efficient inline function and spare a lot of function calls while VCL code is executing.
And so I went down a rabbit role:
* Panics use thread local storage as provided by `pthread_setspecific()` to get hold of the panicking thread's context (req, bo etc)
* We want use tls sparsely due to the cost involved
* We cannot just track additional …
=> Formalize VCL Private data access via VRT_CTX / VCL line info in panics

bin/varnishncsa/varnishncsa.c, doc/sphinx/reference/varnishncsa.rst
This PR backports #3499
---
Allow the user to log the request time in milliseconds through the new format specifier: `%{ms}T`.
=> [LTS Backport] varnishncsa: log request time in milliseconds

configure.ac, doc/changes.rst, doc/sphinx/whats-new/changes-7.2.rst, doc/sphinx/whats-new/index.rst, doc/sphinx/whats-new/upgrading-7.2.rst, include/vrt.h
=> Release 7.2.0

contrib/Makefile.am
Avoid this warning:
```
autoreconf2.69: running: automake --add-missing --copy --no-force vtc.am:12: warning: 'TEST_EXTENSIONS' cannot have conditional contents
contrib/Makefile.am:12:   'vtc.am' included from here
```
Always defining the tests even if contrib is not built should not cause any harm.
=> Polish contrib Makefile

configure.ac
Trying to use zlib from a vmod would lead to conflicts because the varnish-defined zlib symbols were found first.
=> Define Z_PREFIX to prevent collisions with zlib

bin/varnishd/cache/cache.h, vmod/vmod_cookie.c, vmod/vmod_debug.c, vmod/vmod_directors_shard.c, vmod/vmod_directors_shard_cfg.c
isn't this something we would have wanted all along?
This simplifies the common pattern to allocate/initialize a miniobj on the workspace to
```c
WS_TASK_ALLOC_OBJ(ctx, myobj, MYOBJ_MAGIC);
if (myobj == NULL)
return (error);
```
=> Add a utility macro to allocate mini-objects on the workspace

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_fetch.c, bin/varnishd/cache/cache_hash.c, bin/varnishd/cache/cache_obj.c, bin/varnishd/cache/cache_vrt_var.c, bin/varnishd/storage/storage_simple.c, bin/varnishtest/tests/c00110.vtc, bin/varnishtest/tests/c00111.vtc, bin/varnishtest/tests/c00112.vtc, doc/sphinx/reference/vcl_var.rst, include/tbl/params.h
This PR implements the transit buffer feature (previously called pass buffering).
=> feature: Transit buffer

bin/varnishd/mgt/mgt_acceptor.c, bin/varnishtest/tests/c00003.vtc, bin/varnishtest/tests/c00121.vtc, bin/varnishtest/tests/v00038.vtc, bin/varnishtest/vtc_misc.c, doc/sphinx/reference/varnishd.rst, doc/sphinx/reference/vcl-backend.rst, include/vus.h, lib/libvarnish/vsa.c, lib/libvarnish/vus.c, lib/libvcc/vcc_backend.c
We use the commonplace @<name> syntax to specify abstract socket names.
Implements #3863
=> Support abstract sockets for accept and .path to backends

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_fetch.c, bin/varnishd/cache/cache_rfc2616.c, bin/varnishtest/tests/b00002.vtc, bin/varnishtest/tests/b00037.vtc, bin/varnishtest/tests/b00079.vtc, bin/varnishtest/tests/c00036.vtc, bin/varnishtest/tests/l00004.vtc, bin/varnishtest/tests/l00005.vtc, bin/varnishtest/tests/r00498.vtc, bin/varnishtest/vtc_http.c
This PR changes backend revalidations to only send If-Modified-Since if the Last-Modified header is at least one second older than the Date header, to prevent revalidating content that changed within the same second.
varnishtest servers now send a Date header by default, unless `-nodate` is specified. While in the neighborhood, `-nolen` was adjusted to behave similar to `-nohost` and `-nodate`.
RFC9110 states (this is not new, but some of the wording has changed over time):
> A Last-Modified time, when used as a validator in a request, is implicitly weak unless it is possible to deduce that it is strong, using the following rules:
> 
> (...)
> 
> - The validator is being compared by an intermediate cache to the validator stored in its cache entry for the representation, and
> - That cache …
=> Don't send If-Modified-Since if Last-Modified is a weak validator

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_http.c, bin/varnishd/cache/cache_range.c, include/vrt.h
This came up on the enterprise side, the need to move more parsing free of side effects to `http_GetRange()`. It changes the function signature but I'm not sure whether it qualifies as VRT material.
=> range: Move more parsing to http_GetRange()

configure.ac, lib/libvgz/Makefile.am
Trying to fix the build for clang 15 actually broke the build for GCC.
The -Werror that was initially set after saving CFLAGS was meant to be part of NO_VIZ test. We turn warnings into errors later in the configure script so at this point we shouldn't care about it. If we really do, we can move this check below the line where -Werror is set.
GCC chokes on -Wno-error=deprecated-non-prototype so instead we add it conditionally.
To match the naming convention everywhere else, libvgz_extra_cflags was renamed to VGZ_CFLAGS.
Refs 118fd10c9e81920e0c31906c2bf5c62a3f25cd5b
---
Opening a pull request this time, to make sure it passes CI first.
=> build: Revisit zlib C flags one more time

bin/varnishd/common/common_param.h, bin/varnishd/mgt/mgt_vcc.c
They are shared with the cache process but are never used. Only the VCC
process uses them, but they are never set. This specific fchown(2) call
in the VCC process was probably a no-op in the first place: since the
fields are never set this is transferring ownership to root:root and if
that succeeded the process was already root in the first place. If it
failed, we never see the error message since we lacked root privileges.
When this fchown(2) call is made (multiple times) the files are created
by a VCC process that already dropped privileges, if applicable, via the
jail system. So the VJ_fix_fd() replacement may also be a no-op.
=> heritage: Remove unset params::[gu]id fields

lib/libvarnish/vre.c
This patch optimizes substitutions to relevant extent as shown by the percentiles of execution times in microseconds from the test detailed below:
unpatched:
10% | 20% | 30% | 40% | 50% | 60% | 70% | 80%  | 90%
--- | --- | --- | --- | --- | --- | --- | --- | --- |
12.8219 | 12.8650 | 12.9070 | 12.9506 | 13.0225 | 19.2838 | 19.4100 | 19.5714 | 22.7865
patched:
10% | 20% | 30% | 40% | 50% | 60% | 70% | 80%  | 90%
--- | --- | --- | --- | --- | --- | --- | --- | --- |
8.5710 |  8.6090 |  8.6390 |  8.6676 |  8.7020 |  8.8440 |  9.1669 | 10.3150 | 11.0061 
test vcl:
```
vcl 4.1;
backend none none;
import std;
sub perf {
set beresp.http.Snafu8 =
regsub(beresp.http.Foobar, "(b)(a)(r)(f)", "0123456789abcdef0123456789abcdef\4\3\2p0123456789abcdef0123456789abcdef");
set beresp.http.Snafu8 = …
```
=> Optimize VRE_sub() by avoiding VSB_putc()

doc/sphinx/whats-new/changes-trunk.rst, doc/sphinx/whats-new/upgrading-trunk.rst, include/vapi/vsl_int.h, include/vsl_priv.h, lib/libvarnishapi/vsl.c, lib/libvarnishapi/vsl_api.h, lib/libvarnishapi/vsl_cursor.c
This is currently work in progress, but I plan to cover a first sweep of:
=> release: Prep work before the next release

bin/varnishd/mgt/mgt_main.c
I noticed that users, apparently, have no way of finding out what their distribution configured?
=> Inform about the default working directory in usage information

bin/varnishtest/tests/m00003.vtc, configure.ac, doc/changes.rst, doc/sphinx/index.rst, doc/sphinx/whats-new/changes-7.3.rst, doc/sphinx/whats-new/index.rst, doc/sphinx/whats-new/upgrading-7.3.rst, include/vrt.h, lib/libvarnish/version.c
=> Prepare for 7.3.0

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_main.c
When mgt sends a command to the cache process, whether it is a period ping or an actual operation, it must complete within cli_timeout. When the cache fails to meet this requirement, mgt sends a SIGQUIT signal to the cache process. As a result the cache process MAY dump a core file for post-mortem analysis.
When the core file is missing we are left to our own devices.
To mitigate this, a new signal handler is added for SIGQUIT, but since we can't (or don't even try to) guarantee delivery on the CLI thread, we make a last-ditch effort to forward SIGQUIT signals to properly panic from the CLI thread. With a regular panic we may get both a panic report and a core dump.
I didn't add test coverage for this, since we try to avoid intentional core dumps in test cases with the `no_coredump` …
=> cache: It's time for the big quit

bin/varnishd/storage/stevedore.c, bin/varnishtest/tests/r03502.vtc
We only log a Storage record when we successfully create an object, but there may be no clue regarding which storage backend failed to allocate. We can infer from stevedore VSCs where allocation failures happened, but knowing from a VCL transaction which one failed will give a definitive answer.
This is logged as an Error record, and the existing FetchError record from VFPs ("Could not get storage") is left alone.
=> stevedore: Log failures to create objects

bin/varnishd/http1/cache_http1_line.c, bin/varnishtest/tests/b00081.vtc, include/tbl/params.h, lib/libvsc/VSC_main.vsc
This PR adds a counter for premature iovec flushes (V1L_Flush).  This  can be useful to detect when we run out of iovecs during a transaction (due to small workspace_thread or http1_iovs values for example).
The second commit improves the doc of http1_iovs parameter and adds some test coverage.
=> Add counter for premature Iovec flushes

.gitignore, bin/varnishtest/tests/b00016.vtc, bin/varnishtest/tests/c00055.vtc, bin/varnishtest/tests/m00055.vtc, bin/varnishtest/tests/r02339.vtc, bin/varnishtest/tests/v00043.vtc, bin/varnishtest/tests/v00051.vtc, doc/sphinx/reference/vmod.rst, include/Makefile.am, lib/libvcc/generate.py, lib/libvcc/vcc_vmod.c, lib/libvcc/vcc_vmod.h, lib/libvcc/vcc_vmod_sym.c, lib/libvcc/vmodtool.py, vmod/tests/directors_c00015.vtc, vmod/tests/std_c00001.vtc, vmod/tests/unix_c00000.vtc, vmod/vmod_debug.vcc, vmod/vmod_directors.c, vmod/vmod_directors.vcc, vmod/vmod_proxy.vcc, vmod/vmod_purge.vcc, vmod/vmod_std.c, vmod/vmod_std.vcc, vmod/vmod_unix.c, vmod/vmod_unix.vcc
This PR introduces the $Restrict feature described in [vip4](https://github.com/varnishcache/varnish-cache/wiki/VIP4%3A-Restrict-VMOD-function-call-sites).
It provides the ability to restrict vmod functions and methods scope so that they can only be called
from limited VCL built-in sub routines. The first commit introduces the feature, and the following ones use it on relevant vmods.
=> Vip4: add $Restrict in vcc

bin/varnishd/cache/cache_filter.h, include/vrt.h
to facilitate custom filter parametrization:
VMOD filters are likely to use the same init/bytes/fini callbacks for many vcl objects, which differ only in their parameters. It would be helpful to have a place to stash a per VCL private pointer.
=> Add a private pointer to struct vdp

bin/varnishd/cache/cache_req_fsm.c, bin/varnishtest/tests/r02618.vtc, vmod/vmod_debug.c
Context: This issue was spotted while working on #3916 
We currently miss to close VDPs for transport error conditions. This PR adds a (possibly redundant) `VDP_Close()` call to `cnt_transmit()` to ensure that processors' fini method is always called.
The rest of the PR is test infrastructure: the `debug.pedantic` VDP now asserts that the fini method be called by using a `PRIV_TASK` which, when _it_ is finalized, the VDP already was.
=> Close VDPs also for error conditions and extend debug.pedantic vdp to test

bin/varnishd/cache/cache_req_fsm.c, bin/varnishd/cache/cache_vcl.c, bin/varnishd/cache/cache_vpi.c, bin/varnishd/cache/cache_vrt.c, bin/varnishd/cache/cache_vrt_var.c, bin/varnishtest/tests/c00005.vtc, bin/varnishtest/tests/c00054.vtc, bin/varnishtest/tests/r02413.vtc, doc/changes.rst, doc/sphinx/reference/vcl_var.rst, include/tbl/feature_bits.h, include/tbl/params.h, include/tbl/req_bereq_flags.h, include/vcc_interface.h, include/vdef.h, include/vrt.h, lib/libvcc/vcc_parse.c
This PR is the implementation of the bugwash agreement in https://github.com/varnishcache/varnish-cache/pull/3836#issuecomment-1230335147
I am opening a new PR to properly document the performance implications of the alternative approaches. I ran the [*max potential* benchmark from #3515](https://github.com/varnishcache/varnish-cache/pull/3515#issuecomment-834635932) again on master, #3836, this branch, and one with branch predictions enabled. The results are given below as quantiles of `Timestamp:Process` times for 100000 requests:
My conclusion is that, while the tracing calls (not) compiled into VGC is still the fastest option, the runtime check from this PR is still substantially faster than the original code from master. If we think that a runtime tracing switch is an important …
=> Add (be)req.trace and feature +trace to control generation of VCL_trace logs

bin/varnishd/cache/cache_deliver_proc.c, bin/varnishd/cache/cache_esi_deliver.c, bin/varnishd/cache/cache_req_fsm.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishd/http1/cache_http1_deliver.c, bin/varnishd/http2/cache_http2_deliver.c
This is the alternative to #3916 discussed during bugwash, where `HSH_Cancel()` gets called from `VDP_Close()`.
The corresponding MR for pESI is here: https://gitlab.com/uplex/varnish/libvdp-pesi/-/merge_requests/3
Commit message:
Transports should be free to keep a reference on the object to be delivered until after their transport function returns, but HSH_Cancel() in cnt_transmit() prevented the object from being of any use for the case that it is final (pass/hfm/hfp).
We solve this by moving the HSH_Cancel() close to VDP_Close, which also makes sense from the perspective of the VDP design: Until the VDP close, filters could still reference object data.
HSH_Cancel() needs the objcore, which could be reachable also via vdc->req. But that member is unset in VDP_DeliverObj(), presumably …
=> Move HSH_Cancel() to VDP_Close() to bring it under transport control

Makefile.am, configure.ac, lib/libvcc/vmodtool.py, lib/libvsc/Makefile.am, vmod/Makefile.am, vmod/automake_boilerplate_blob.am, vmod/automake_boilerplate_cookie.am, vmod/automake_boilerplate_debug.am, vmod/automake_boilerplate_directors.am, vmod/automake_boilerplate_proxy.am, vmod/automake_boilerplate_purge.am, vmod/automake_boilerplate_std.am, vmod/automake_boilerplate_unix.am, vmod/automake_boilerplate_vtc.am, vsc.am, vtc.am
The new vsc.am file takes care of most of the logic, and include sites only need to reference sources as such.
=> build: Centralize suffix .c.vsc make rules

bin/varnishd/cache/cache_vrt_var.c, bin/varnishtest/tests/v00068.vtc
From an Enterprise ticket, trying to unset a cached request body currently accomplishes nothing.
The body can be sent after the first request (without Content-Length), and the body bytes become a part of the next request.
=> bereq: Also unset a cached req body

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_shmlog.c, bin/varnishd/http2/cache_http2_proto.c
The ``VSB``/``printf`` bits in here come with a very significant performance penalty, also for the case when the log tags are masked (which they are by default).
On my laptop this cuts processing of a 1G POST from 45 seconds down to <1s.
=> h2_vsl_frame: Exit early if masked

bin/varnishd/cache/cache_req_body.c, bin/varnishtest/tests/c00123.vtc
Instead of trying to allocate storage for the entire request body when the content length is known, let it go in fetch_chunksize steps. This may prevent spurious cache evictions for large request bodies for pass transactions when we are merely streaming the body.
On the other hand, when the content length is known and the goal is to cache the request body, we may still attempt a single allocation and all that entails.
=> vrb: Reduce storage pressure from req.body

bin/varnishd/cache/cache_vcl.c, bin/varnishd/mgt/mgt_jail.c
I also tried `mmap(PROT_READ|PROT_EXEC)`, but, apparently, that needs a proper executable.
Fixes #3943
=> Warn about pitfall: workdir on noexec mountpoint

bin/varnishd/mgt/mgt_child.c, bin/varnishtest/tests/p00000.vtc, bin/varnishtest/tests/r03940.vtc, bin/varnishtest/tests/s00003.vtc, include/tbl/params.h
The first commit is a fix for #3940 by killing the child when it does not come up within the timeout.
The second commit adds a specific `start_timeout` parameter.
=> Avoid worker startup hang, add startup_timeout

bin/varnishd/cache/cache_pool.c, bin/varnishd/cache/cache_pool.h, bin/varnishd/cache/cache_wrk.c, bin/varnishtest/tests/c00124.vtc, lib/libvsc/VSC_main.vsc
I ran into a waiting list queuing case recently and the lack of consistent `sess_queued` was really getting in the way.
=> pool: Safely update pool statistics

bin/varnishd/cache/cache_backend_probe.c
Suppose the following happens:
`vbp_task()` finishes with `vt->running = 0` and a heap insert. The `vbp_cond` is signaled under the lock, but now instead of `vbp_thread()` waking up first, `VBP_Remove()` gets the lock and reaches `assert(vt->heap_idx == VBH_NOIDX);` before the racing `vbp_thread()` deleted the heap.
This is unlikely to happen with static backends, because for those, the probe is stopped via the vcl temperature before they get removed.
Fixes https://github.com/nigoroll/libvmod-dynamic/issues/100
=> Fix a race between VBP_Remove() and vbp_thread()

bin/varnishtest/tests/a00024.vtc, bin/varnishtest/tests/b00000.vtc, bin/varnishtest/tests/b00053.vtc, bin/varnishtest/tests/c00036.vtc, bin/varnishtest/tests/e00003.vtc, bin/varnishtest/tests/l00002.vtc, bin/varnishtest/tests/l00003.vtc, bin/varnishtest/tests/l00004.vtc, bin/varnishtest/tests/l00005.vtc, bin/varnishtest/tests/r00498.vtc, bin/varnishtest/tests/r01140.vtc, bin/varnishtest/tests/r01637.vtc, bin/varnishtest/tests/r02831.vtc, bin/varnishtest/tests/t02005.vtc, bin/varnishtest/tests/t02015.vtc, bin/varnishtest/tests/u00003.vtc, bin/varnishtest/tests/u00010.vtc, bin/varnishtest/tests/v00051.vtc, bin/varnishtest/tests/v00064.vtc, bin/varnishtest/vtc_http.c
As discussed on varnish-dev ML: https://varnish-cache.org/lists/pipermail/varnish-dev/2023-July/009755.html
This adds default "Server: sNAME" and "User-Agent: cNAME" headers to server `txresp` and client `txreq` respectively in vtc, with the ability to disable them with `-noserver` and `-nouseragent`. Also, both can be overridden with `-hdr`
=> Add default "Server" and "User-Agent" headers in vtc

bin/varnishd/cache/cache_ban_build.c, bin/varnishtest/tests/r03962.vtc, doc/changes.rst
=> Ban parser: don't accept object name prefixes

bin/varnishd/cache/cache_director.c, bin/varnishd/cache/cache_vcl.c, bin/varnishd/mgt/mgt_vcl.c, bin/varnishtest/tests/s00005.vtc, include/Makefile.am, include/vcli_serve.h, include/vte.h, lib/libvarnish/vcli_serve.c, lib/libvarnish/vte.c
Some work on the VTE was requested somewhere else, and it so happened to align with #3946 goals, although, this pull request is not moving anything to libvarnishapi.
The new VTE API is inspired by the VSB API and ultimately avoids one printf per character.
One thing I didn't attempt was to adopt the VTE for the `varnishstat -1` output.
=> vte: Provide a CLI-independent API

.circleci/config.yml, configure.ac, doc/changes.rst
=> Prepare for 7.4.1

lib/libvarnish/vsub.c
`close_range` is still a somewhat new function and its common that the userspace in a container is newer than the kernel.
This fixes https://github.com/varnishcache/varnish-cache/issues/3988
=> Loop over FDs if close_range fails.

bin/varnishd/http2/cache_http2.h, bin/varnishd/http2/cache_http2_proto.c, bin/varnishd/http2/cache_http2_session.c, bin/varnishtest/tests/r03996.vtc, include/tbl/h2_error.h, include/tbl/params.h, include/tbl/sess_close.h, lib/libvsc/VSC_main.vsc
This adds parameters ``h2_rst_allowance`` and ``h2_rst_allowance_period``, which govern the rate of which we allow clients to reset h/2 streams.
If the limit is exceeded the connection is closed.
The functionality is currently disabled by default (``h2_rst_allowance = 0``). This is the kind of mitigation that will always need refinement, so it might be hard to come up with a one-size-fits-all kind of default here. It needs to be generous enough to not impact regular traffic, while at the same time low enough to meaningfully mitigate malicious clients. We may come up with some sort of generous number here, and give a recommendation for users to tune this down if under attack.
Mitigates: #3996
=> h2: Add a rate limit facility for h/2 RST handling ("Rapid reset" mitigation)

bin/varnishd/cache/cache_transport.h, bin/varnishd/cache/cache_vrt_vcl.c, bin/varnishd/http2/cache_http2_session.c, bin/varnishtest/tests/t02014.vtc, bin/varnishtest/tests/t02025.vtc, doc/sphinx/reference/vsl.rst, include/tbl/feature_bits.h, include/tbl/params.h, include/tbl/req_flags.h, lib/libvsc/VSC_main.vsc
This is the main commit message:
> Once a client is reportedly gone, processing its VCL task(s) is just a
> waste of resources. The execution of client-facing VCL is intercepted
> and an artificial return(fail) is returned in that scenario.
> 
> Thanks to the introduction of the universal return(fail) proper error
> handling and resource tear down is already in place, which makes this
> change safe modulus unknown bugs. This adds a circuit breaker anywhere
> in the client state machine where there is VCL execution.
> 
> A new Reset time stamp is logged to convey when a task does not complete
> because the client is gone. This is a good complement to the walk away
> feature and its original circuit breaker for the waiting list, but this
> has not been integrated yet.
> 
> While the request …
=> vcl_vrt: Skip VCL execution if the client is gone

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_backend_probe.c, bin/varnishd/cache/cache_esi_deliver.c, bin/varnishd/cache/cache_shmlog.c, bin/varnishd/cache/cache_vrt_var.c, bin/varnishd/http2/cache_http2_hpack.c, bin/varnishd/http2/cache_http2_proto.c, bin/varnishtest/tests/a02027.vtc, bin/varnishtest/tests/e00003.vtc, bin/varnishtest/tests/v00068.vtc, bin/varnishtest/vtc_client.c, include/vus.h, lib/libvarnish/vus.c, lib/libvgz/deflate.c
This is a list of bug fixes candidates for a 7.3.1 release:
- #3908
- #3913
- #3914
Please note that only the first one was merged, we didn't get a chance to formally approve them during the last bugwash.
=> Collect bug fixes for 7.3.1

configure.ac, doc/changes.rst
=> Release 7.4.2

bin/varnishtest/vtc_varnish.c, configure.ac, doc/changes.rst
=> Release 7.3.1

configure.ac, doc/changes.rst, lib/libvarnish/version.c, lib/libvmod_h2/automake_boilerplate.am
=> Release 6.0.12

.circleci/config.yml
Remove stretch as it wont build unless we hack the build to replace sources files with archive-urls.
=> Remove stretch as its EOL

bin/varnishtest/tests/b00008.vtc, lib/libvarnish/vav.c
This PR  improves `vav_test` and fixes two issues in `VAV_ParseTxt`:
- `vav_test` was always returning 0, which makes it always pass make check. Failed tests as expected were not printed in the final report. And the test suite was aborting as soon as a single test would fail.
- `VAV_ParseTxt` was not correctly handling `"foo" "bar"` with no flags, and `"foo", "bar"` with the ARGV_COMMA flag.
=> vav: fix issues and improve tests

bin/varnishd/mgt/mgt_param.c, bin/varnishd/mgt/mgt_param_tweak.c, bin/varnishtest/tests/c00054.vtc, include/tbl/cli_cmds.h, include/tbl/params.h
With the introduction of `param.set -j` performing the regular `param.set` operation but outputting `param.show -j` we made it possible for "operators" to atomically set a parameter to a specific value, and know how it would be rendered. This enables safe periodic consistency checks to undo potential manual tweaks.
This change however, left a blind spot for bits parameters, since we either set them to their default value via the "none" or "default" special values, and otherwise with relative values in the form of a series of `-xxx` or `+yyy` tokens.
This patch series adds a new "all" value and allows "all" and "none" to appear in the bits list:
```
param.set foo none,+bar,+baz
```
It also changes the relative default values of some bits parameters to make them all absolute.
The "default" …
=> param: Enable absolute bits parameters

doc/sphinx/vtc-syntax.py
Since Python 3.12 unknown escape sequences trigger a warning.
---
Not expecting a review, I will merge this as soon as CI completes, unless there are failures.
=> doc: Use a raw string for regular expressions

bin/varnishd/http2/cache_http2.h, bin/varnishd/http2/cache_http2_hpack.c, bin/varnishd/http2/cache_http2_proto.c, bin/varnishtest/tests/t02026.vtc
The :scheme pseudo header is not optional in H/2 except when doing CONNECT. There is also a strict requirement for it appear only once.
Signed-off-by: Asad Sajjad Ahmed <asadsa@varnish-software.com>
Conflicts:
bin/varnishtest/tests/t02025.vtc
---
This was submitted to the 6.0 branch instead of trunk first. I noticed it thanks to the test case collision while porting #3998 to the 6.0 branch.
=> h2: the :scheme pseudo header is not optional

bin/varnishd/cache/cache_fetch.c, bin/varnishd/storage/storage_simple.c, bin/varnishtest/tests/b00062.vtc
(edit: Added a second commit which depends on the first)
TL;DR: Fix trimstore use in 304 and copy objects efficiently ("defragmented")
It is my understanding that the objtrimstore stevedore API function is only to be called once when the object is complete, which I believe is also in line with the comment on `ObjExtend()` that _The final flag must be set on the last call_.
If this understanding of the API is correct, we did not adhere to it in the fetch code when we made a copy of an existing stale object after a 304 response: There, we iterated over the stale object and did not set the final flag just once when the object was complete, but rather after each storage segment was copied.
This commit fixes this, adds some pedentry to the simple storage and extends b00062.vtc to test this …
=> Fix and optimize 304 object copying

bin/varnishd/cache/cache_req_fsm.c, bin/varnishtest/tests/t02025.vtc, doc/sphinx/reference/vsl.rst
The 503 synth and 500 minimal response status codes are too misleading in this context, where the failure is attributed to the client. Among existing 4XX status codes, this is the closest if we stretch the timeout definition to "didn't complete rapidly enough before the client went away".
=> req_fsm: Use status 408 for reset streams

bin/varnishd/cache/cache_req_fsm.c, bin/varnishtest/tests/t02025.vtc, doc/sphinx/reference/vsl.rst
The 503 synth and 500 minimal response status codes are too misleading in this context, where the failure is attributed to the client. Among existing 4XX status codes, this is the closest if we stretch the timeout definition to "didn't complete rapidly enough before the client went away".
Conflicts:
- bin/varnishd/cache/cache_req_fsm.c
There is no minimal 500 response on this branch.
=> req_fsm: Use status 408 for reset streams (6.0)

bin/varnishd/cache/cache_vcl.c, include/vrt.h
@delthas reported [an interesting issue with vmod_dynamic](https://github.com/nigoroll/libvmod-dynamic/issues/107): When the vmod receives a cold event, it might have some directors left to delete, and when it deletes them, they do not receive a cold event, and a follow up assertion triggers because a warm director is deleted.
I believe the root cause is actually a wrong ordering in Varnish-Cache:
[`vcldir_retire()`](https://github.com/varnishcache/varnish-cache/blob/7aeca4d632827e2db91bf63e67e4c61c9319d038/bin/varnishd/cache/cache_vrt_vcl.c#L257-L258) only sends a `VCL_EVENT_COLD` when the vcl is warm. In other words, it (rightly, IMHO) asserts that a COLD event (if any) has alrady been posted when a director is deleted on a COLD vcl.
Yet, when the director is deleted upon a COLD vmod …
=> Fix order of COLD events for directors vs. VCL (and VMODs, implicitly)

bin/varnishstat/varnishstat_curses.c
In interactive mode the description of the VSC currently highlighted is displayed at the bottom of the interface, except when the last VSC is highlighted.
=> varnishstat: Fix missing description of the last VSC

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_backend.c, bin/varnishd/cache/cache_req_fsm.c, bin/varnishd/cache/cache_vrt_var.c, bin/varnishd/http1/cache_http1.h, bin/varnishd/http1/cache_http1_pipe.c, bin/varnishtest/tests/s00013.vtc, doc/sphinx/reference/varnishd.rst, doc/sphinx/reference/vcl_var.rst, include/tbl/params.h
Followup from the last VDD, the idea of having deadlines was discussed.
This patch series fixes a bug, improves logging slightly, and introduces a new `deadline_pipe` parameter. It leaves `deadline_client` and `deadline_backend` for later as this is the simplest to implement among the three.
The parameter is disabled by default to match the current behavior.
=> param: New deadline_pipe parameter

bin/varnishd/http1/cache_http1_pipe.c, include/vtim.h, lib/libvarnish/vtcp.c, lib/libvarnish/vtim.c
The expectations on FreeBSD are stricter than on Linux.
=> v1p: Fix invalid poll() usage with a new VTIM_poll()

bin/varnishd/cache/cache_fetch_proc.c, bin/varnishd/cache/cache_obj.c, bin/varnishd/storage/storage_debug.c, bin/varnishd/storage/storage_simple.c
For chunked encoding, we do not know how big the object is ultimately going to be, so `VFP_GetStorage()` called `ObjGetSpace()` with the `fetch_chunksize` parameter in this case.
Yet which size is best might differ for different storage engines, and having the information that the caller does not know the final size might be relevant. Storage engines could guess that if a request came in for `fetch_chunksize` that this _might_ be the "chunked" case, but that heuristic would be wrong for Objects of just that size advertised via `Content-Length`.
So this patch takes the guesswork out of the game by just passing the magic 0 value down to the storage engine to mean "give me some good chunk of bytes, I do not know how much I am going to need".
---
For context: Over the past two years, this …
=> Move decision on fetch_chunksize to the storage engine

varnish.m4, wflags.py
The first commit I noticed there was a missing comma in wflags.py `UNDESIRABLE_WFLAGS`. The build system didn't seem to care either way but figured it was easy enough to update.
The second commit relates to the auto-generated `BUILD_VMOD_$NAME` helper generated by `VARNISH_VMOD()` in `configure.ac`. When a VMOD adds a CFLAG with `libvmod_$1_la_CFLAGS` the object name is no longer `vmod_$name.lo` but `$library-vmod_name.lo` this changes the build order such that the VCC autogenerated files would not be guaranteed to compile first causing compilation issues. Updating to the `$libvmod_$1_la_OBJECTS` fixes the build order by letting automake/tools figure out the right object name. It might add in more objects than really desired but it's probably better to have the VCC files always built …
=> Minor build fixes

bin/varnishd/http2/cache_http2_proto.c
When discussing #4055 during last bugwash, we realized that `busy_stats_rate` was only used in h1, which could potentially explain why enabling it did not fix the issue. This PR introduces the feature flag support in h2.
Refs #4055
=> h2: Add support for busy_stats_rate

bin/varnishd/cache/cache_vrt_priv.c, lib/libvcc/vcc_compile.c, lib/libvcc/vcc_compile.h, lib/libvcc/vcc_expr.c, lib/libvcc/vcc_xref.c
Description mostly identical to that of the second commit:
Before this change, we would call `VRT_priv_*` only once per subroutine, which can be *) a nice performance optimization, but leaves us with stale pointers after a rollback.
Rather than adding complications for the rollback case just to keep the option of the "per subroutine pointer cache", just retrieve a fresh priv pointer every time.
The other use of the per subroutine initialization was error handling, which needs additional code outside the function arguments, simply because a `return` statement is not possible within function arguments. We remove the requirement for error handling by making sure that `VRT_priv_{task,top}` always return a valid pointer: They now fall back to a heap allocation if the workspace is full, which …
=> Avoid stale PRIV_{TASK,TOP} pointers by calling VRT_priv_{task,top} for each such argument

bin/varnishd/cache/cache_esi_deliver.c, bin/varnishtest/tests/r03865.vtc
When we introduced checking ESI includes for status 200 or 204, we would only (potentially, depending on the `onerror` attribute and `esi_onerror_continue` parameter) abort ESI processing for includes with a non-zero length.
This patch makes behavior consistent to not depend on whether or not an include is empty.
Fixes #4070
=> Consistently abort ESI transactions also for empty includes

.circleci/config.yml
looks like the remote docker image we were using was ancient, that seems to have broken more recent builds, like `noble` and `arch`
=> [cci] add ubuntu:noble, fix arch

bin/varnishd/cache/cache_esi_deliver.c, bin/varnishtest/tests/e00035.vtc, bin/varnishtest/tests/r03241.vtc, bin/varnishtest/tests/r03865.vtc, bin/varnishtest/tests/r04053.vtc, doc/sphinx/users-guide/esi.rst
This is a partial revert of 582ded6a2d6ae1a4467b1eb500f2725b42888016 to restore the assumed onerror=continue behavior for ESI includes, unless the feature flag esi_include_onerror is raised.
The part of the change that considers all status codes besides 200 and 204 to be errors for ESI includes remains. A test case covers VCL's ability to "bless" error responses by overriding resp.status, allowing ESI delivery to continue on this criterion.
Fixes #4053
=> esi: Restore the original onerror behavior

include/vapi/vsl_int.h
`VSL_VERMASK` is used in `VSL_VER()` macro, which currently always returns 0
=> vcl_int.h: Fix VSL_VER macro

bin/varnishd/cache/cache_fetch.c, bin/varnishtest/tests/c00120.vtc
The log emitted for a bgfetch task when there are no available threads in the thread pools currently looks like this:
```
1004 Begin           b bereq 1003 bgfetch
1004 VCL_use         b vcl1
1004 BereqAcct       b 0 0 0 0 0 0
1004 End             b 
```
This PR makes it easier to understand what happened:
```
1004 Begin           b bereq 1003 bgfetch
1004 VCL_use         b vcl1
1004 FetchError      b No thread available for bgfetch
1004 BereqAcct       b 0 0 0 0 0 0
1004 End             b 
```
=> fetch: Log bgfetch_no_thread

.circleci/config.yml
Ubuntu noble tries to use `fchmodat2` (new syscall) and gets permission denied instead of ENOSYS. 
This is a small security risk but it's running inside of circleci containers anyway so i think its acceptable.
=> Run docker without seccomp rules.

bin/varnishd/cache/cache_expire.c, bin/varnishd/cache/cache_hash.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishtest/tests/m00057.vtc, bin/varnishtest/tests/m00058.vtc, vmod/vmod_purge.vcc
This PR resolves an issue where softpurging an object would reset its expiry timer to the start of the objects grace period. Repeated softpurges of the same object would keep it away from expiry indefinetly, and softpurging an object in keep would bring it back into grace. 
The effects of the current softpurge implementation are most severe when the cache contains a high number of objects that are regularly hit by key-based invalidation. This can result in a growing number of objects in cache, increasing load on the expiry thread mailbox, and contention on the `exp` mutex. Grace hits on stale objects long past their indended lifetime can also occur.
This patch series introduces `EXP_Reduce()` as an alternative to `EXP_Rearm()` for softpurging applications. `purge.soft()` has been changed …
=> expire: Add EXP_Reduce() for better softpurges

bin/varnishd/cache/cache_hash.c, bin/varnishtest/tests/c00132.vtc
The opposite of 'EXP_Ttl(req, oc) > req->t_req' should not have been 'EXP_Ttl(NULL, oc) < req->t_req'. If we somehow enter the lookup when the two operands are equal, the objcore suffers a phenomenon known as Schrödinger's expiry.
The chances of running into this scenario range from epsilon to 100%.
Because 't_req' is stable across restarts, a soft purge will reliably trigger this case.
Test case by @AlveElde who first demonstrated the problem.
=> hash: Close an expiry loophole

bin/varnishd/http2/cache_http2_session.c, bin/varnishtest/tests/t02001.vtc
`highest_stream` gets used both in transmitting goaway frames, and also for internal protocol consistency checks.
For the `Upgrade: h2c` handling we fail to bump this when kicking off the stream for the request that got the upgrade, so any subsequent frame transmitted on that stream will be treated with an inconsistent view on `highest_stream`. In particular, this leads to an erroneous `PROTOCOL_ERROR` on reception of a `WINDOW_UPDATE`.
=> h2: Ensure highest_stream is consistent also on Upgrade: h2c

configure.ac, lib/libvarnish/vfil.c
Eliminate autocrap checks and unused fall-back code paths.
=> All sensible platforms have <sys/statvfs.h> these days.

bin/varnishtest/tests/r02310.vtc
> The test is racy, since #3998 we no longer perform the backend fetch if the client disconnects before it is started. Thus, the test will be stuck at [this](https://github.com/varnishcache/varnish-cache/blob/5e98181a6180a50df0836539b2bc12b2264fb8fe/bin/varnishtest/tests/r02310.vtc#L37) line until it times out since the [other](https://github.com/varnishcache/varnish-cache/blob/5e98181a6180a50df0836539b2bc12b2264fb8fe/bin/varnishtest/tests/r02310.vtc#L7C2-L7C9) `barrier b1 sync` will never be reached.
Fixes: #4098
=> vtc: Stabilize r02310.vtc

bin/varnishadm/varnishadm.c, bin/varnishd/mgt/mgt_main.c, bin/varnishtest/tests/b00041.vtc, bin/varnishtest/tests/b00045.vtc, bin/varnishtest/tests/u00003.vtc, bin/varnishtest/tests/u00004.vtc, bin/varnishtest/tests/u00005.vtc, bin/varnishtest/tests/u00006.vtc, bin/varnishtest/tests/u00009.vtc, doc/changes.rst, lib/libvarnish/vin.c, lib/libvarnishapi/vsm.c, lib/libvarnishapi/vut.c
After 15 years of tirelessly repeating `-n <foo>` for <s>each and every</s> varnish admin command, I wonder: is it time to set defaults from environment variables?
This PR is not remotely complete. It is merely to ask about opinions.
=> Argument defaults from environment variables?

bin/varnishd/mgt/mgt_main.c, doc/changes.rst, doc/sphinx/reference/vmod.rst, vmod/vmod_debug.c
Processes created by the worker might require a `TMPDIR` for temporary files (think: filters). Create a dedicated directory for this purpose, which is otherwise hard to achieve in a universal manner.
=> Create a directory owned by the worker process for use as a TMPDIR

bin/varnishd/cache/cache_backend.c, doc/changes.rst, doc/sphinx/reference/vcl-backend.rst
Inherit the three backend timeouts from a proxy if not defined for the destination.
TODO before merge if otherwise accepted: changes.rst, documentation
=> Copy timeouts from a via backend if undefined for the destination

bin/varnishd/cache/cache_obj.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishd/storage/storage_simple.c, doc/changes.rst, include/vrt.h
For context see [SLASH/fellow issue #44](https://gitlab.com/uplex/varnish/slash/-/issues/44).
Clients to the Object API need to know not only the current extension (new length) of streaming objects, but also the streaming state - in particular `BOS_FINISHED` and `BOS_FAILED`. The latter for obvious reasons, and the former to call the delivery function with `OBJ_ITER_END`, which then likely results in `VDP_END` sent down the delivery pipeline.
Background:
It is important for efficient delivery to not receive an additional `VDP_END` with a null buffer, but rather combined with the last chunk of data, so, consequently, it is important to reliably send `OBJ_INTER_END` also with the last chunk of data.
Consequent to all of this, `ObjWaitExtend()` callers need to know when `BOS_FINISHED` has …
=> Add ObjWaitExtend2() to provide a consistent boc state

bin/varnishd/cache/cache_panic.c, include/Makefile.am, include/vbt.h, lib/libvarnish/Makefile.am, lib/libvarnish/vbt.c
This is an old patch series from more than a year ago that I mentioned briefly to @bsdphk back then. The idea was to move the back-trace rendering code to libvarnish and make the panic code use it.
We needed to print back-traces outside of `varnishd` to track down an alleged unknown bug in our `getaddrinfo()` usage, that would only happen under an unknown set of circumstances, but it turned out to be a silly overflow not reported as such by glibc.
In other words, it took us a back-trace to realize we were facing another incarnation of #3765 because 247eb50f47d4dae5eeacc54375eb3f2adde086a1 had not been back-ported to the 6.0 branch. Once the problem was solved the VBT code was forgotten until last Friday.
Apologies for the delay.
=> vbt: Move backtrace code to libvarnish

bin/varnishtest/Makefile.am, bin/varnishtest/cmds.h, bin/varnishtest/tests/a00025.vtc, bin/varnishtest/tests/c00123.vtc, bin/varnishtest/tests/u00008.vtc, bin/varnishtest/vtc_varnish.c, bin/varnishtest/vtc_vsm.c, doc/sphinx/Makefile.am, doc/sphinx/reference/vsm.rst, include/vapi/vsm.h, lib/libvarnishapi/vsm.c
From the main patch of the series:
> Roughly:
> 
> - index hash change means restarted
> - index new plus or minus means changed
> - reopening the index means restarted
> 
> This aligns with my POLA expectations, except for one we can do nothing about after the removal of SIGNULL liveness checks.
> 
> Refs b845c2789cae4f165e30a3d0f3af1bfbbeca98ee
I wasted a fair amount of time trying to get transaction logs from a VTC involving a restart of the cache process. Ever since we stopped sending `SIGNULL` the cache process became virtually always running once started for the first time. Especially since `vtc_varnish` would only check the `VSM_WRK_RUNNING` flag.
Between a probable copy-pasta mistake and alleged logic errors, the `VSM_WRK_CHANGED` flag was effectively dead.
It turned out to be …
=> vsm: Drastically refine status checks

.circleci/Dockerfile, .circleci/config.yml, .circleci/make-rpm-packages.sh, bin/varnishtest/tests/b00058.vtc, bin/varnishtest/tests/p00000.vtc, bin/varnishtest/tests/s00003.vtc
We retire:
- centos:7
- debian:buster (10)
This is not trivial because centos:7 is the base image of many jobs.
=> circleci: Retire EOL platforms

lib/libvarnishapi/vsc.c
This is a change implemented mostly by @mbgrydeland in the first commit:
> This patch polishes and fixes up the VSC parts of libvarnishapi. Main
> points are:
> 
> 1) The merging of the VSM list and the VSC segment list is done in a
> separate loop from where the callbacks are executed. This prevents a
> VSM_Status() being executed in a callback from interfering with the update
> of the VSC segment list to match the VSM list.
> 
> 2) Failures to map counters does not remove the counter from the VSC seg
> list. Previously we would remove VSC seg list elements on map failures,
> but doing so would then cause issues when attempting to consolidate the
> VSM list and the VSC seg list on the next call to VSC_Iter(). With this
> patch, map failures are recorded as a state without removing the …
=> vsc: Revamp vsc.c and VSC_Iter()

bin/varnishd/cache/cache_session.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishd/cache/cache_ws.c, bin/varnishd/cache/cache_ws_emu.c, bin/varnishd/http2/cache_http2.h, bin/varnishd/http2/cache_http2_hpack.c, bin/varnishd/http2/cache_http2_proto.c
Originally from #4125, submitted independently as per bugwash to reduce the size of #4125.
=> ws: Prep work for trailers support

bin/varnishd/cache/cache_backend_probe.c, doc/graphviz/cache_backend_probe.dot
I will be away until July, but I would appreciate reviews and collection of feedback in the meantime. Also, for the unlikely event that everyone is absolutely happy about it, I would also not oppose a merge.
----
Every time I looked at the probe code in the past, my mind ended up twisted and confused. A probe could change the "enabled" state (tracking the temperature) or be removed at any time (unless the `mtx` is held), yet the code did not seem to reflect this.
We un-twist my mind by implementing probe states:
* `cold`: reflects cold backend temperature
* `scheduled`: probe is on binheap, waiting for its time to come
* `running`: a task has been started to run the probe
* `cooling`: running probe disabled
* `deleted`: running probe removed (while `cooling` only)
With this new scheme, we …
=> vbp: Rework probe state management

bin/varnishd/cache/cache_fetch.c, bin/varnishd/storage/storage_simple.c
By the same argument as #4056, storage engines might be able to make a better decision on the layout of object bodies if they know the expected length upfront, thus the transit buffer limit should be implemented at the storage layer.
This is also in line with the "other end" of the transit buffer, the "free behind" from the client side, being implemented in the object iterator.
=> Move implementation of transit_buffer to the storage engine

bin/varnishd/http2/cache_http2.h, bin/varnishd/http2/cache_http2_hpack.c, bin/varnishd/http2/cache_http2_proto.c, bin/varnishd/http2/cache_http2_send.c, bin/varnishd/http2/cache_http2_session.c
Currently, some of the logging to the H2 session vsl is done withouth holding the session lock, even when multiple streams are active. This PR is an attempt to make things more consistent in that regard.
=> Consistent locking when logging to H2 session vsl

bin/varnishhist/varnishhist_options.h
#3468 changed the flags to mention `(E)SI` but didn't update the short bits...
I ran across this while working on a spell checking pass for this repository. It seemed worth peeling this out.
=> varnishhist: fix help for -P to mention E

bin/varnishd/cache/cache_fetch.c, bin/varnishd/cache/cache_req_body.c, bin/varnishd/cache/cache_req_fsm.c, bin/varnishd/http1/cache_http1_fetch.c, bin/varnishtest/tests/c00055.vtc, include/tbl/body_status.h, include/tbl/req_flags.h
This PR is to revert commits which I think are going in the wrong direction. The issues raised here have become apparent when rebasing #4035 where we actually do things with request bodies and, for the first time, add some more interesting test coverage.
So what is wrong with these changes?
`BS_TAKEN` and `BS_CACHED` are exactly _not_ properties of the request, but of the request body. It can be processed on the client side, or backend side, or both, so the backend side needs to know the status, and going through `bo->req` is a bad idea long term, because we might want to decouple client and backend request more. Needless to say this also adds to complexity, because besides the request body status, also the request flags would need to be checked.
`BS_TAKEN` is important, because a request …
=> Don't go the wrong way with request bodies

bin/varnishd/Makefile.am, bin/varnishd/mgt/mgt.h, bin/varnishd/mgt/mgt_jail.c, bin/varnishd/mgt/mgt_jail_linux.c, bin/varnishd/mgt/mgt_jail_unix.c, bin/varnishd/mgt/mgt_main.c, doc/sphinx/reference/varnishd.rst
The idea for this PR originates [here](https://github.com/varnishcache/varnish-cache/pull/4123)
It introduces a Linux jail which overloads the UNIX one
It currently only re enables core dumps after playing with uid/gid and outputs some logs when the working directory is not on a tmpfs partition
=> Introduce a Linux jail

bin/varnishd/http2/cache_http2_proto.c, bin/varnishd/http2/cache_http2_send.c, include/tbl/h2_frames.h
In many situations, we just close the h2 session with no information about what was the reason for that. This adds some logging that can be very helpful for debugging.
=> H2: Improve logging for connection level errors

bin/varnishd/builtin.vcl, bin/varnishtest/tests/c00034.vtc
Since 4ab110047130e3a89936104d74f4729b650676f9 (see also #3246), we fail backend responses with an unexpected `Content-Range`.
Yet [RFC9110](https://www.rfc-editor.org/rfc/rfc9110.html#section-14.4) states:
> The Content-Range header field has no meaning for status codes that do not explicitly describe its semantic.
The semantic is described for status codes 206 and 416, so the obvious implementation change would be for core code to only consider `Content-Range` for these status codes.
But there might be scenarios where a stricter-than-RFC check is intended, so we keep that in core code and change `builtin.vcl` to remove the header where it has no semantic.
=> builtin.vcl: Delete Content-Range header where it has no meaning

bin/varnishtest/tests/v00019.vtc, lib/libvcc/vcc_expr.c, vmod/vmod_debug.c, vmod/vmod_debug.vcc
I do not consider myself enough of an expert on VCC and would appreciate reviews by those who do.
Side note: STRING vs STRINGS vs. STRANDS is confusing
Fixes #4146
=> libvcc: Fix STRING/STRANDS comparison without STRING folding

m4/ax_pthread.m4
Split from https://github.com/varnishcache/varnish-cache/pull/4153/commits/a0a9a044b3de44fc54301a5064fe145d5af0e2c2
=> chore(m4): spelling: reentrant

bin/varnishd/common/common_vsmw.c
Trivial follow-up to #4141 : We should notify users if we can not `mlock()` VSM.
Related to #4121
=> Emit a warning if mlock() of VSM fails

bin/varnishd/cache/cache_backend.c, bin/varnishd/cache/cache_backend_probe.c, bin/varnishd/cache/cache_director.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishtest/tests/v00074.vtc
This is a followup for #4030, it adds an optimization to purge the backend wait queue when the backend becomes sick.
Three possible transitions trigger this:
- Admin health is set to sick.
- Probe health goes sick when admin health is auto.
- Admin health is set to auto and current probe state is sick.
=> Backend: Wakeup clients on waitqueue when BE goes sick

bin/varnishd/mgt/mgt_acceptor.c, bin/varnishtest/tests/b00085.vtc, bin/varnishtest/tests/c00121.vtc, doc/sphinx/reference/varnishd.rst, include/vss.h, lib/libvarnish/vss.c, vmod/vmod_debug.c, vmod/vmod_debug.vcc
This PR extends the syntax of the varnishd `-a` argument to support port ranges. The range is inclusive, and failing to bind to any port in the range will terminate startup. This change should not affect any existing setup.
=> -a port ranges

bin/varnishd/cache/cache_session.c, bin/varnishd/waiter/cache_waiter.c, bin/varnishd/waiter/cache_waiter_epoll.c, bin/varnishd/waiter/cache_waiter_kqueue.c, bin/varnishd/waiter/waiter.h, bin/varnishd/waiter/waiter_priv.h, bin/varnishtest/tests/b00086.vtc, bin/varnishtest/tests/b00087.vtc, bin/varnishtest/tests/b00088.vtc, bin/varnishtest/vtc_http.c, lib/libvsc/Makefile.am, lib/libvsc/VSC_waiter.vsc
There seems to be a discrepancy between the epoll and kqueue
implementation. One implementation is not reporting WAITER_REMCLOSE,
while the other implementation is reporting WAITER_REMCLOSE too soon.
epoll:
We sometimes incorrectly report WAITER_ACTION when it is supposed to be
WAITER_REMCLOSE. We can check EPOLLRDHUP before reading 1 byte with MSG_PEEK to
detect WAITER_REMCLOSE. This saves us from a pontential session detour from the
Waiter to a worker thread.
kqueue:
We incorrectly report WAITER_REMCLOSE when there could be more data to be
read from the socket. Change this so that we perform read of 1 byte with
MSG_PEEK to detect closure when EV_EOF is set.
DESCRIPTION:EVFILT_READ:Sockets:
> It is possible for EOF to be  returned (indicating the connection is gone)
> while there is …
=> waiter: report WAITER_REMCLOSE correctly

bin/varnishd/cache/cache_deliver_proc.c, bin/varnishd/cache/cache_esi_deliver.c, bin/varnishd/cache/cache_filter.h, bin/varnishd/cache/cache_gzip.c, bin/varnishd/cache/cache_range.c, bin/varnishd/cache/cache_req_fsm.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishd/cache/cache_vrt_filter.c, bin/varnishd/http2/cache_http2_deliver.c, vmod/vmod_debug.c
This commit is to prepare use of the VDP API also for the backend side to filter bereq.body through bereq.filters by putting all pointers _intended_ to be used by a VDP init function into vdp_ctx.
For background, see #4035
=> Generalize the VDP API: all in vdp_ctx

.github/workflows/cifuzz.yml
V1 and V2 of the upload-artifact action are now [deprecated](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/), this PR sets it to V4
=> cifuzz: Update upload action to v4

bin/varnishtest/tests/v00018.vtc, lib/libvcc/vcc_action.c
=> vcc_action: Accept strings returned by vmods for return(fail())

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_deliver_proc.c, bin/varnishd/cache/cache_hash.c, bin/varnishd/cache/cache_obj.c
To avoid repetition and mistakes, and in order to clarify the meaning of certain conditions, a new OC_F_TRANSIENT pseudo-flag is introduced. This was prompted by an incoming change to transit buffer where identifying transient delivery requires again to check the same set of flags.
=> obj: List transient flags in a single place

lib/libvcc/vmodtool.py
Python does not like having `\` characters followed by non-special characters, e.g. `\.` - but regex requires that. For this, python has "raw strings", e.g. `r'....'` - this way no `\` have any special meaning to python, only to the regex itself.  At least on my 3.12 Python it refused to work without it.  In general, it is a good practice to always use r-strings with regex.
=> Minor r'str' fix to vmodtool.py

bin/varnishd/cache/cache_backend.c, bin/varnishtest/tests/b00089.vtc, bin/varnishtest/tests/b00090.vtc
There is a race between the time we connect to a backend and when we increase
the connection count. This race is not normally observed, but when
.max_connections property is used we could end up creating more connections to
the backend than this limit permits. This is problematic as we end up consuming
more system resources, e.g., file-descriptors, than reserved for such backends.
The problem is that we release the backend lock and wait for the connect
to finish. This can take upto connect_timeout, which has a default timeout of
3.5 seconds, and only then do we count the connection as consumed towards the
.max_connections property.
This can create a recipe for bursty behavior where a backend already
struggling could be overwhelmed by a significant number of connections. Then,
as the …
=> backend: increase connection count before connect

bin/varnishtest/tests/e00016.vtc, bin/varnishtest/tests/e00029.vtc, bin/varnishtest/tests/e00030.vtc, bin/varnishtest/tests/e00034.vtc, bin/varnishtest/tests/l00003.vtc, bin/varnishtest/tests/r01737.vtc, bin/varnishtest/tests/r01781.vtc, bin/varnishtest/tests/r01878.vtc, bin/varnishtest/tests/r02849.vtc, bin/varnishtest/tests/v00042.vtc, bin/varnishtest/tests/v00043.vtc
The former threadpool size of 80k fails on 32bit ppc (at least on my Debian/ppc32)
**** v1    CLI TX|param.set thread_pool_stack 80k
**** dT    0.197
***  v1    CLI RX  106
**** v1    CLI RX|Must be at least 128k
Upping to 128k makes the test suite run.
=> tests get larger thread pool, necessary for ppc32

bin/varnishtest/tests/c00042.vtc, lib/libvcc/vcc_backend.c, lib/libvcc/vcc_compile.h, lib/libvcc/vcc_expr.c, lib/libvcc/vcc_symb.c, lib/libvcc/vcc_types.c
A new DEFAULT type identifies symbols called 'default' and types that can have a default symbol carry a pseudo symbol. This approach can reconcile the overloaded default symbols that all share the generic type DEFAULT but carry their respective kinds.
This helps remove some of the special casing for default probes and backends whilst offering a sentinel DEFAULT type to safely deal with the special casing where it is actually needed, simplifying the code a wee bit in those areas.
Fixes #4177
=> vcc: Internal type for the reserved 'default' symbol

bin/varnishd/cache/cache_backend.c, bin/varnishtest/tests/b00091.vtc
since DNS resolution happens only once for static backends and can be a bit obscure for dynamic backend, it's valuable to be able to dump the IPs that are used.
In order to not break existing scripts which may `varnishadm backend.list`, only update the JSON ouput
side note: it's a bit confusing that `vbe_list` needs to produce a JSON value ending with a coma if `pflag` is true, but not if it's false. Do we want to change that? And also maybe make printing the `probe_details` and `probe_message` a responsibilty of the backend implementation, rather than splitting the key-value pair across two functions?
=> backend.list -j now outputs IPs/port information

bin/varnishd/cache/cache_backend.c, bin/varnishd/cache/cache_backend_probe.c, bin/varnishd/cache/cache_director.c, bin/varnishd/cache/cache_varnishd.h, include/vrt.h
Alternative implementation to #4186 as suggested by dridi and phk:
This patch adds an event to the existing event facility, which so far was only used for VCL-related events. We now add `VDI_EVENT_SICK` as a director-specific event, which is cheap and also helps us maintain clean layering.
The new event is posted when the admin health changes and used by VBE to cancel all waiting connection requests.
=> Add VDI_EVENT_SICK and use it for admin health changes

bin/varnishd/mgt/mgt_cli.c, bin/varnishd/mgt/mgt_main.c, bin/varnishd/mgt/mgt_vcl.c, include/vev.h, lib/libvarnish/vev.c
This PR makes MGT log from which PID originates the signal it received.
It does that by adding the SIGINFO flag to sigaction in order to use `sa_sigaction` insead of `sa_handler` and grab the `struct siginfo_t` which contains the origin PID
=> vev: Log where MGT received its signal from

bin/varnishd/storage/storage_simple.c
Previously, `sml_iterator()` could not free the last segment while iterating, because it could have turned out to be over-allocated at any time and be removed.
We now delay freeing any over-allocated segments, identical to how we delay any reallocated segments, which enables us to "free behind" all sent segments.
This is relevant because, due to of the race between the fetch and iterator side of a transient operation, the "is last segment" condition can happen repeatedly while an object is busy.
=> sml: Optimize freebehind (transient) memory usage

bin/varnishd/cache/cache_main.c
On Linux, threads can not have name longer than 15 bytes plus a terminating '\0' byte:
> PR_SET_NAME (since Linux 2.6.9)
>     Set the name of the calling thread, using the value in the loca‐
>     tion  pointed  to  by  (char  *) arg2.  The name can be up to 16
>     bytes long, including the terminating null byte.  (If the length
>     of  the  string, including the terminating null byte, exceeds 16
>     bytes, the string is silently truncated.)  This is the same  at‐
>     tribute  that can be set via pthread_setname_np(3) and retrieved
>     using pthread_getname_np(3).  The attribute is likewise accessi‐
>     ble via /proc/self/task/tid/comm (see proc(5)), where tid is the
>     thread ID of the calling thread, as returned by gettid(2).
We have until now ignored the return value …
=> varnishd: truncate thread name on Linux

doc/sphinx/users-guide/vcl-grace.rst
`sub vcl_recv` does not have `return (lookup)`
=> Minor doc fix

doc/sphinx/conf.py.in
This commit mirrors https://github.com/varnishcache/homepage/commit/0f25620719c3568e166b9beff5c2c176236bf29a
as of today, each page redendered from the sphinx source contains the line
© Copyright 2010-2014, Varnish Software AS.
While this is true for some of the content, it is not for all of it and because we, several people from UPLEX, intend to contribute significant amounts of documentation in the near future, we would like to change this into something more generic, without the need to state specific copyright and authorship on each page.
=> Generic Copyright

.circleci/config.yml
Brought to my attention by @walid-git.
=> circleci: Fix group install on Fedora 41 with dnf5

bin/varnishd/cache/cache_backend.c, bin/varnishd/cache/cache_backend_probe.c, bin/varnishd/cache/cache_director.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishd/common/common_vsmw.c, bin/varnishd/mgt/mgt_main.c, bin/varnishd/waiter/cache_waiter_epoll.c, bin/varnishtest/tests/b00089.vtc, bin/varnishtest/tests/b00090.vtc, bin/varnishtest/tests/v00074.vtc, doc/sphinx/reference/vsm.rst, include/vrt.h, lib/libvarnishapi/vsm.c
This is a set of backports in preparation for the 7.6.1 release.
Refs: #4195
=> Backport series for 7.6.1

configure.ac, doc/changes.rst
=> Prepare for 7.6.1

lib/libvarnish/vsha256.c
to avoid errors and confusion as documented in #4226
=> vsha256: Insist that our byte order macros are defined

lib/libvarnish/vsha256.c
Since 5a60b36fe9b45b68244596d93db2b922d53e7b5c varnish drop support of sys/endian.h and they had a bit different API one or two leading `_`.
Some system may have symlink from endian.h to sys/endian.h, for example OpenBSD. On such system build fails due to wrong SHA256 hash.
=> Tolerate when endian.h is symlink to sys/endian.h

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_esi_deliver.c, bin/varnishd/cache/cache_req_fsm.c, bin/varnishd/cache/cache_transport.h, bin/varnishd/http1/cache_http1.h, bin/varnishd/http1/cache_http1_deliver.c, bin/varnishd/http2/cache_http2_deliver.c, bin/varnishtest/tests/m00060.vtc, vmod/automake_boilerplate_debug.am, vmod/vmod_debug.c, vmod/vmod_debug.h, vmod/vmod_debug.vcc, vmod/vmod_debug_transports.c
This is the next chapter of the book of AI, see #4209
To eventually get to event driven, asynchronous IO where a smaller number of threads handles a large number of requests, we also need a way to disembark a request from a worker and have another thread pick up where it left of, then reentering the state machine later to finish off.
Thanks to the already existing disembark facility used for waitinglist wakeups, implementing this is pretty straight forward: We basically only need to allow the vtr_deliver_f (transport deliver function) to tell the state engine to disembark, add a "finish" state, and everything else more or less works out of the box.
The last commit has a demonstration in a test case.
Everything else in this patch is refactoring.
=> Transport disembark

bin/varnishd/cache/cache_backend.c
There is a fundamental concurrency issue with the backend connection wait queue implementation.
With the current implementation, when there are items on the waiting queue, every in-progress backend request that complete signals the request at the head of the waiting queue to notify it that should resume obtaining a connection.  
However the current implementation assumes this means that if N in-progress requests complete then N waiting requests will be notified - but this is not the case.  This is because multiple in-progress requests can all complete simultaneously and all signal the same waiting request - the current head of the waiting queue.  Eventually that thread will obtain the lock and continue, however it reduces the maximum concurrency through the backend as N requests completed …
=> fix: always wake the new head of the waiting queue when there is available connections

bin/varnishd/http2/cache_http2_proto.c, bin/varnishd/http2/cache_http2_session.c
Two minor fixes, see commit logs for details.
=> H2 minor fixes

doc/sphinx/installation/install_source.rst
building Varnish Cache on a brand new Mac will fail with a weird Syntax error in configure unless Sphinx and doctools are in PATH. :-/
=> build breaks without sphinx and doctools on macos

.gitignore, bin/varnishd/cache/cache_vrt_vmod.c, doc/changes.rst, doc/sphinx/reference/vmod.rst, include/vrt.h, lib/libvcc/vmodtool.py, vmod/Makefile.am
This commit adds a facility which I had wanted for a very long time, and should have added much earlier: Analyzing bug reports with VMODs involved used to be complicated by the fact that they typically did not contain reliable version information.
We add to vmodtool.py the generic code to create version information from generate.py with minor modifications. It adds the version set for autotools and, if possible, the git revision to the vmodtool-generated interface code. We copy that to struct vrt and output it for panics.
Being at it, we polish the panic output slightly for readability.
As an example, the output from a panic now might look like this:
```perl
vmods = {
curl = {p=0x7ff9e064a230, abi="Varnish trunk 403a4743751bb6ae81abfb185abae13419ee0fb7", vrt=18.1,
version="libvmod-curl …
```
=> Add VMOD version information to Panic output

bin/varnishncsa/varnishncsa.c, bin/varnishtest/tests/u00020.vtc, doc/sphinx/reference/varnishncsa.rst
This PR introduces the changes discussed in https://github.com/varnishcache/varnish-cache/issues/3528
The relevant parts of [BE]requests/responses are now shown as they were received/sent from/to the peer, without taking irrelevant VCL changes into account. This PR also introduces the handling of Unset headers in varnishncsa.
Note: this breaks the default behavior of varnishncsa.
Fixes #3528.
=> Varnisncsa: Change matching rules to reflect reality

bin/varnishd/cache/cache_hash.c, bin/varnishtest/tests/c00133.vtc, bin/varnishtest/tests/c00134.vtc, doc/sphinx/users-guide/purging.rst, include/tbl/params.h
This is an implementation of the solution suggested by @bsdphk in https://github.com/varnishcache/varnish-cache/pull/4236#issuecomment-2511729813
It adds a parameter to limit the number of possibly non matching variants that we evaluate against the ban list during a lookup.
Leaving this as a draft until we agree on the parameter name.
Refs: #4236
=> HSH: Limit the number of non matching variants evaluated against the ban list during lookup

bin/varnishd/cache/cache_director.h, bin/varnishd/cache/cache_vcl.c, bin/varnishd/cache/cache_vcl.h, bin/varnishd/cache/cache_vrt_vcl.c
Pondering #4140 made me realize that our central per-vcl director list constitutes a classic case of iterating a mutable list. That besides the already known fact that running potentially expensive iterator functions while holding the vcl_mtx is a very bad idea.
So this patch is a suggestion on how to get out of this situation. It does not go all the way (it still leaves unsolved a similar problem of iterating over all backends of _all vcls_), but shows an attempt on how to tackle the "iterate over one VCL's backends".
We add a fittingly named 'vdire' facility which manages the director list and, in particular, director retirement. The main change is that, while iterators are active on the director list, vcl_mtx is _not_ held and any request of a director to retire only ends up in a …
=> Add a facility for unlocked director iteration

bin/varnishd/storage/storage_simple.c, bin/varnishd/storage/storage_simple.h
Make sure that we do not confuse buffers with object data.
The flags field comes at no extra memory cost on 64bit. For 32bit, this change breaks binary compatibility with any out-of-tree storages using storage_simple.
=> storage_simple: mark buffers

bin/varnishd/common/common_param.h, bin/varnishd/http1/cache_http1_fsm.c, bin/varnishd/mgt/mgt_param.h, bin/varnishd/mgt/mgt_param_tweak.c, bin/varnishtest/tests/c00039.vtc, include/tbl/params.h
Resolves https://github.com/varnishcache/varnish-cache/issues/2735
Before this PR, Varnish would silently close the connection to a client that triggered an RX_OVERFLOW (too long URI), this PR allows configuring Varnish to respond to RX_OVERFLOW with a minimal HTTP response that will contain a chosen HTTP code instead.
Its done by adding a new feature flag in order to enable the feature and a new parameter in order to set the HTTP code that will be sent in the response.
=> Return HTTP response to RX_OVERFLOW

bin/varnishd/cache/cache_req.c, bin/varnishd/mgt/mgt_main.c, bin/varnishtest/tests/e00029.vtc, bin/varnishtest/vtc.c
Fix up some issues when configuring varnish with ASAN, UBSAN and workspace emulator on Ubuntu22. I tested locally, with all tests passing, on Bookworm as well since that is what CCI uses for the SAN builds. 
1. 109543e87fbfbda0f9dc1fb5397327f6000de277- Initialize the VDP CTX in `Req_new()`. I think just using INIT_OBJ is okay here and aligns with the rest of the structs initialized in this section.
2. 6ea6c934ae1c69ef2b5bf867e4709b66bacd540f- Increase `thread_pool_stack` in  e29.vtc. Without the increase the test would segfault on Ubuntu 22.
3. 569c68a8630f38431b6394be1e738ba4391bea1b - Free value created from `create_bogo_n_arg()`. Let me know if there is a more desired way to structure the temporary value to free. 
Ubsan error from `Req_new()`:
```
In function ‘memset’,
inlined from …
```
=> SAN fixes on Ubuntu 22

bin/varnishhist/varnishhist.c, bin/varnishstat/varnishstat_curses.c, bin/varnishtop/varnishtop.c, tools/coccinelle/curses.cocci
This patch continues prior work to gain clarity about which curses functions are expected to fail (and why) and which are not. It is particularly interesting to test this on non-Linux OSes before merging, but ultimately, to de-fuse the assertions, we only need to flip a single 1 into a 0 in `vcurses.h`.
The only relevant change in this patch is the [curses.cocci](https://github.com/varnishcache/varnish-cache/blob/862b29557e1206a41593bfa24ac1a425ba7d71f5/tools/coccinelle/curses.cocci) file. All other changes are just the result of applying that patch, with additional manual polishing where coccinelle caused unwanted cstyle changes.
We explicitly ignore the return value of some curses functions through the IC() macro:
* curs_set is known to be ok to fail for terminals which do have no …
=> vcurses: add return value assertions using a semantic patch

bin/varnishtest/tests/c00042.vtc, doc/sphinx/reference/vcl-backend.rst, lib/libvcc/vcc_backend.c
Second half of the fix for #3963:
So far, we deliberately allowed IP addresses in the `.authority` field of backends, which might be derived from `.host_header` or `.host`.
There is a fair argument in #3963 that this should not be allowed.
This patch adds a `getaddrinfo()` call via `VSS_ResolveOne()` to check if the value parses as an ip address and, if so, fails VCL compilation.
=> vcc_backend: Forbid ip addresses as .authority with .via

bin/varnishd/acceptor/mgt_acceptor_uds.c, bin/varnishd/mgt/mgt.h, bin/varnishd/mgt/mgt_jail_solaris.c, bin/varnishd/mgt/mgt_jail_unix.c
@dridi I would use this in place of #4202. Do you agree?
This is a Draft because I still want to look if we can replace other similar cases and probably move the helper function to a better place as a `static inline` [^1]
----
we add a simple utility function to return the pointer to the thing after "key=" if the first argument begins with "key=".
Note that this is no worse than a macro with a "reasonable good" compiler *) and default (-O2) optimization, because the function call gets inlined and the strlen() turned into a constant.
```
0x00000000000a1bd1 <+49>:     lea    0x6ed49(%rip),%r14        # 0x110921
...
0x00000000000a1c01 <+97>:    mov    $0x5,%edx
0x00000000000a1c06 <+102>:   mov    %rbx,%rdi
0x00000000000a1c09 <+105>:   mov    %r14,%rsi
0x00000000000a1c0c <+108>:   call …
```
=> Simplify key=val argument handling

bin/varnishd/cache/cache_fetch.c, include/tbl/body_status.h
This reverts commit 8c4ae4f0e1c1990a48884b36e2b3e9acc8d162a1.
I dispute the claim from the revert commit that bo->htc->body_status
refers to the bereq, since this is managed by the V1F (HTTP/1 Fetch)
code. What we fetch on the backend side is a beresp.
=> Reapply "fetch: A beresp body cannot be BS_TAKEN"

bin/varnishtest/tests/c00053.vtc, doc/sphinx/reference/vcl.rst, include/tbl/params.h, lib/libvcc/vcc_source.c
This is a replacement for https://github.com/varnishcache/varnish-cache/pull/4250, where [it appeared](https://github.com/varnishcache/varnish-cache/pull/4250#issuecomment-2575730478) that finding an unambiguous and easy to predict behavior when using `+glob` includes with relative paths involving `vcl_path` was not an easy task.
After some discussions, the consensus was that relative paths should not be allowed when using `+glob` includes.
Refs #4250
Closes #4249
=> VCC: Prohibit the use of relative paths with +glob

bin/varnishd/acceptor/cache_acceptor_tcp.c, bin/varnishd/acceptor/cache_acceptor_uds.c, bin/varnishd/cache/cache_esi_deliver.c, bin/varnishd/cache/cache_req.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishd/http1/cache_http1_fsm.c, bin/varnishd/http2/cache_http2_proto.c, bin/varnishd/http2/cache_http2_session.c
This patch avoids allocating a superfluous `struct reqtop` for ESI subrequests.
From a discussion here:
https://github.com/varnishcache/varnish-cache/pull/4269#issuecomment-2654577140
=> cache_req: Allocate topreq only if needed

bin/varnishd/mgt/mgt_param_tweak.c, bin/varnishtest/tests/c00054.vtc
This enables:
- `param.set debug all`
- `param.set experimental all`
- `param.set feature all`
- `param.set vsl_mask none`
Based on an incomplete patch from @nigoroll.
=> param: Cut all (or none of the) loose ends for bits parameters

bin/varnishncsa/varnishncsa.c, bin/varnishtest/tests/u00002.vtc, doc/changes.rst, doc/sphinx/reference/varnishncsa.rst
The title should say it all. Simple straight forward extension of the handling strings.
@martin-uplex
=> varnishncsa: Add hitmiss hitpass indicators to Varnish:handling

bin/varnishd/http2/cache_http2.h, bin/varnishd/http2/cache_http2_proto.c, doc/changes.rst
A newly created request's `t_first` is now when the first (partial) read of the `HEADERS` frame is complete.
`t_req` is now when all headers are complete.
This should match http1 more closely
Implements #4282
Alternatives considered: Add the timestamp as a field to `struct h2_sess`. I did not like growing this big structure even more.
=> http2: Improve timestamps

bin/varnishd/http2/cache_http2_proto.c, bin/varnishtest/tests/t02027.vtc
It is fine for a client to close the connection, we should say a friendly goodbye and log this as no error.
Closes #4281
Related to #4283
=> http2: The client closing the connection is not an error

doc/sphinx/phk/notes.rst
When I read the excellent notes, I noticed the double 'if'.
=> remove redundant 'if'

bin/varnishd/cache/cache_req_fsm.c, bin/varnishtest/tests/b00037.vtc, configure.ac, doc/changes.rst, doc/sphinx/index.rst, lib/libvarnish/version.c
=> Prepare for 7.6.2

bin/varnishd/cache/cache_conn_pool.c, bin/varnishtest/tests/b00093.vtc, lib/libvsc/Makefile.am, lib/libvsc/VSC_vcp.vsc
Add counter for the Connection Pool.
Initially start out with just 2 counters:
> VCP.ref_hit                                   0         0.00 Number of times we have found an existing conn. pool
> VCP.ref_miss                                  1         0.10 Number of times we have not found an existing conn. pool
Fixes: #4311
=> vcp: add counters

bin/varnishd/cache/cache_esi_fetch.c, bin/varnishd/cache/cache_gzip.c, bin/varnishd/cache/cache_vgz.h, include/tbl/params.h
Arbitrary allocation from storage was introduced to solve the h2
head-of-line blocking caused by early DATA frames, allowed by the
initial control flow window of new streams. The decision could have
been made then to allocate the window buffer from the heap, but it
was tied to storage instead, offering better control over the global
memory footprint of the cache process.
The gzip buffer is tied to a task, but too large to allocate from
workspace without posing a risk. Even worse, there may be multiple
concurrent gzip operations in a single task. For example a gunzip
needed to parse ESI followed by a gzip to store a compressed body.
For a similar reason, it was not opportune to allocate the h2 stream
window buffer from workspace, despite being tied to the task.
Following the same logic, …
=> gzip: Allocate gzip buffers from storage

bin/varnishd/Makefile.am, bin/varnishd/cache/cache_ban.c, bin/varnishd/cache/cache_ban.h, bin/varnishd/cache/cache_ban_idx.c
When loading a cache with a relevant number of BANs from a persistent storage, `BAN_FindBan()` needs to called for every object to determine the struct ban which the in-core object is to point to based on the persisted ban time.
This is highly inefficient because `BAN_FindBAN()` conducts a linear search of the ban list, for which we would expect about half the bans to need inspection if objects were distributed equally across all bans. But for a long BAN list, most objects will hang near the bottom, so chances are high that we actually need to traverse nearly _all_ of the ban list for each loaded object.
So this screams for turning the ban list into a different data structure, like a binary tree.
Yet once loading of objects is complete, the ban list as we have it is optimal: All …
=> Add BANIDX facility to speed up BAN loading

include/tbl/params.h
Spotted during a discussion with @walid-git.
=> param: Off by one maximum http_req_overflow_status

bin/varnishd/common/common_vsc.c, include/vrt.h, lib/libvsc/vsctool.py
VRT_VSC_Alloc requires `va_list` which isn't available on all platforms in `rust`. To bridge this FFI gap, provide a variadic version of it.
=> introduce VRT_VSC_AllocVariadic

bin/varnishtest/tests/m00003.vtc, bin/varnishtest/tests/m00055.vtc, doc/sphinx/reference/vmod.rst, lib/libvcc/vcc_expr.c, lib/libvcc/vcc_vmod.c, lib/libvcc/vmodtool.py, vmod/vmod_std.vcc, vmod/vmod_std_conversions.c
I tried gcc version 15.0.0 20241203 and even without -std=c23, it would reserve "bool":
```
In file included from vcc_std_if.c:10:
vcc_std_if.h:78:33: error: two or more data types in declaration specifiers
78 |         VCL_BOOL                bool;
|                                 ^~~~
```
(and more)
So this patch adds the option to specify the c name of arguments to vmod functions/methods by separating it with a colon:
vclname:cname
We use this facility to rename the "bool" argument to vmod_std functions to "boola".
**Implementation**
cname needs to be specified by the VMOD author because it is also used in the vmod implementation.
Obviously, VCC needs to know that name, too, to generate argument structs, so we need to transport it from the VMOD to VCC via the JSON spec. A logical …
=> vmodtool: Add option to specify c names of arguments and avoid "bool"

tools/import_vtree_from_freebsd.sh
This is an attempt at adding assertions without keeping track of a specific line of code. Tested with tree.h from the current tip of the main branch.
Refs freebsd/freebsd-src@a962800a09a45b8f702ebd1a06b8f20bc84e97b1
=> vtree: Inject contextual parent checks during import

.circleci/Dockerfile, .circleci/config.yml
`awk` is apparently not installed by default on `fedora:42` images
=> [ci] fedora:42 needs awk

.circleci/Dockerfile, .circleci/config.yml, bin/varnishd/http1/cache_http1_vfp.c, bin/varnishtest/tests/f00016.vtc, bin/varnishtest/tests/m00003.vtc, bin/varnishtest/tests/m00055.vtc, bin/varnishtest/tests/r01184.vtc, bin/varnishtest/tests/r01506.vtc, bin/varnishtest/tests/r01729.vtc, configure.ac, doc/changes.rst, doc/sphinx/reference/vmod.rst, lib/libvcc/vcc_expr.c, lib/libvcc/vcc_vmod.c, lib/libvcc/vmodtool.py, vmod/vmod_blob.h, vmod/vmod_blob_base64.c, vmod/vmod_blob_hex.c, vmod/vmod_std.vcc, vmod/vmod_std_conversions.c
=> Prepare for 7.6.3

.circleci/Dockerfile, .circleci/config.yml, bin/varnishd/http1/cache_http1_vfp.c, bin/varnishtest/tests/f00016.vtc, bin/varnishtest/tests/m00003.vtc, bin/varnishtest/tests/m00055.vtc, bin/varnishtest/tests/r01184.vtc, bin/varnishtest/tests/r01506.vtc, bin/varnishtest/tests/r01729.vtc, configure.ac, doc/changes.rst, doc/sphinx/reference/vmod.rst, lib/libvcc/vcc_expr.c, lib/libvcc/vcc_vmod.c, lib/libvcc/vmodtool.py, vmod/vmod_blob.h, vmod/vmod_blob_base64.c, vmod/vmod_blob_hex.c, vmod/vmod_std.vcc, vmod/vmod_std_conversions.c
=> Prepare for 7.7.1

bin/varnishd/mgt/mgt_param.c, bin/varnishd/mgt/mgt_param_tweak.c, bin/varnishtest/tests/r04323.vtc, doc/sphinx/users-guide/run_security.rst
param: Move alias resolution before protected check
Instead of resolving tweaks when the function is called, this is now
done in the MGT code performing the protected check. Since aliases may
be used to reset a single bit of another parameter (namely vcc_feature)
the default value is looked up before the alias resolution.
Unfortunately, that also means resolving deprecated aliases before
showing them to the user, adding a little bit of duplicated logic.
Refs #4323
=> param: Move alias resolution before protected check

doc/sphinx/users-guide/increasing-your-hitrate.rst
This typo exists in older versions of the documentation as well.
=> doc: Fix typo (increasing-your-hitrate.rst)

bin/varnishd/cache/cache.h, bin/varnishd/cache/cache_deliver_proc.c, bin/varnishd/cache/cache_filter.h, bin/varnishd/cache/cache_gzip.c, bin/varnishd/cache/cache_main.c, bin/varnishd/cache/cache_obj.c, bin/varnishd/cache/cache_obj.h, bin/varnishd/cache/cache_range.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishd/http1/cache_http1_line.c, bin/varnishd/storage/storage_persistent.c, bin/varnishd/storage/storage_simple.c, bin/varnishtest/tests/c00111.vtc, bin/varnishtest/tests/m00061.vtc, vmod/automake_boilerplate_debug.am, vmod/vmod_debug.c, vmod/vmod_debug.h, vmod/vmod_debug.vcc, vmod/vmod_debug_transport_vai.c
... where _of course_ AI stands for **Asynchronous Iterators** ;)
This PR might be more extensive than others, and I would like to ask reviewers to lean back and take some time for it. Thank you in advance to anyone who invests their time into looking at this.
The PR description has been written to give an overview; individual commit messages have more details.
While the code proposed here works, and I am already building on top of it, I am deliberately marking this PR as a draft to make clear that I am very interested in feedback and comments before committing to a particular interface. Also I expect sensible changes to arrive still, but the fundamentals are ripe, IMHO.
This PR suggests a new API to enable use of asynchronous I/O on the delivery side of Varnish-Cache. The design has been …
=> Prepare Varnish-Cache for the age of AI

bin/varnishd/cache/cache_req_fsm.c, bin/varnishd/http1/cache_http1_fetch.c, bin/varnishtest/tests/c00055.vtc, bin/varnishtest/tests/c00067.vtc, bin/varnishtest/tests/f00001.vtc, bin/varnishtest/tests/f00016.vtc, bin/varnishtest/tests/r02722.vtc
This turns response status of req body errors into 400 instead of the generic 503.
Fixes #4329
=> Turn request body errors into 400 status

bin/varnishd/cache/cache_hash.c
With a lot of objects on the private objhead, the mtx would become contended.
We solve this contention by using an array of private objheads and spreading objects over the array elements using a fibonacci hash.
The choice of an array of objheads rather than an array of objhead pointers is motivated by hsh_deref_objhead_unlock(), which behaves differently for private objects. An alternative to the address check would be to add a flag field to struct objhead, but that would require to grow the struct (really not a good option for such a central data structure which, in many cases, is required once per object) or reduce the size of the magic value to 16 bits.
The drawback of the chosen solution is that flexelint thinks all objheads would need to be from the array, and hence reports out of …
=> Scale private oh

bin/varnishd/cache/cache_backend.c, bin/varnishd/cache/cache_conn_pool.c, bin/varnishd/cache/cache_vrt.c, bin/varnishd/cache/cache_vrt_var.c, include/vrt.h, lib/libvcc/vcc_token.c, vmod/vmod_blob.c, vmod/vmod_debug_acl.c, vmod/vmod_debug_filters.c, vmod/vmod_directors_shard.c, vmod/vmod_std_fileread.c
On 64bit, this basically comes for free because len is already aligned on 8 bytes.
Motivated by the void pointer type `VCL_BODY`, which is basically a union of a blob and a `struct strands` pointer.
Magic checks follow the rule:
- If a function accesses the object, add a check
- If a function only passes on the object, don't
before:
```c
(gdb) ptype /o struct vrt_blob
/* offset      |    size */  type = struct vrt_blob {
/*      0      |       4 */    unsigned int type;
/* XXX  4-byte hole      */
/*      8      |       8 */    size_t len;
/*     16      |       8 */    const void *blob;
/* total size (bytes):   24 */
}
```
after:
```c
(gdb) ptype /o struct vrt_blob
/* offset      |    size */  type = struct vrt_blob {
/*      0      |       4 */    unsigned int magic;
/*      4      | …
```
=> Give struct vrt_blob a magic value

bin/varnishd/cache/cache_shmlog.c, bin/varnishd/cache/cache_vrt.c, bin/varnishd/cache/cache_vrt_var.c, bin/varnishtest/tests/r01406.vtc, include/vrt.h, vmod/vmod_blob.c, vmod/vmod_blob_base64.c, vmod/vmod_blob_hex.c, vmod/vmod_blob_id.c, vmod/vmod_blob_url.c, vmod/vmod_debug.c, vmod/vmod_directors_hash.c, vmod/vmod_std.c, vmod/vmod_vtc.c
On 64bit, this basically comes for free because the pointer p is already aligned on 8 bytes.
Motivated by the void pointer type `VCL_BODY,` which is basically a union of a blob and a `struct strands`.
Magic checks follow the rule:
- If a function accesses the object, add a check
- If a function only passes on the object, don't
=> Give struct strands a magic value

bin/varnishstat/varnishstat.c, bin/varnishstat/varnishstat_options.h, doc/changes.rst
Simple quality-of-life improvement to automatically detect that the `varnishstat` output is being piped, and to use `-1` if that's the case.
=> [stat] use -1 is not outputting to a TTY

bin/varnishd/http2/cache_http2_proto.c, bin/varnishd/http2/cache_http2_send.c
When queing for send during rapid reset handling on incoming frame, it is `h2->req0` that should be used for queueing, not the `struct h2_req` of the stream for which we are handling the incoming frame. This error would lead to the queue structure becoming corrupted.
=> H2: Use the correct queue context when sending rapid reset goaway

bin/varnishd/cache/cache_main.c, bin/varnishd/cache/cache_varnishd.h, bin/varnishd/cache/cache_vcl.c, bin/varnishd/storage/stevedore.c, bin/varnishtest/tests/r01506.vtc
[A panic with SLASH/fellow](https://gitlab.com/uplex/varnish/slash/-/issues/61) exposed a problem in Varnish-Cache: We shut down stevedores unconditionally, no matter if still used or not. While an argument could be made that stevedores should wait for all object references to be returned before actually shutting down (which SLASH/fellow does, but limited to a fixed number of retries), this would not have helped in this particular case, because a `.free_space` variable was queried which, by definition, requires no reference on stevedore objects whatsoever.
So this PR adds `VCL_Shutdown()` to wait for all VCL references to vanish before closing stevedores.
=> Add VCL_Shutdown to wait for VCL references to vanish

bin/varnishd/builtin.vcl, bin/varnishd/cache/cache_req_fsm.c, bin/varnishtest/tests/r01524.vtc, bin/varnishtest/tests/r01890.vtc, bin/varnishtest/tests/s00013.vtc, doc/changes.rst, doc/sphinx/reference/vcl-step.rst, doc/sphinx/reference/vcl_step.rst
It was agreed during a bugwash that we no longer want to pipe unknown request methods by default and instead return a synthetic 405 (Method Not Allowed) for the next 8.0 release.
Refs #3352
=> No builtin pipe

lib/libvarnish/vtcp.c, lib/libvarnish/vus.c
It was originally observed by @scance that unix-domain sockets were in a non-blocking state, which was unexpected. After some digging, he found the root cause and fixed it. It was also independently observed by @fwsGonzo.
This patch series ensures that all successful outcomes of `V{TCP,US}_connect()` calls yield a socket in blocking mode for consistency.
=> vtcp,vus: Consistently establish blocking connections

bin/varnishd/cache/cache_range.c, bin/varnishtest/tests/r04336.vtc
The added VTC contains a test case for a (crude) partial caching pattern in VCL, which stopped working with 4ab110047130e3a89936104d74f4729b650676f9 because the Range header to check is taken from bereq0, rather than bereq, which VCL has under control and is also the request sent to the backend.
Ref #3246
=> cache_range: Bring back VCL control over backend range Requests

bin/varnishd/cache/cache_vcl.c, bin/varnishtest/tests/c00077.vtc
labels are struct vcl objects for which most members are empty/null, with the label member pointing to the labeled vcl.
As such, label vcl objects also have no vdire struct. Hence, when iterating over VCLs to find backends, labels need to be skipped.
=> fix backend.list x.y when labels are in use
