- bin/varnishhist/Makefile.am
- bin/varnishhist/varnishhist.c
- bin/varnishhist/varnishhist_options.h
- bin/varnishhist/varnishhist_profiles.h
- bin/varnishlog/varnishlog_options.h
- bin/varnishncsa/varnishncsa_options.h
- bin/varnishstat/varnishstat.c
- bin/varnishtop/varnishtop_options.h
- doc/changes.rst
- doc/sphinx/reference/varnishhist.rst
- include/vapi/vapi_options.h
- include/vut_options.h
This is my backport of #2023, made from the list @nigoroll provided and @Dridi added to. I have tested it by running a bit and seeing that it looks sane, but nothing more. If anyone else wants to have a look at the patches and/or run this before I commit, please do.
The plan is to shove all of this into the 4.1 branch tomorrow around lunch.
> 4.1 backport 2023

- bin/varnishd/cache/cache_acceptor.c
- bin/varnishd/cache/cache_backend_cfg.c
- bin/varnishd/cache/cache_backend_probe.c
- bin/varnishd/cache/cache_vcl.c
- bin/varnishd/flint.lnt
- bin/varnishd/http1/cache_http1_line.c
- bin/varnishd/http2/cache_http2_deliver.c
- bin/varnishd/http2/cache_http2_panic.c
- bin/varnishd/http2/cache_http2_proto.c
- bin/varnishd/http2/cache_http2_send.c
- bin/varnishd/proxy/cache_proxy_proto.c
- bin/varnishd/storage/mgt_storage_persistent.c
- bin/varnishd/storage/storage_persistent.c
- bin/varnishd/storage/storage_persistent_silo.c
- bin/varnishd/storage/storage_umem.c
- bin/varnishd/waiter/cache_waiter_kqueue.c
- lib/libvmod_debug/vmod_debug.c
- lib/libvmod_debug/vmod_debug_dyn.c
- lib/libvmod_directors/hash.c
- lib/libvmod_directors/random.c
- lib/libvmod_directors/shard_dir.c
- lib/libvmod_directors/shard_hash.c
- lib/libvmod_directors/vmod_shard.c
- lib/libvmod_std/vmod_std.c
- lib/libvmod_std/vmod_std_conversions.c
- lib/libvmod_std/vmod_std_fileread.c
> 20161209 flexelint

- bin/varnishd/cache/cache_backend_probe.c
- bin/varnishtest/tests/o00004.vtc
Fixes #2151, ~~probably a good candidate for 4.1 too~~.
> Send PROXY headers with probes

- lib/libvarnish/vtim.c
> Fix typo in lib/libvarnish/vtim.c

- doc/sphinx/installation/install.rst
In the section related to make test, the sentences were a bit hard incorrect. I've corrected it.
> Corrected grammar for install.rst

- bin/varnishd/main.vsc
> VSC n_vcl, n_vcl_avail, n_vcl_discard are gauge (master)

- include/tbl/vsc_f_main.h
> VSC n_vcl, n_vcl_avail, n_vcl_discard are gauge

- bin/varnishd/cache/cache_hash.c
- bin/varnishd/cache/cache_vrt.c
- bin/varnishd/hash/hash_slinger.h
- bin/varnishtest/tests/m00031.vtc
- bin/varnishtest/tests/r02339.vtc
- configure.ac
- doc/sphinx/Makefile.am
- include/vrt.h
- lib/Makefile.am
- lib/libvmod_debug/vmod.vcc
- lib/libvmod_debug/vmod_debug.c
- lib/libvmod_purge/Makefile.am
- lib/libvmod_purge/flint.sh
- lib/libvmod_purge/vmod.vcc
- lib/libvmod_purge/vmod_purge.c
- man/Makefile.am
This module offers a finer-grained control over purges, in the old
pre-vcl 4.0 style. For that, the signatures of VRT_purge and HSH_Purge
were updated to inform about the number of rearmed objects.
Initially suggested in #2339, it was agreed on IRC to review such a VMOD.
> Introduce vmod-purge

- bin/varnishd/cache/cache_vcl.c
The locking around the use of vcl_active does not include the checking
of its magic value or the temperature asserts, leading to a race when
changing vcl_active.
Fixes: #2390
> Straighten locking wrt vcl_active

- bin/varnishd/cache/cache_req_fsm.c
Also add asserts for the references held in req->objcore and
req->stale_oc.
The test case for #1807 catches this bug after adding the asserts.
Fixes: #2502
> Deref the objcore before switching to synth on error.

- bin/varnishd/http2/cache_http2_proto.c
Timing out an H/2 session needs to take into account any active streams being processed.
This fix should also hopefully contribute to t02003.vtc showing up less frequently in VTEST.
> Avoid premature H/2 session close

- lib/libvcc/vmodtool.py
.keys() doesn't produce a list in python3, only an iterable view
> python3 compatibility

- lib/libvcc/vsctool.py
> bytearray needs an encoding in python3

- bin/varnishtest/tests/a00002.vtc
- bin/varnishtest/tests/a00003.vtc
- bin/varnishtest/tests/a00004.vtc
- bin/varnishtest/tests/a00005.vtc
- bin/varnishtest/tests/a00006.vtc
- bin/varnishtest/vtc.h
- bin/varnishtest/vtc_client.c
- bin/varnishtest/vtc_http.c
- bin/varnishtest/vtc_server.c
- include/Makefile.am
- include/vus.h
- lib/libvarnish/Makefile.am
- lib/libvarnish/vus.c
This supersedes PR #2371, in light of @bsdphk's decisions in his mail to varnish-dev on Feb 13th 2018. See #2371 and the mail for details.
I'll be adding commits to this branch/PR incrementally as we go along.
> Support Unix domain sockets

- bin/varnishtest/tests/r02686.vtc
- bin/varnishtest/tests/u00004.vtc
- bin/varnishtop/varnishtop.c
- bin/varnishtop/varnishtop_options.h
Fixes #2686, bonus docfix and coverage for `-f`.
Please see individual commits for details.
> varnishtop -1, -d and -f

- bin/varnishd/VSC_vbe.vsc
- bin/varnishd/cache/cache_backend.c
- bin/varnishd/cache/cache_backend_probe.c
- bin/varnishd/cache/cache_tcp_pool.c
- bin/varnishd/cache/cache_tcp_pool.h
- include/tbl/params.h
> vbe open error statistics and holddown

- lib/libvcc/vcc_expr.c
minor cleanup and additional assertions to vcc code generation for vmod function arguments:
* We remove setting function argument names to the empty string such that there are only two cases left: either the function argument name is NULL or points to a proper name
* We assert that only named arguments can be possibly be speficied multiple times at this place in the code
* We assert that only named arguments can be optional
* We add handling for positional arguments being missing
> vcc: vmod function named argument clarifications

- configure.ac
- doc/changes.rst
> Prepare for 6.0.1

- doc/sphinx/whats-new/upgrading-6.1.rst
As far as I can see, the documentation is correct, but I suggest a slight update to the text. Take it or leave it.
> Simple addition on req.grace

- bin/varnishd/VSC_main.vsc
> Fix varnish_vsc metrics type

- bin/varnishd/cache/cache.h
- bin/varnishd/cache/cache_acceptor.c
- bin/varnishd/cache/cache_backend.c
- bin/varnishd/cache/cache_backend.h
- bin/varnishd/cache/cache_backend_probe.c
- bin/varnishd/cache/cache_lck.c
- bin/varnishd/cache/cache_tcp_pool.c
- bin/varnishd/cache/cache_tcp_pool.h
- include/vdef.h
- lib/libvarnish/vtim.c
this is far from complete, but before going through the whole tree and determining the proper type for all the uses of our doubles, @bsdphk please let me know if the simple basics are ok
> typedefs for real/mono time and durations

- bin/varnishd/cache/cache_vrt_priv.c
- bin/varnishd/mgt/mgt_pool.c
- bin/varnishtest/gensequences
- bin/varnishtest/tests/d00023.vtc
- bin/varnishtest/tests/v00041.vtc
- configure.ac
- doc/changes.rst
- include/tbl/params.h
- lib/libvmod_directors/shard_dir.c
This Pull Request for 6.0.2 release is the last chance to get in any last minute changes, for example in the change log. Release date is set to 2018-11-05, but it is negotiable.
> Prepare for 6.0.2

- bin/varnishd/cache/cache_hash.c
While we're doing a proper christmas cleaning of cache_hash.c, I figured we should deal with this one too.
Contrary to what the comment in ``hsh_deref_objhead_unlock`` says, req's on waiting list do indeed hold an objhead ref (``req->hash_objhead``), so the condition for the while loop in there will always evaluate to false.
This gets rid of the needless rushing code and replaces it with an assert.
> Clean up dead code in hsh_deref_objhead_unlock

- bin/varnishd/http2/cache_http2_proto.c
- bin/varnishtest/tests/t02012.vtc
> Fix max_concurrent_streams check(#2916)

- lib/libvarnish/vte.c
> ensure columns are separated by at least one space

- bin/varnishd/cache/cache_hash.c
- bin/varnishd/cache/cache_objhead.h
- bin/varnishd/cache/cache_req_fsm.c
- bin/varnishtest/tests/r02964.vtc
for anything but return (deliver)
Fixes #2963
>  Cancel a request for a private (streaming) object from vcl_deliver

- bin/varnishd/cache/cache_req_fsm.c
- bin/varnishtest/tests/c00028.vtc
> respect max_restarts and fix c00028.vtc

- lib/libvarnish/vin.c
If an absolute path is provided as n_arg with a length of exactly
PATH_MAX-1 then the combination of strcpy and strcat for the trailing
slash '/' overflows dn by one byte, writing its new null-terminating
character '\0' right after dn's upper bound.
By using a fixed-length VSB we can simply ensure that we stay within
bounds at a reasonable cost. Guarding VSB operations should silence
Flexelint as a nice side effect.
VIN_n_Arg is not exposed outside of the source tree, and both callers
today provide a valid dir argument, so we can now make it part of the
contract with an assertion, simplifying the strdup error handling.
> Kill strcat and strcpy usage in VIN_n_Arg

- bin/varnishd/common/common_vsmw.c
- include/vapi/vsm.h
- lib/libvarnishapi/vsc.c
- lib/libvarnishapi/vsm.c
Set of patches containing optimizations and bug fixes in the VSM and VSC. See the individual commit messages for details.
> Various VSM and VSC fixes and improvements

- .travis.yml
- bin/varnishd/Makefile.am
- bin/varnishd/cache/cache_panic.c
- configure.ac
- doc/changes.rst
offered as an alternative to #3034
> Use libunwind instead of libexecinfo

- doc/sphinx/reference/vcl.rst
- doc/sphinx/users-guide/vcl-backends.rst
Add documentation for the syntax
```backend name none;```
> Add Backend None Documentation

- bin/varnishd/cache/cache_acceptor.c
- bin/varnishd/cache/cache_ws.c
- bin/varnishd/storage/storage_persistent_subr.c
- bin/varnishd/storage/storage_umem.c
- bin/varnishtest/vtc_server.c
- bin/varnishtest/vtc_varnish.c
- include/vdef.h
> Add a fixed-buffer strcpy analogous to bprintf

- bin/varnishd/cache/cache_fetch.c
- bin/varnishd/cache/cache_req_fsm.c
- bin/varnishd/cache/cache_vcl.c
- bin/varnishd/cache/cache_vrt_vcl.c
- bin/varnishtest/tests/d00040.vtc
- bin/varnishtest/tests/v00041.vtc
- include/vrt.h
- lib/libvmod_debug/vmod.vcc
- lib/libvmod_debug/vmod_debug.c
This implements one of the possible options to approach #2997
> add ctx->handling and ctx->vsl for cli

- bin/varnishtest/tests/v00019.vtc
- bin/varnishtest/tests/v00020.vtc
- lib/libvcc/vcc_expr.c
I ran into this quirk and it ruffled my POLA.
> Allow non-literal negative VCL expressions

- lib/libvmod_proxy/vmod_proxy.c
> Correct WS allocation in tlv_string

- bin/varnishd/cache/cache_vrt_var.c
- bin/varnishtest/tests/r03079.vtc
- bin/varnishtest/tests/v00018.vtc
- include/vrt.h
- lib/libvcc/generate.py
- lib/libvcc/vcc_action.c
This is an alternative take on #3100 as per my review suggestions. This is not comprehensive in terms of concatenation compared to #3100 and is only meant as a minimal proof of concept that I may complete if requested.
> Teach libvcc more += operators

- bin/varnishtest/tests/c00035.vtc
- bin/varnishtest/tests/r02219.vtc
Back-port some VTC stabilization to 6.0
> 60 vtc backports

- bin/varnishtest/tests/r01821.vtc
pretty straight forward, cherry-picked
> r01821.vtc racy fix backport

- bin/varnishd/cache/cache_range.c
- bin/varnishtest/tests/c00100.vtc
This is a direct cherry-pick so enough said.
Cherry Picked from 649ad2ba79f44fb0213331e8692361d1f6aa0daa
> add if-range logic - backport 6.0

- bin/varnishd/cache/cache.h
- bin/varnishd/cache/cache_session.c
- bin/varnishd/cache/cache_vrt_var.c
- bin/varnishd/http1/cache_http1_deliver.c
- bin/varnishd/http1/cache_http1_fsm.c
- bin/varnishd/http2/cache_http2_proto.c
- bin/varnishtest/tests/b00068.vtc
- bin/varnishtest/tests/c00070.vtc
- bin/varnishtest/tests/s00010.vtc
- bin/varnishtest/tests/s00012.vtc
- doc/sphinx/reference/vcl_var.rst
and test that they work for H1
follow up #2981 
loosely related to #2980
> Add vcl control over timeout_linger, send_timeout, idle_send_timeout

- bin/varnishd/cache/cache_req_fsm.c
- configure.ac
- doc/changes.rst
- doc/sphinx/index.rst
- include/vrt.h
- lib/libvarnish/version.c
Following the relase checklist at https://github.com/varnishcache/varnish-cache/wiki/Release-procedure , I have now to the step where I push the changes. This PR is here so that the maintainers can have a brief look before I do so. I will push and close this PR when things have been verified.
> Prepare for 6.4.0

- .gitignore
- bin/varnishstat/Makefile.am
- bin/varnishstat/varnishstat.c
- bin/varnishstat/varnishstat.h
- bin/varnishstat/varnishstat_bindings.h
- bin/varnishstat/varnishstat_curses.c
- bin/varnishstat/varnishstat_help_gen.c
- bin/varnishtest/tests/r02990.vtc
- bin/varnishtest/tests/u00008.vtc
One of the items from #2990, It is currently lacking test coverage.
Otherwise, it works (on my machine).
> Interactive varnishstat help screen

- bin/varnishd/cache/cache_panic.c
minor improvements to be merged after release freeze
self-OKing, but now everyone has a chance to veto
> Panic pthread improvements

- bin/varnishd/cache/cache_vrt.c
- bin/varnishd/http2/cache_http2_deliver.c
- bin/varnishtest/tests/r03301.vtc
- doc/sphinx/reference/vcl_var.rst
- lib/libvcc/vcc_action.c
> Patches to address issue #3301

- bin/varnishd/mgt/mgt_child.c
- bin/varnishtest/tests/b00071.vtc
- bin/varnishtest/tests/u00011.vtc
- include/tbl/cli_cmds.h
Commits:
34d38f0b006482b58fc6b7bf3dc30ced6b7e2a66
(Clean Cherry Pick)
> Expose the master and worker PIDs via the CLI - Backport

- bin/varnishd/cache/cache_fetch.c
- bin/varnishd/cache/cache_rfc2616.c
- bin/varnishtest/tests/r03221.vtc
Commits:
aaaf7b383339b18f368935ff3fd38a6575c15666
b610e9a0b954fe963a86b95b44ee30089a9333d3
cff50548b9633b676d71fc82c9103b368807e9a3
(All clean cherry-picks)
> Age is dropped when passing backport

- bin/varnishd/cache/cache_director.c
- bin/varnishtest/tests/d00021.vtc
- include/vrt.h
- lib/libvcc/vcc_expr.c
This is an alternative implementation of #2680
VTC by @nigoroll from #2680
> Make .resolve() a type specific method of BACKEND (#2680 redux)

- .circleci/config.yml
https://github.com/varnishcache/pkg-varnish-cache/issues/139
Add packaging jobs for Ubuntu 20.04
> Issue pkg-varnish-cache/issues/139 - Add package for Ubuntu 20.04

- bin/varnishd/common/common_vsmw.c
- bin/varnishd/mgt/mgt_cli.c
- bin/varnishd/mgt/mgt_main.c
- bin/varnishd/mgt/mgt_vcl.c
- bin/varnishd/proxy/cache_proxy_proto.c
- bin/varnishtest/tests/r03038.vtc
- bin/varnishtest/tests/v00025.vtc
- bin/varnishtest/vtc_haproxy.c
- bin/varnishtest/vtc_http.c
- bin/varnishtest/vtc_process.c
- bin/varnishtest/vtc_proxy.c
- include/tbl/params.h
- include/vsb.h
- lib/libvarnish/vsb.c
- lib/libvarnishapi/libvarnishapi.map
- tools/coccinelle/vsb_tofile.cocci
Commit List:
https://github.com/varnishcache/varnish-cache/commit/b51bc4a787709d340d6753aa02025837183371c0
https://github.com/varnishcache/varnish-cache/commit/5d8a6c0012c05c2f095c3a59e9f1dbc89b9f2c55
https://github.com/varnishcache/varnish-cache/commit/3c87f32a341ce14a28f34067c29ef428466f2a48
https://github.com/varnishcache/varnish-cache/commit/0bff7aab71d0e2710cecacde1f0f10a99bfe7e80
https://github.com/varnishcache/varnish-cache/commit/cf14a0fd774fcbcd4bfd2d50bcbe029f63ff7e0e
https://github.com/varnishcache/varnish-cache/commit/c22ccdcb2c605a78ecc07ffef694f3e0d5a34cc1
https://github.com/varnishcache/varnish-cache/commit/20c8aafb281ed5693771d65dc4e33e827173946c
> Backport too many VCLs

- bin/varnishd/cache/cache_fetch.c
- bin/varnishtest/tests/v00064.vtc
Commits:
d3b6409ea3f52851aa63fde8120af5cfc430db8b
This PR supersedes #3278 with the fix @rezan mentioned.
> 304 no storage panic backport

- bin/varnishd/http1/cache_http1_vfp.c
- bin/varnishtest/tests/r03266.vtc
Fixes: #3266
Commits:
b8efd99aba079fe9bc92ec7f70a839527fff321a
> Backport ensure we don't recycle a closed backend connection

- bin/varnishd/cache/cache_vrt.c
- bin/varnishd/http2/cache_http2_deliver.c
- bin/varnishtest/tests/r03301.vtc
- doc/sphinx/reference/vcl_var.rst
- lib/libvcc/vcc_action.c
Commits:
ff8d29ae5a7e3eaeb30a4a7bf21efc89eed9f93a
aba2855cb947dd5aa9ca1a9680c330264b23925d
c7799008fe12b3bbd9ee95988700a081867a5859
4c1b0345d32a58a095768996ef03fab9aa878e5f
9494205f7379b598fbbefdb6fe853e7dcce7bba6
b71ccdeb8bda20cf37425b0622a0e06a6d7f45f3
Most of these were not clean cherry-picks had to be slightly changed
> Backport Patches to address issue #3301

- .circleci/make-deb-packages.sh
Add  _amd64|_arm64 before the extension
> [cci] Copy the .dsc file to the folder

- bin/varnishd/cache/cache_esi_fetch.c
- bin/varnishd/cache/cache_esi_parse.c
- bin/varnishd/cache/cache_gzip.c
- bin/varnishtest/tests/r03253.vtc
Commits:
0f3af407f65ac4bc6d446c61fb3e3b50747194cd
d1bd80e83a88a0caaaf7e5021472e23d244a8ac6
(This is a redo of #3284)
> ESI workspace assert - backport

- varnish.m4
With a separate autoconf macro to preserve existing behavior. While at it, I got rid of some intermediate processing in the generated configure script that should result in slightly smaller scripts for third party VMODs.
---
Use case prompted by @nigoroll, the existing macro in `varnish.m4` doesn't play well with dynamically generated VCC files at build time.
Not sure when this should be merged, the change speculatively targets Varnish 7 for the Sep 2020 release and would need to be amended if we end up with a 6.5 release. And that's typically the kind of thing we'd forget when it's release time.
This needs to be tested extensively, so far so good on my end.
> varnish.m4: Support generated VCC files

- lib/libvarnishapi/vsl_cursor.c
The log readers would not complete the acquire/release pair of memory
fence operations when waiting for new data to appear in the shared memory
log. With this, a VRMB() is issued after having waited for the
VSL_ENDMARKER disappears, and before using any data after it (including
the deciphered length data).
Ref: #3363
> Complete the VSL memory fence pair

- lib/libvarnish/vrnd.c
trivial patch, but going through a PR because it is a sensitive area:
Try to read into the buffer in one go.
closes #3366
> Optimize VRND_RandomCrypto()

- bin/varnishd/cache/cache_vrt.c
- bin/varnishtest/tests/r03308.vtc
- lib/libvarnish/vtim.c
https://github.com/varnishcache/varnish-cache/pull/3308
> Backport undefined VCL_TIME conversions

- bin/varnishd/cache/cache_backend.c
- bin/varnishd/cache/cache_director.c
- bin/varnishd/cache/cache_req_fsm.c
- bin/varnishd/cache/cache_vcl_vrt.c
- bin/varnishd/cache/cache_vrt_priv.c
- bin/varnishtest/tests/d00029.vtc
- bin/varnishtest/tests/d00030.vtc
- bin/varnishtest/tests/d00041.vtc
- bin/varnishtest/tests/r03329.vtc
- bin/varnishtest/tests/r03385.vtc
- lib/libvmod_directors/shard_cfg.c
- lib/libvmod_directors/shard_cfg.h
- lib/libvmod_directors/shard_dir.c
- lib/libvmod_directors/shard_dir.h
- lib/libvmod_directors/vmod.vcc
- lib/libvmod_directors/vmod_shard.c
Backport the new weight parameter for shard directors.
Reference: https://github.com/varnishcache/varnish-cache/commit/b90b60d0a066f1aa7302a70125cb91cdfa605119
> Backport shard weights

- doc/changes.rst
This is the potential changelog for 6.0.7. A few of these issues have not been merged, the plan is to merge them by EOW.
> 6.0.7 changelog

- bin/varnishd/cache/cache_req_fsm.c
- configure.ac
- doc/sphinx/index.rst
- include/vrt.h
- lib/libvarnish/version.c
> Prepare for 6.5.0

- bin/varnishd/http1/cache_http1_line.c
trivial patch on hold until after the freeze
> simplify workspace reservation handling in v1l

- bin/varnishd/cache/cache.h
- bin/varnishd/cache/cache_http.c
- bin/varnishd/cache/cache_req_fsm.c
- bin/varnishd/http1/cache_http1_fetch.c
- bin/varnishd/http2/cache_http2_deliver.c
Spotted by @mbgrydeland.
---
Wasn't sure whether this is below the review threshold.
> http: Record which peer wants to close the session

- configure.ac
- doc/changes.rst
- doc/sphinx/index.rst
- lib/libvarnish/version.c
This PR is created to initiate the final steps to releasing 6.0.7.
Anyone is welcome to comment here about the particular commit, and about the actual content of the release.
The release date is set just two days in the future. If any good reason to postpone this, let us know, and I will amend this PR.
> Prepare for 6.0.7

- bin/varnishd/mgt/mgt_main.c
> clean out vmod cache at startup

- configure.ac
> Fix autoconf error in version 2.70

- bin/varnishtest/tests/v00043.vtc
- lib/libvcc/generate.py
- lib/libvcc/vcc_compile.h
- lib/libvcc/vcc_expr.c
- lib/libvcc/vcc_vmod.c
> PoC: vcc: Restrict static PRIV_TOP scope

- bin/varnishd/VSC_vbe.vsc
Hopefully this will shed some light on how to read this counter
> document the happy counter

- bin/varnishd/builtin.vcl
- bin/varnishtest/tests/c00000.vtc
- doc/sphinx/users-guide/vcl-built-in-code.rst
- doc/sphinx/users-guide/vcl-built-in-subs.rst
- doc/sphinx/users-guide/vcl-syntax.rst
- doc/sphinx/users-guide/vcl.rst
- lib/libvcc/vcc_compile.c
- lib/libvcc/vcc_compile.h
- lib/libvcc/vcc_parse.c
#3484 rebased on top of current master based on a merge which I am already running in production
> Built-in VCL split

- .circleci/config.yml
- bin/varnishtest/witness.py
- configure.ac
- doc/sphinx/vtc-syntax.py
- include/generate.py
- include/tbl/style.py
- lib/libvcc/generate.py
- lib/libvcc/vmodtool.py
- lib/libvcc/vsctool.py
- tools/gcov_digest.py
- tools/include_wash.py
- varnish-legacy.m4
- varnish.m4
There were a few commits missing that didn't make it into 6.0, These were not apart of any PR.
> [LTS Backport] Finish up Python3 migration

- bin/varnishd/cache/cache_backend.c
- bin/varnishtest/tests/r03556.vtc
Original ticket: varnishcache/varnish-cache#3556
Commits to fix it:
varnishcache/varnish-cache@8976958
varnishcache/varnish-cache@b8a3753
> [LTS Backport] Backend fetch stall

- bin/varnishd/cache/cache_expire.c
- bin/varnishd/cache/cache_hash.c
- bin/varnishd/cache/cache_varnishd.h
- include/tbl/oc_exp_flags.h
Original ticket: varnishcache/varnish-cache#2999
Original PR: varnishcache/varnish-cache#3261
> [LTS Backport] Expiration race

- bin/varnishd/cache/cache_backend_probe.c
- bin/varnishd/http1/cache_http1_deliver.c
- bin/varnishd/http1/cache_http1_pipe.c
- bin/varnishd/http1/cache_http1_vfp.c
- bin/varnishd/http2/cache_http2_session.c
- bin/varnishd/proxy/cache_proxy_proto.c
- include/vtcp.h
- lib/libvarnish/vtcp.c
Original ticket: https://github.com/varnishcache/varnish-cache/issues/3415
Original PR: https://github.com/varnishcache/varnish-cache/pull/3430
> [LTS Backport] HTTP1 minimal response assert

- bin/varnishd/mgt/mgt_param.c
- include/vdef.h
- lib/libvarnish/vtcp.c
Original ticket: #3415
Original PR: #3430
Continuation of #3579
> [LTS Backport] Catch up VTCP fixes

- bin/varnishncsa/varnishncsa.c
- bin/varnishncsa/varnishncsa_options.h
- bin/varnishtest/tests/u00016.vtc
- doc/sphinx/reference/varnishncsa.rst
Fixes #3297
Co-authored-by: Ben Zvan <ben.zvan@target.com>
Co-authored-by: Jasmine Wang <jasmine.wang@target.com>
Co-authored-by: Jordan Christiansen <jordan.christiansen@target.com>
Co-authored-by: Madhavi Dintakurthy <madhavi.dintakurthy@target.com>
> varnishncsa: Add -j to format for JSON

- bin/varnishtest/tests/r00916.vtc
- bin/varnishtest/tests/v00016.vtc
- bin/varnishtest/tests/v00020.vtc
- lib/libvcc/vcc_acl.c
- lib/libvcc/vcc_action.c
- lib/libvcc/vcc_backend.c
- lib/libvcc/vcc_compile.h
- lib/libvcc/vcc_expr.c
- lib/libvcc/vcc_parse.c
- lib/libvcc/vcc_symb.c
- lib/libvcc/vcc_token.c
- lib/libvcc/vcc_types.c
- lib/libvcc/vcc_utils.c
- lib/libvcc/vcc_vmod.c
- lib/libvcc/vcc_xref.c
- tools/coccinelle/archive/vcc_peek.cocci
A side effect is slightly more accurate error messages.
Closes #3555
> vcc: Allow global symbols to be defined after use

- configure.ac
- include/Makefile.am
- include/vre_pcre2.h
- lib/libvarnish/vre.c
> How would we handle the pcre2_code typedef in VRE_unpack()?

- bin/varnishd/VSC_main.vsc
- bin/varnishd/cache/cache_esi_deliver.c
- bin/varnishtest/tests/e00003.vtc
Conflicts:
bin/varnishd/cache/cache_esi_deliver.c
> [Backport] Add MAIN.esi_req counter for ESI subrequests

- .circleci/config.yml
Submitted as a pull request only to make sure I'm not breaking the yaml thing.
> circleci: 32bit build on the oldest Ubuntu

- .circleci/config.yml
And bionic inherits the "oldest Ubuntu" 32bit setting.
---
Submitted as a pull request only to exercise CI first.
> circleci: Trade Ubuntu xenial for focal

- doc/sphinx/users-guide/command-line.rst
> Fix bullet list formatting

- bin/varnishadm/varnishadm.c
Or when the -p option is used.
Fixes #3687
> varnishadm: Only print the status in interactive mode

- bin/varnishd/cache/cache_req_fsm.c
- configure.ac
- doc/sphinx/index.rst
- doc/sphinx/whats-new/changes-7.0.rst
- doc/sphinx/whats-new/index.rst
- doc/sphinx/whats-new/upgrading-7.0.rst
- include/vrt.h
- lib/libvarnish/version.c
See slight changes made to the release process so far:
https://github.com/varnishcache/varnish-cache/wiki/Release-procedure/_compare/14f91b9d37832d5ad84e61d7bc0018f6bd76832d...84064e92862289f3aff23502ed10ddc3d2d4a0e2
> Prepare for 7.0.0

- bin/varnishd/cache/cache_session.c
- bin/varnishd/hpack/vhp_table.c
- bin/varnishd/http2/cache_http2_hpack.c
- bin/varnishd/storage/storage_simple.c
- include/miniobj.h
- lib/libvarnish/vev.c
It operates on a pointer like FREE_OBJ() and clears it.
> miniobj: Add a FINI_OBJ() macro

- bin/varnishd/Makefile.am
- bin/varnishd/fuzzers/esi_parse_fuzzer.c
While at it, try to better formalize all the setup steps.
---
Suggested by @bsdphk, but in light of 46e3f3fdfdea1e4bff7c323f4129593c66419245 I would like to get some feedback from @nigoroll to see whether it builds fine on SunOS.
> fuzz: Set up a workspace emulator in esi_parse_fuzzer

- bin/varnishd/cache/cache_acceptor.c
- bin/varnishd/cache/cache_vrt_var.c
- bin/varnishtest/tests/b00020.vtc
- bin/varnishtest/tests/b00021.vtc
- bin/varnishtest/tests/b00022.vtc
- bin/varnishtest/tests/b00023.vtc
- bin/varnishtest/tests/b00026.vtc
- bin/varnishtest/tests/s00010.vtc
- bin/varnishtest/tests/s00012.vtc
- bin/varnishtest/vtc_misc.c
- configure.ac
- include/tbl/params.h
- lib/libvarnish/vtcp.c
> build: Simply require that SO_???TIMEO are present

- lib/libvarnishapi/vsl_dispatch.c
See https://github.com/varnishcache/varnish-cache/pull/3451#issuecomment-949434399
> vsl: Give up when it's too late to buffer records (6.0)

- bin/varnishd/cache/cache_vcl.c
- bin/varnishd/cache/cache_vcl.h
- bin/varnishd/cache/cache_vrt_vcl.c
- bin/varnishd/mgt/mgt.h
- bin/varnishd/mgt/mgt_child.c
- bin/varnishd/mgt/mgt_main.c
- bin/varnishd/mgt/mgt_vcl.c
- bin/varnishtest/tests/u00000.vtc
- bin/varnishtest/tests/v00067.vtc
- doc/sphinx/reference/varnishd.rst
This PR consolidates the two PRs #3676 and #3711, ref previous discussions.
Please see the commit message of 2dca51cc09a6ac03738a48cb91f864a7bd667d42 for a summary of change of behaviour this patch set brings with it.
> Combine #3676 and #3711

- bin/varnishd/cache/cache_acceptor.c
- bin/varnishd/common/heritage.h
- bin/varnishtest/tests/b00020.vtc
- bin/varnishtest/tests/b00021.vtc
- bin/varnishtest/tests/b00022.vtc
- bin/varnishtest/tests/b00023.vtc
- bin/varnishtest/tests/b00026.vtc
- bin/varnishtest/tests/l00000.vtc
- bin/varnishtest/tests/r01804.vtc
- bin/varnishtest/tests/r02722.vtc
- bin/varnishtest/vtc_misc.c
- configure.ac
- include/tbl/params.h
- lib/libvarnish/vtcp.c
This backports the two PRs #3704 and #3732 to 6.0 LTS
> Backport #3704 and #3732

- vmod/vmod_std_conversions.c
Otherwise valid code can panic on workspace exhaustion:
std.ip(req.http.X-Real-IP, std.ip(req.http.X-Client-IP, client.ip))
If the nested std.ip() call runs out of workspace, it will return a null
ip instead of the fallback, and since the outer std.ip() call is getting
a fallback argument, it will panic upon checking the suckaddr sanity.
Refs a3b26d0ba7dd8763a4e34d9e18d92fc24f1c291c
> std.ip: Always provide some form of fallback

- .circleci/config.yml
- .circleci/make-rpm-packages.sh
> circleci: Add fedora jobs and migrate centos:8 jobs

- .circleci/config.yml
- .circleci/make-rpm-packages.sh
- doc/sphinx/installation/install_redhat.rst
- doc/sphinx/whats-new/changes-trunk.rst
Do not merge before the last commit (48371e5ff4c461502825a0862939ee14a5a7be77) goes away,
> circleci: Don't drop el8 packaging just yet

- varnish-legacy.m4
- varnish.m4
Maybe it is good idea to introduce also `--with-python=PATH` but I haven't use any real use case for this
> Added support of python 3.10

- configure.ac
> Add -fno-var-tracking-assignments to cc_command if accepted by the compiler

- bin/varnishd/cache/cache_vary.c
Just polish some bits which I noticed while working in something else.
On hold until after release.
flexelint has been run locally with no new reports.
> Polish vary code a bit

- lib/libvarnishapi/vsl_cursor.c
To be consistent with how the file cursor behaves, the close_fd field is duplicated in the mmap cursor. If a VUT replaces stdin's file descriptor with a regular file's fd using dup2(2), we don't want to close it just because we managed to mmap(2) it.
For some reason we don't use the closefd() macro in the VSL cursor code, potentially to avoid its underlying assertion in libvarnishapi.
On the other hand we do use it in other places:
$ git grep -l closefd -- lib/libvarnishapi/
lib/libvarnishapi/daemon.c
lib/libvarnishapi/vsm.c
So maybe in a subsequent change `(void)close(fd)` statements could turn into `closefd(&fd)` in vsl_cursor.c to harden those code paths as well.
> vslc: Plug mmap file descriptor leak

- bin/varnishd/mgt/mgt_main.c
> mgt: Remove vext_cache only when necessary

- bin/varnishtest/vtc.h
- bin/varnishtest/vtc_http.c
- bin/varnishtest/vtc_http.h
- bin/varnishtest/vtc_http2.c
- bin/varnishtest/vtc_main.c
A small grab bag of changes from downstream, see individual commits for details.
> varnishtest: File limits and timeouts

- .editorconfig
I am late to the party, but only learned about  https://editorconfig.org/ today and think that it could help us to keep our code consistent in style.
This is only a first baby step
> Humble beginnings with editorconfig

- bin/varnishd/cache/cache_vcl.c
- bin/varnishtest/tests/r02471.vtc
- bin/varnishtest/tests/u00000.vtc
- bin/varnishtest/tests/v00045.vtc
- include/vte.h
- lib/libvarnish/vte.c
A meeting was pushed today, so I was able to quickly do it.
> vte: Add support for left-justified fields

- .circleci/config.yml
doesn't cost much, and [it makes people happy](https://github.com/varnishcache/pkg-varnish-cache/issues/167)
> [6.0] add bookworm building+packaging

- .circleci/config.yml
if 6.0 is going to have it (#3974), `master` should too
> add bookworm building+packaging

- bin/varnishd/cache/cache_vrt_vcl.c
For the past days, I have been struggling with a [deadlock situation exposed with vmod_dynamic](https://github.com/nigoroll/libvmod-dynamic/issues/110) in VTC mode, which exists, I believe, also for production setups, but is unlikely to be hit.
I will give some background information, feel free to skip to "Details from the commit message" if you are not interested:
[vmod_dynamic](https://github.com/nigoroll/libvmod-dynamic) (originally authored by the _Distinguished web hater_ and later adopted under the current name by /me) implements `getaddrinfo()` or DNS based backends. It configures two to three layers of varnish directors: A first optional layer is for a service (SRV) name, the second layer is for a host (A/CNAME) and the third for actual IP addresses. IP Backends to the host layer …
> Avoid deadlock in VRT_AddDirector() when VCL is going cold

- bin/varnishd/cache/cache_conn_pool.c
Since, we seems to not use it at all.
> varnishd: kill the killlist

- bin/varnishd/http2/cache_http2_panic.c
This brings 20e007a5b17c1f68f70ab42080de384f9e192900 from master.
> Cast to (u)intmax_t for %ju and %jd

- .circleci/config.yml
This is an attempt at speeding up this job that usually takes three time as long as other distcheck jobs.
> circleci: Run sanitizers on a larger system

- .circleci/Dockerfile
- .circleci/config.yml
- .circleci/make-rpm-packages.sh
- bin/varnishtest/tests/b00058.vtc
- bin/varnishtest/tests/p00000.vtc
- bin/varnishtest/tests/s00003.vtc
https://github.com/varnishcache/varnish-cache/pull/4119 and other commit dependencies applied to the 7.5 branch.
>  circleci: Retire EOL platforms (7.5)

- .circleci/Dockerfile
- .circleci/config.yml
- .circleci/make-rpm-packages.sh
- bin/varnishtest/tests/b00058.vtc
- bin/varnishtest/tests/e00016.vtc
- bin/varnishtest/tests/e00030.vtc
- bin/varnishtest/tests/e00034.vtc
- bin/varnishtest/tests/l00003.vtc
- bin/varnishtest/tests/p00000.vtc
- bin/varnishtest/tests/r01737.vtc
- bin/varnishtest/tests/r01781.vtc
- bin/varnishtest/tests/r01878.vtc
- bin/varnishtest/tests/r02849.vtc
- bin/varnishtest/tests/s00003.vtc
- bin/varnishtest/tests/v00042.vtc
- bin/varnishtest/tests/v00043.vtc
https://github.com/varnishcache/varnish-cache/pull/4119 and other commit dependencies applied to the 7.4 branch.
>  circleci: Retire EOL platforms (7.4)

- lib/libvarnish/vev.c
The routine in VEV looping to report on all of the fd events gets confused if an event is removed while in another callback event.
This will typically cause the mgt event loop to just spin, making the manager unresponsive.
Original patch and commit message by Martin Blix Grydeland.
> Allow VEV_Stop() called from within a VEV callback

- bin/varnishtest/vtc_varnish.c
This aims at collecting varnishd's output when something went wrong in a test.
> VTC output race

- bin/varnishd/mgt/mgt_shmem.c
- include/tbl/params.h
64k ought to be enough for everyone. /s
> Add a parameter for the panic buffer size

- lib/libvarnish/vfl.c
- lib/libvarnish/vsb.c
- lib/libvarnish/vtcp.c
- lib/libvarnishapi/vsl.c
- lib/libvarnishapi/vsl_api.h
- lib/libvarnishapi/vsl_arg.c
- lib/libvcc/generate.py
- lib/libvcc/vcc_backend.c
- lib/libvcc/vcc_expr.c
- lib/libvcc/vcc_utils.c
- lib/libvcc/vcc_xref.c
- lib/libvcc/vmodtool.py
- lib/libvgz/README
- lib/libvsc/VSC_main.vsc
Split from https://github.com/varnishcache/varnish-cache/pull/4153/commits/c7ab855773ed40025dc49914896cd77b44d751e9
> Spelling lib

- include/tbl/cli_cmds.h
- include/tbl/obj_attr.h
- include/tbl/params.h
- include/tbl/vsl_tags.h
- include/vapi/vsl.h
- include/vapi/vsl_int.h
- include/vapi/vsm.h
- include/vbm.h
- include/vbm_test.c
- include/vrt.h
- include/vsb.h
- include/vut_options.h
Split from https://github.com/varnishcache/varnish-cache/pull/4153/commits/37a9ddbe2b833ff8d58c2c9d0cd9b1ac73314c57
> Spelling include

- bin/varnishd/cache/cache_conn_pool.c
The cost to find an existing connection in the pool can become expensive when the linked-list is long. Heavy use of dynamic backends could exhibit such behavior.
> vcp: use RB-tree to keep track of connection pools

- doc/sphinx/users-guide/vcl-backends.rst
Thank you for the documentation!
I'm on my way to have a full read of the tutorial and User Guide.
I'm not a native English person, so the original text could be valid but I think my little contribution improve a bit the comprehension.
> [doc] Update vcl-backends.rst - fix typos

- bin/varnishd/cache/cache_conn_pool.c
This was recently introduced in #4198 and observed on a CCI job failure. The race happens between the waiter thread and the CLI thread, a stack trace of both threads during the panic can be found in https://github.com/varnishcache/varnish-cache/issues/4260#issuecomment-2639365725.
The race is caused by the fact that we read `cp->n_kill` without holding the `cp` mutex in `VCP_RelPoll()`:
- The waiter thread (holding the mutex) sets `n_kill` to 0 and is then interrupted before being able to release the lock.
- The CLI thread reads `cp->n_kill` and calls `vcp_destroy()` on the connection pool, which in turn calls `Lck_Delete` on a lock still being hold by the waiter thread. 
Another occurrence of reading `n_kill` without holding the mutex  in `VCP_Rel` (which could potentially lead to a …
> VCP: Fix a race that leads to a panic when destroying connection pools 

- doc/sphinx/reference/varnishd.rst
- doc/sphinx/reference/vcl_var.rst
- doc/sphinx/users-guide/storage-backends.rst
following a discussion on discord I realized that we could be clearer about stevedore selection
> [doc] add some notes about storage selection

- doc/sphinx/reference/vtla.rst
> doc: Add a definition for VUT in VTLA
